### ISSUE TITLE
Picke problem with ann2snn

### ISSUE THREAD

**Issue by SRKH** [fangwei123456/spikingjelly#124]
I am running a modified version of your ann2snn example on Fashion-MNIST dataset:
[ann2snn.py.zip](https://github.com/fangwei123456/spikingjelly/files/7235375/ann2snn.py.zip)

However, it ended with the following error message:
`/anaconda3/lib/python3.8/site-packages/torch/serialization.py in _save(obj, zip_file, pickle_module, pickle_protocol)
    482     pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol)
    483     pickler.persistent_id = persistent_id
--> 484     pickler.dump(obj)
    485     data_value = data_buf.getvalue()
    486     zip_file.write_record('data.pkl', data_value, len(data_value))

AttributeError: Can't pickle local object '_o2p_converter.convert_matmul.<locals>.MatMul'`

**Comment by fangwei123456** [comment]
Hi, I run this code on ubuntu and the error is:

```
libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: google/protobuf/descriptor.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
```

Then I install a new protobuf and solve this problem:
`pip install protobuf==3.8`

**Comment by XiangyuMao1108** [comment]
File "cnn_mnist.py", line 219, in <module>
    main('./cnn_mnist')
  File "cnn_mnist.py", line 194, in main
    snn = onnxparser.parse(ann, norm_data.to(parser_device))

_pickle.PickleError: can't pickle repeated message fields, convert to list first

请问一下这个error如果修复？

**Comment by fangwei123456** [comment]
> File "cnn_mnist.py", line 219, in main('./cnn_mnist') File "cnn_mnist.py", line 194, in main snn = onnxparser.parse(ann, norm_data.to(parser_device))
> 
> _pickle.PickleError: can't pickle repeated message fields, convert to list first
> 
> 请问一下这个error如果修复？

这个错误应该已经修复过了 https://github.com/fangwei123456/spikingjelly/issues/70

**Comment by XiangyuMao1108** [comment]
很感谢您的答复。
我有尝试您所说的onnx ,torch版本啥的，但我还是有这个issue. 至于关于所说的torch_save 不能保存dict，需要转成list先我有点暂时没弄明白。还有您所说的已经修复是指您的code已经更新过这个bug了嘛(bug free了)？我是上个月才download的，所以我不确定我现在的是不是最新的那个版本。

**Comment by lovingpolar** [comment]
我希望将cnn_mnist.py的bias设置成false，ann可训练，在转换成snn时报错AttributeError: type object '_o2p_converter' has no attribute 'convert_matmul'，请问如何修改

**Comment by lovingpolar** [comment]
您好，我想把cnn_mnist.py的卷积跟全连接的bias设置成false，ann可以训练，但到转换成snn时却会报错AttributeError: type object '_o2p_converter' has no attribute 'convert_matmul'，请问有无方法实现

**Comment by fangwei123456** [comment]
> 您好，我想把cnn_mnist.py的卷积跟全连接的bias设置成false，ann可以训练，但到转换成snn时却会报错AttributeError: type object '_o2p_converter' has no attribute 'convert_matmul'，请问有无方法实现

请另开一个issue，附上可以复现bug的代码吧

**Comment by fangwei123456** [comment]
现在不使用onnx 应该没有bug了

**Comment by fangwei123456** [comment]
> I am running a modified version of your ann2snn example on Fashion-MNIST dataset: [ann2snn.py.zip](https://github.com/fangwei123456/spikingjelly/files/7235375/ann2snn.py.zip)
> 
> However, it ended with the following error message: `/anaconda3/lib/python3.8/site-packages/torch/serialization.py in _save(obj, zip_file, pickle_module, pickle_protocol) 482 pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol) 483 pickler.persistent_id = persistent_id --> 484 pickler.dump(obj) 485 data_value = data_buf.getvalue() 486 zip_file.write_record('data.pkl', data_value, len(data_value))
> 
> AttributeError: Can't pickle local object '_o2p_converter.convert_matmul..MatMul'`

Now we do not use ONNX. This bug will not happen.
