### ISSUE TITLE
进行DVS128分析时出现的问题

### ISSUE THREAD

**Issue by star-123456** [fangwei123456/spikingjelly#125]
我在使用:~$ python -m spikingjelly.clock_driven.examples.classify_dvsg -data_dir /home/yangdayou/datasets/DVS128Gestur -out_dir ./logs -amp -opt Adam -device cuda:0 -lr_scheduler CosALR -T_max 64 -cupy -epochs 1024这个命令时，出现了如下报错：
Cupy is not installed.
Namespace(T=16, T_max=64, amp=True, b=16, channels=128, cupy=True, data_dir='/home/yangdayou/datasets/DVS128Gestur', device='cuda:0', epochs=1024, gamma=0.1, j=4, lr=0.001, lr_scheduler='CosALR', momentum=0.9, opt='Adam', out_dir='./logs', resume=None, step_size=32)
Traceback (most recent call last):
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/examples/classify_dvsg.py", line 428, in <module>
    main()
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/examples/classify_dvsg.py", line 265, in main
    if args.cext:
AttributeError: 'Namespace' object has no attribute 'cext'
请问应该怎么解决

**Comment by Yanqi-Chen** [comment]
看起来是旧版本的代码，可以尝试git pull到最新版本，现在使用的是cupy
https://github.com/fangwei123456/spikingjelly/blob/86041fcd6716e865ccd69dcd72b4f2dd1f229796/spikingjelly/clock_driven/examples/classify_dvsg.py#L265

**Comment by Yanqi-Chen** [comment]
> Cupy is not installed

以及需要安装cupy，这个目前还没有放进dependency，但是对于训练是必要的。

看起来你是用的是conda，安装可以参考这个教程
https://docs.cupy.dev/en/stable/install.html#installing-cupy-from-conda-forge

**Comment by star-123456** [comment]
> > Cupy is not installed
> 
> 以及需要安装cupy，这个目前还没有放进dependency，但是对于训练是必要的。
> 
> 看起来你用的是conda，安装可以参考这个教程
> https://docs.cupy.dev/en/stable/install.html#installing-cupy-from-conda-forge

感谢，更新了代码之后问题确实解决了，第一次直接安装的是0.0.0.0.6版本的sj，我在进行覆盖代码时发现存在spikingjelly和spikingjelly-0.0.0.0.6.dist-info两个文件夹，请问第二个文件夹有什么作用，更新代码时是否需要删除

**Comment by fangwei123456** [comment]
spikingjelly-0.0.0.0.6.dist-info是pip安装的中间产物，直接删除就行了
