### ISSUE TITLE
Visualizing可视化问题

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#127]
就比如visualizing.plot_2d_heatmap()，我将img->spikes，一般经过Spikingjelly处理完的数据是5D array，我打印了spikes的shape是（20，），将这个脉冲作为输入，在T时刻就产生了 s_list 和 v_list，生成的是v_list我查看是5D array。但是可视化需要的是2D array，那该如何转化才能转成2D的呢？

**Comment by fangwei123456** [comment]
`plot_2d_heatmap`需要输入是`shape=[T, N]`的数组，因为画出的图像是二维的，所以不能支持更高维度的数据输入。你可以将高维的数据reshape成二维：

```python
import torch

x = torch.rand([2, 3, 4, 5, 6])
y = x.flatten(1)
print(y.shape)
```

**Comment by BugCodeHub** [comment]
好的，但是有个问题就是我们reshape后，就比如MNIST是（50，1，1，28，28）转成了（50，748），这样neuron Index不就增加了很多

**Comment by BugCodeHub** [comment]
![image](https://user-images.githubusercontent.com/33653847/135044516-5dc5975d-5e3b-4fa9-9b44-548a596bfddf.png)
sh生成这样的图片的话，那上下两部部分是没有电压的吗

**Comment by Yanqi-Chen** [comment]
> 好的，但是有个问题就是我们reshape后，就比如MNIST是（50，1，1，28，28）转成了（50，748），这样neuron Index不就增加了很多

除了第一个维度表示时间之外，其他维度都是神经元的空间分布。展平就相当于不在乎具体的空间分布，但神经元数量不会有变化

**Comment by fangwei123456** [comment]
是的，一般卷积层的神经元脉冲发放很稀疏，所以如果直接把脉冲全部画出来，大部分为0是正常的。

**Comment by BugCodeHub** [comment]
好的，谢谢了！

**Comment by BugCodeHub** [comment]
> > 好的，但是有个问题就是我们reshape后，就比如MNIST是（50，1，1，28，28）转成了（50，748），这样neuron Index不就增加了很多
> 
> 除了第一个维度表示时间之外，其他维度都是神经元的空间分布。展平就相当于不在乎具体的空间分布，但神经元数量不会有变化

那就相当于我们拉平之后，Neuron Index只是相对的位置，该位置对应T时刻中的膜电位变化，是这样理解的吗

**Comment by Yanqi-Chen** [comment]
> > > 好的，但是有个问题就是我们reshape后，就比如MNIST是（50，1，1，28，28）转成了（50，748），这样neuron Index不就增加了很多
> > 
> > 
> > 除了第一个维度表示时间之外，其他维度都是神经元的空间分布。展平就相当于不在乎具体的空间分布，但神经元数量不会有变化
> 
> 那就相当于我们拉平之后，Neuron Index只是相对的位置，该位置对应T时刻中的膜电位变化，是这样理解的吗

是的，比如你的例子里输入是28x28的img，对应的就是28x28=784个脉冲神经元

**Comment by BugCodeHub** [comment]
> > > > 好的，但是有个问题就是我们reshape后，就比如MNIST是（50，1，1，28，28）转成了（50，748），这样neuron Index不就增加了很多
> > > 
> > > 
> > > 除了第一个维度表示时间之外，其他维度都是神经元的空间分布。展平就相当于不在乎具体的空间分布，但神经元数量不会有变化
> > 
> > 
> > 那就相当于我们拉平之后，Neuron Index只是相对的位置，该位置对应T时刻中的膜电位变化，是这样理解的吗
> 
> 是的，比如你的例子里输入是28x28的img，对应的就是28x28=784个脉冲神经元

好的，谢谢了！
