### ISSUE TITLE
是否有打算整合SpykeTorch的项目代码

### ISSUE THREAD

**Issue by densechen** [fangwei123456/spikingjelly#13]
你好，SpykeTorch也是基于PyTorch框架开发的。但是这个项目已经是两年前的产品了。
然而其中的一些函数代码和模型以及一些设计思想应该可以高效的整合进来
请问你们有打算整合SpykeTorch的项目代码吗？

**Comment by fangwei123456** [comment]
SpykeTorch我不是很了解，大致看了一下，是纯python实现，某些功能或设计思想如果想加进来，难度应该不大。是希望整合哪些功能？

**Comment by fangwei123456** [comment]
手滑按错成关闭了

**Comment by densechen** [comment]
🐥🐥🐥
![image](https://user-images.githubusercontent.com/14089191/95766560-03c22a80-0ce6-11eb-886c-2ced0c5acd98.png)
https://github.com/XDUSPONGE/SNN_benchmark?utm_source=catalyzex.com
感谢及时回复

目前来说，这几个框架都是基于PyTorch实现的。但是，都是一两年前的了，而且都没有更新维护了。
每一个框架都有一些特点。
我不知道这个对你们开发这个新的框架会不会有些参考。
目前来说，这个项目是我看到的最新，而且是国内开发的💪🏻

**Comment by fangwei123456** [comment]
感谢支持。以往的大多数框架都侧重生物可解释性（例如PySNN, SpykeTorch），使用STDP之类的规则来学习。Nengo-DL是一个特例，它是可以做深度学习的，因其基于TensorFlow，先训练一个ANN再转换成SNN。最新的3个框架里，BindsNet侧重生物可解释性，Norse和SpikingJelly是侧重深度学习的。Norse和SpikingJelly应该都是在去年下半年启动开发，但我们直到今年8月才注意到Norse这个框架。Norse和SpikingJelly的设计思路类似，但代码风格不太相同。
