### ISSUE TITLE
关于cifar10_r11_enabling_spikebased_backpropagation.py 

### ISSUE THREAD

**Issue by EmmmaEric** [fangwei123456/spikingjelly#136]
您好，　我能请问一下您在这个example中的spikingjelly/spikingjelly/clock_driven/examples/cifar10_r11_enabling_spikebased_backpropagation.py　运行环境设定嘛？(library version啥的）然后运行这个代码是直接python cifar10_r11_enabling_spikebased_backpropagation.py 后面加dataset的path嘛？

谢谢您的帮助

**Comment by Yanqi-Chen** [comment]
@EmmmaEric 如果还有任何问题可以重新打开issue
