### ISSUE TITLE
“神经形态数据集处理”教程中的代码有误

### ISSUE THREAD

**Issue by QgZhan** [fangwei123456/spikingjelly#138]
“神经形态数据集处理”教程中，“[获取Event数据](https://spikingjelly.readthedocs.io/zh_CN/0.0.0.0.4/clock_driven/13_neuromorphic_datasets.html#event)”小节：

`from spikingjelly.datasets import DVS128Gesture`
`root_dir = 'E:/datasets/DVS128Gesture'`
`train_set = DVS128Gesture(root_dir, train=True, use_frame=False)`
`test_set = DVS128Gesture(root_dir, train=True, use_frame=False)`

此处test_set与train_set完全相同。

**Comment by fangwei123456** [comment]
感谢。这个是004版本的文档，后来应该修复过了 https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/13_neuromorphic_datasets.html#event 。由于老版本已经发布过，所以不再更改了。

**Comment by QgZhan** [comment]
> 感谢。这是004版本的文档，以后应该修复过了https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/13_neuromorphic_datasets.html#event。由于旧版本已经过，所以不再更改了。

不好意思，才发现这是老版本的，多谢您的回复！
