### ISSUE TITLE
如何应用SNN在格式为三维数组的数据集上? 

### ISSUE THREAD

**Issue by XianWoo** [fangwei123456/spikingjelly#139]
您好, 我使用的数据集格式如下:
![image](https://user-images.githubusercontent.com/44899736/141928587-f657301a-bc20-4687-a7df-99ad6ed99336.png)

SpikingJelly给的案例均为图片数据集, 因此想请问如何替换为三维数组的数据集? 报错信息如下
![image](https://user-images.githubusercontent.com/44899736/141928477-1cf19a9f-1bde-4001-9e96-6f637b86149e.png)

**Comment by fangwei123456** [comment]
积分后的DVS数据就是三维的，`shape=[T, C, H, W]`，可以参考

https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/14_classify_dvsg.html
