### ISSUE TITLE
请问下，有什么方式来对spike的图片进行可视化？

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#140]

**Comment by fangwei123456** [comment]
https://spikingjelly.readthedocs.io/zh_CN/latest/spikingjelly.visualizing.html

**Comment by BugCodeHub** [comment]
想要的是对Frame进行可视化，就把DVS的图像显示出来

**Comment by fangwei123456** [comment]
用 https://spikingjelly.readthedocs.io/zh_CN/latest/spikingjelly.visualizing.html#spikingjelly.visualizing.plot_2d_spiking_feature_map 可以画多个时刻的单通道的frame

**Comment by BugCodeHub** [comment]
好的，感谢
