### ISSUE TITLE
from.. 和from.的相对路径问题一直出错，可不可以改成绝对路径

### ISSUE THREAD

**Issue by 2916656832** [fangwei123456/spikingjelly#143]
代码里面有许多引用from.. 和from.的相对路径问题一直出错，可不可以改成绝对路径！！！

**Comment by fangwei123456** [comment]
具体报错信息是？

**Comment by 2916656832** [comment]
以model下的sew_resnet.py为例    
from .. import functional
ImportError: attempted relative import with no known parent package

**Comment by 2916656832** [comment]
![微信截图_20211130135839](https://user-images.githubusercontent.com/50077562/143993752-73a2ce92-f06d-48bc-8133-d553a660ae98.png)

**Comment by fangwei123456** [comment]
python模块内部的代码，如果运行，应该按照 `python -m`的形式，例如

`python -m spikingjelly.clock_driven.examples.classify_dvsg -data_dir /userhome/datasets/DVS128Gesture -out_dir ./logs -amp -opt Adam -device cuda:0 -lr_scheduler CosALR -T_max 64 -cupy -epochs 1024`

**Comment by fangwei123456** [comment]
python模块内部通常用相对导入，例如

https://github.com/pytorch/vision/blob/48b82c11935c4058c68654fddbf5d73074fb9c40/torchvision/models/resnet.py#L7

**Comment by 2916656832** [comment]
谢谢大佬，非常幸运能与大佬对话！！
