### ISSUE TITLE
About max_pool in snn

### ISSUE THREAD

**Issue by Dignity-ghost** [fangwei123456/spikingjelly#145]
Dear authors,
  As I know, Maxpool in ANN should be converted to spike-format to be used in SNN. Such as according to accumulated membrane potential to choose the correct channel to pass spikes. In your repository, I found you use Maxpool directly in SNN. So if you mean just pool spikes is correct?

Hoping for your reply.

**Comment by fangwei123456** [comment]
It depends on your purpose to use pooling. In ANN2SNN, the max pooling in ANN is chosing maximum activations. Hence, in SNN converted from ANN, using max pooling directly is wrong because pooling spikes is not pooling firing rates.

**Comment by Dignity-ghost** [comment]
> It depends on your purpose to use pooling. In ANN2SNN, the max pooling in ANN is chosing maximum activations. Hence, in SNN converted from ANN, using max pooling directly is wrong because pooling spikes is not pooling firing rates.

Thanks for replying. I have a further question. In spiking_resnet.py, it seems the model use maxpool directly. I want to know whether using maxpool directly is available. If I train the model from zero, will maxpool without conversion work?

**Comment by Dignity-ghost** [comment]
> It depends on your purpose to use pooling. In ANN2SNN, the max pooling in ANN is chosing maximum activations. Hence, in SNN converted from ANN, using max pooling directly is wrong because pooling spikes is not pooling firing rates.

Thanks for replying. I have a further question. In spiking_resnet.py, it seems the model use maxpool directly. I want to know whether using maxpool directly is available. If I train the model from zero, will maxpool without conversion work?

**Comment by fangwei123456** [comment]
> I want to know whether using maxpool directly is available. If I train the model from zero, will maxpool without conversion work?

Yes. Max pooling works well in directly trained SNNs.

**Comment by Dignity-ghost** [comment]
Thank you very much.
