### ISSUE TITLE
`MultistepContainer` 没有 `reset` 方法

### ISSUE THREAD

**Issue by function2-llx** [fangwei123456/spikingjelly#146]
似乎是在 910d6b60d26148995d9f40144e99b63eabb500fc 被删除了，这样就无法运行[这篇文档](https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/10_propagation_pattern.html)中的示例。

**Comment by function2-llx** [comment]
应该用这样一段代码就可以了：
```python
def reset(self):
    for child in self.children():
        if hasattr(child, 'reset'):
            child.reset()
```

**Comment by fangwei123456** [comment]
在某个版本后，reset不再由class自行定义，所以新版的MultistepContainer没有写reset方法。把教程做了一下修复，用functional的reset函数去重置。

**Comment by function2-llx** [comment]
感觉可以顺便说说这里 `functional.reset_net` 的一个潜在的问题：`nn.Module` 的 `modules` 方法是会返回自身的，所以如果这个类自己也有 reset 方法的话会造成无限递归。

**Comment by fangwei123456** [comment]
> 感觉可以顺便说说这里 `functional.reset_net` 的一个潜在的问题：`nn.Module` 的 `modules` 方法是会返回自身的，所以如果被调用的对象自己也有 `reset` 方法的话会造成无限递归。

调用  `functional.reset_net` 的模块及其子模块不应该自行定义一个reset函数，否则会无限递归。模块本身含有reset函数是没有问题的：

```
from spikingjelly.clock_driven import layer, functional
import torch

class TestModuleA(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def reset(self):
        pass

class TestModuleB(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def reset(self):
        for m in self.modules():
            if hasattr(m, 'reset'):
                m.reset()

ta = TestModuleA()
functional.reset_net(ta)
print('reset ta')
tb = TestModuleB()
functional.reset_net(tb)
print('reset tb')
```

**Comment by function2-llx** [comment]
> 

我表述得不够准确，确实只要约定好 `reset` 只设置当前模块的相关内容就没问题了。

**Comment by function2-llx** [comment]
似乎文档渲染还存在问题？

![image](https://user-images.githubusercontent.com/38486514/144865563-b4a9e955-e43d-4fda-a898-35e84714a4b1.png)

**Comment by fangwei123456** [comment]
> 我表述得不够准确，确实只要约定好 `reset` 只设置当前模块的相关内容就没问题了。

是的，但这个约定很难保证让用户知道。但这不是问题，因为用户写错，运行就会报错，可以很快感知到。

**Comment by fangwei123456** [comment]
> 似乎文档渲染还存在问题？

代码忘了加缩进，已经修复了，服务器端重新编译应该就好了。
