### ISSUE TITLE
有没有做检测的转换

### ISSUE THREAD

**Issue by ryikl** [fangwei123456/spikingjelly#148]
你好，我对基于转换的脉冲神经网络很感兴趣，现在多数网络（转换和脉冲）都在做分类，我对是否有关于对检测网络的转换比较关心。谢谢！

**Comment by fangwei123456** [comment]
https://github.com/cwq159/PyTorch-Spiking-YOLOv3

**Comment by ryikl** [comment]
我想问的是，spikingjelly中有没有转换的代码，如果有的话，能说明在哪个文件里么，我没找到。谢谢

**Comment by fangwei123456** [comment]
https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/5_ann2snn.html

**Comment by ryikl** [comment]
我找到了用于分类的SNN仿真器，但是没找到用于检测的SNN仿真器

**Comment by fangwei123456** [comment]
用于检测的SNN和用于分类的SNN基本组件是一样的，但需要自行搭建

**Comment by ryikl** [comment]
好的，谢谢！
