### ISSUE TITLE
About Unsupervised Learning

### ISSUE THREAD

**Issue by 932179209** [fangwei123456/spikingjelly#15]
Hi！
It's a brilliant job to construct and improve spikingjelly.
And the question is, will spikingjelly support unsupervised learning such as STDP and so on? Cause unsupervised learning is a very important part and many researchers are on it.
Thanks for your time!

**Comment by Yanqi-Chen** [comment]
Thanks for your advice!
We have realized that unsupervised learning rules such as STDP and other Hebbian-based rules are hot areas. These are on our roadmap, while it will not be implemented shortly.
If what you need is GPU acceleration for these unsupervised rules, you can refer to [cuSNN](https://github.com/tudelft/cuSNN) library. They have done a lot in performance optimization! Maybe we will also refer to their implementation later @Grasshlw .

**Comment by 932179209** [comment]
Glad to hear that and thanks for the recommendation!
Hope to see more complete and powerful spikingjelly as soon as possible :)

**Comment by fangwei123456** [comment]
Hi, STDP is provided now:

https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/stdp.html

**Comment by 932179209** [comment]
Glad to hear that!  Thanks for the time to build the STDP rule in Spikingjelly!
