### ISSUE TITLE
Why CIFAR10DVS dataset has no attribute ‘train’? and how can i split the train dataset and test dataset

### ISSUE THREAD

**Issue by zhanggj821** [fangwei123456/spikingjelly#165]

**Comment by fangwei123456** [comment]
Because CIFAR10-DVS does not support a split of train/test set. You can use [spikingjelly.datasets.split_to_train_test_set](https://spikingjelly.readthedocs.io/zh_CN/latest/spikingjelly.datasets.html#spikingjelly.datasets.split_to_train_test_set) to get train and test set.
