### ISSUE TITLE
common.multiprocessing_env

### ISSUE THREAD

**Issue by CHonChou** [fangwei123456/spikingjelly#17]
from common.multiprocessing_env import SubprocVecEnv
ModuleNotFoundError: No module named 'common.multiprocessing_env'

**Comment by fangwei123456** [comment]
@lucifer2859 
![image](https://user-images.githubusercontent.com/38352109/97653599-1f765080-1a9c-11eb-93dc-bf8a93797af3.png)

**Comment by CHonChou** [comment]
How should I install this module

**Comment by lucifer2859** [comment]
https://github.com/openai/baselines/tree/master/baselines/common/vec_env

> How should I install this module

**Comment by lucifer2859** [comment]
> How should I install this module

And you can see [](https://github.com/lucifer2859/Policy-Gradients/tree/master/common) for more details.

**Comment by lucifer2859** [comment]
> How should I install this module

And you can see https://github.com/lucifer2859/Policy-Gradients/tree/master/common for more details.

**Comment by Yanqi-Chen** [comment]
Maybe code with additional dependency should be explicitly showed on the head? 🤔 
https://github.com/fangwei123456/spikingjelly/blob/6dc0a6acdfb2ea6ea88bbbdf7cb21fcf2d46afb2/spikingjelly/clock_driven/examples/Spiking_A2C.py#L1-L15

**Comment by lucifer2859** [comment]
> Maybe code with additional dependency should be explicitly showed on the head? 🤔
> https://github.com/fangwei123456/spikingjelly/blob/6dc0a6acdfb2ea6ea88bbbdf7cb21fcf2d46afb2/spikingjelly/clock_driven/examples/Spiking_A2C.py#L1-L15

The common package is added into the new repo, and it can be find at  https://github.com/fangwei123456/spikingjelly/tree/master/spikingjelly/clock_driven/examples/common
