### ISSUE TITLE
some questions (ann to snn)

### ISSUE THREAD

**Issue by rolling1z1** [fangwei123456/spikingjelly#170]
请问目前ann to snn mnist是否支持concat和upsampling：我修改成自己的snn model去跑mnist转换成snn时，有concat和upsampling操作时不能成功转换。
请问后续会出检测的ann to snn吗？
期待您的回信

**Comment by fangwei123456** [comment]
计算上都是支持的，原理则需要自行考虑是否合理：对每个时刻的脉冲做的操作F，是否等价于对脉冲相加后再做操作F。例如最大池化是不满足的
