### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by slucas03** [fangwei123456/spikingjelly#173]
I have problems when I try to download this package to an environment in Anaconda. Firstly, I have downloaded PyTorch package because I have read that it is a requirement for SpikingJelly. Then, I use the command `pip install spikingjelly` , but the following error appears:

> Collecting spikingjelly
>   Using cached spikingjelly-0.0.0.0.8-py3-none-any.whl (213 kB)
> Requirement already satisfied: torchvision in c:\users\slucas004\anaconda3\envs\stereospike\lib\site-packages (from spikingjelly) (0.11.3)
> Collecting onnx==1.8.0
>   Using cached onnx-1.8.0.tar.gz (5.2 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
>       Traceback (most recent call last):
>         File "C:\Users\slucas004\Anaconda3\envs\StereoSpike\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
>           main()
>         File "C:\Users\slucas004\Anaconda3\envs\StereoSpike\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "C:\Users\slucas004\Anaconda3\envs\StereoSpike\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\slucas004\AppData\Local\Temp\pip-build-env-_8xblve7\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in get_requires_for_build_wheel
>           return self._get_build_requires(
>         File "C:\Users\slucas004\AppData\Local\Temp\pip-build-env-_8xblve7\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\slucas004\AppData\Local\Temp\pip-build-env-_8xblve7\overlay\Lib\site-packages\setuptools\build_meta.py", line 266, in run_setup
>           super(_BuildMetaLegacyBackend,
>         File "C:\Users\slucas004\AppData\Local\Temp\pip-build-env-_8xblve7\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in run_setup
>           exec(compile(code, __file__, 'exec'), locals())
>         File "setup.py", line 75, in <module>
>           assert CMAKE, 'Could not find "cmake" executable!'
>       AssertionError: Could not find "cmake" executable!
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

I do not know what the problems is. Do you have any idea to solve it?

**Comment by fangwei123456** [comment]
Hi, I suggest that you can download from GitHub and install from the source codes.
