### ISSUE TITLE
About tempotron_mnist.py

### ISSUE THREAD

**Issue by yjzhang97** [fangwei123456/spikingjelly#18]
在例子tempotron_mnist.py中，第127行是不是应该调用test_data_loader，而不是train_data_loader？

**Comment by fangwei123456** [comment]
感谢debug，现已修复。https://spikingjelly.readthedocs.io/zh_CN/latest/tutorial.event_driven.html教程中的测试集正确率图片也需要顺便修复一下。

**Comment by fangwei123456** [comment]
教程已经修复
