### ISSUE TITLE
你好，我想问一下，训练SNN模型，使用的什么类型的突触

### ISSUE THREAD

**Issue by Craw-B** [fangwei123456/spikingjelly#180]

**Comment by fangwei123456** [comment]
参考教程里面的代码，普通的Conv2d或者Linear就行

**Comment by Craw-B** [comment]
我的意思是基于什么样的学习规则，比如赫布，或者STDP

**Comment by fangwei123456** [comment]
SJ框架主要是用深度学习方法（梯度下降）。赫布或者STDP之类的目前支持还不够好，只有一个很原始的STDP：
https://spikingjelly.readthedocs.io/zh_CN/latest/spikingjelly.clock_driven.layer.html?highlight=STDP#spikingjelly.clock_driven.layer.STDPLearner

如果有兴趣参与开发，参考这个issue:
https://github.com/fangwei123456/spikingjelly/issues/76

**Comment by fangwei123456** [comment]
现在SJ框架完全支持STDP了：
https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based/stdp.html
