### ISSUE TITLE
Hidden layers of a SNN

### ISSUE THREAD

**Issue by slucas03** [fangwei123456/spikingjelly#184]
Hello again,

I am trying to understand very well how SpikingJelly works and which hyperparameters I can vary to perform my studies. I have queries about how to define the structure of the newtork. Most of the available examples work with images , such as the use of MNIST dataset [[https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/clock_driven/examples/lif_fc_mnist.py](url) ]. This kind of problems have particular characteristics because of the use of images as input data and I am interested in working with other type of input data in order to perform a regression task problem. Therefore, I would want to know how I should define the structure of the SNN so that the performance of the network with spikingjelly will be correct.

In the aforomentioned example problem the way to define the newtork is:
`net = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28*28, 10, bias=False), 
    neuron.LIFNode(tau=tau)
)`

I understand that `nn.Flatten()` is used because of images and `nn.Linear(28*28, 10, bias=False)` define the "network", but this line of code does not define the hidden layers that the network may have and I do not know wheter this is because the network does not have any hidden layer or spikingjelly do automatically. Thus, my question is whether spikingjelly automatically defines the hidden layers depending on the input data or you have to define more modules in `nn.Sequential` block. One example of the latter could be: 

`net = nn.Sequential(
    nn.Linear(28, 10, bias=False), 
    nn.Linear(10, 5, bias=False), 
    neuron.LIFNode(tau=tau)
)`

where the input layer has 28 neurons, the hidden layer has 10 neurons and the output layer 5.

Thank you in advance.

**Comment by fangwei123456** [comment]
> my question is whether spikingjelly automatically defines the hidden layers depending on the input data

No, the hidden layers should be defined manually.

One example of the latter could be:

> net = nn.Sequential( nn.Linear(28, 10, bias=False), nn.Linear(10, 5, bias=False), neuron.LIFNode(tau=tau) )
> 
> where the input layer has 28 neurons, the hidden layer has 10 neurons and the output layer 5.

Yes. But if you do not insert a spiking neurons layer between two linear layers, these two layers will be same with one layer because Y = W2 * W1 * X = (W1 * W2) * X.

**Comment by slucas03** [comment]
You mean this, do not you?

`net = nn.Sequential(
    nn.Linear(28, 10, bias=False),
    neuron.LIFNode(tau=tau)
    nn.Linear(10, 5, bias=False),
    neuron.LIFNode(tau=tau)
)`

So if I understand you correctly, you can define different type of neurons per layer (which can be another hyperparameter), can't you?

**Comment by fangwei123456** [comment]
> You mean this, do not you?

Yes.

> you can define different type of neurons per layer

Yes, for example:

> net = nn.Sequential(
>     nn.Linear(8, 4, bias=False),
>     neuron.IFNode(),
>     nn.Linear(4, 2, bias=False),
>     neuron.LIFNode()
> )

**Comment by slucas03** [comment]
Thank you very much for your comments and your help. Just only you to know but this algorithm is very interesting. Congratulations for your great job!! :)
