### ISSUE TITLE
cifar10_r11_enabling_spikebased_backpropagation.py

### ISSUE THREAD

**Issue by CHonChou** [fangwei123456/spikingjelly#20]
in the "cifar10_r11_enabling_spikebased_backpropagation.py",What is the purpose of the following code？
for m in net.modules():
	if isinstance(m, LIFNode) and m.fire:
		m.v_acc += (m.v_acc < 1e-3).float()
		m.new_grad = (m.v_acc_l > 1e-3).float() + math.log(1 - 1 / m.tau) * torch.div(m.v_acc_l, m.v_acc)

**Comment by Yanqi-Chen** [comment]
According to the paper (Section 2.2.1.2), for the hidden layers, the authors redefine the gradient.
> pseudo derivative of LIF neuronal activation with respect to total input current

It is used in the following lines:
https://github.com/fangwei123456/spikingjelly/blob/e5c39e2aba369133dee64994df4404907a7cdd4b/spikingjelly/clock_driven/examples/cifar10_r11_enabling_spikebased_backpropagation.py#L117-L120

I follow the implementation of the authors here:
https://github.com/chan8972/Enabling_Spikebased_Backpropagation/blob/46e18a7b0741d08f155435e2c62acac4bebe5b2f/src/cifar10_ResNet11.py#L172-L175

**Comment by CHonChou** [comment]
Thank you very much for your answer
