### ISSUE TITLE
Leaky Integrate and analog Fire LIAF module in spinikingjelly

### ISSUE THREAD

**Issue by ChidanandKumarKS** [fangwei123456/spikingjelly#203]
@fangwei123456 
Is there is any possibility to incorporate LIAF model in spikingjelly?

**Comment by fangwei123456** [comment]
It can be got by modifying LIFNode. I have added it:

https://github.com/fangwei123456/spikingjelly/blob/ccdfa663f4f88200306c79573a09cc504d2e5411/spikingjelly/clock_driven/neuron.py#L1315

**Comment by ChidanandKumarKS** [comment]
@fangwei123456 Thanks. Closing the issue
