### ISSUE TITLE
使用from spikingjelly.clock_driven import layer语句时，程序会卡住。

### ISSUE THREAD

**Issue by HFourier** [fangwei123456/spikingjelly#217]
您好！我在使用from spikingjelly.clock_driven import layer时，即使没有用到相关函数，程序也会卡住。
![image](https://user-images.githubusercontent.com/45991550/165895409-12ec8258-b880-4f93-a19a-7bbcb4a2a26a.png)
使用from spikingjelly.clock_driven import neuron

值得一提的是，当我使用Powershell窗口运行代码时候，虽然也会出现同样的问题，但是按住Ctrl+c后可以跳过导致程序卡住的异常语句，同时显示该语句`spikingjelly.clock_driven.spike_op:`
![image](https://user-images.githubusercontent.com/45991550/165895526-7a2ea604-e170-43a5-9308-7659eec56ba0.png)
我的python版本是3.8，torch是1.7.1，cuda是11.0，编译器使用的是Pycharm，SJ的版本是0.0.0.0.11。
一开始以为是cupy的问题，尝试过cupy-cuda110、cupy-cuda111以及卸载cupy均未解决该问题。

**Comment by fangwei123456** [comment]
从github安装最新版的源代码可以解决这个问题。这个水pytorch的c/cuda缓存造成都，最新版会提示删除这个目录

**Comment by HFourier** [comment]
谢谢您的建议。我刚刚又重新git了最新版本的SJ，并重启了Pycharm，但是这个问题仍然存在。请问怎么解决呢？

**Comment by fangwei123456** [comment]
新版在运行时会提示你删除缓存目录，按提示操作即可

**Comment by fangwei123456** [comment]
把logging的等级改为info，然后看一下输出

**Comment by HFourier** [comment]
输出了这条报错信息`15:20	Error running 'spike_op': Cannot start process, the working directory 'F:\Miniconda\envs\liuye\Lib\site-packages\spikingjelly-0.0.0.0.11-py3.8.egg!\spikingjelly\clock_driven' does not exist`

**Comment by fangwei123456** [comment]
卸载后 用python setup.py develop安装试试

**Comment by HFourier** [comment]
好的，我已经卸载并按照你的方法进行安装了，但是在安装过程中并没有提示我删除任何目录。
我在spike_op.py文件中试图输出刚才的log信息，但是报了新的错误：
`Traceback (most recent call last):
  File "F:/Miniconda/envs/liuye/Lib/site-packages/spikingjelly/spikingjelly/clock_driven/spike_op.py", line 6, in <module>
    from . import tensor_cache
ImportError: attempted relative import with no known parent package`但是我可以跳转到该py文件。

**Comment by Yanqi-Chen** [comment]
可以拉取最新的代码再试试
