### ISSUE TITLE
关于DVS128Gesture数据集划分问题

### ISSUE THREAD

**Issue by Gavin-Meskin-Chen** [fangwei123456/spikingjelly#222]
请问你们在论文中的DVS128Gesture测试数据是如何划分的？训练集、验证集、测试集的比例是多少？（是根据官方发布的那样，仅仅根据他们所确定的训练集与测试集划分的吗？）是否采用了K折交叉验证呀？最后模型的测试精度是如何得出的呀？

**Comment by fangwei123456** [comment]
DVS128Gesture按照官方的划分方式。在__init__函数中有 `train` 参数，控制是使用训练集还是测试集。
在早期的文章中（https://github.com/fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron 中的ACC B）我们划分了训练集、测试集、验证集，汇报验证集性能最高时的测试集性能。但其他文章都汇报的是最大测试集性能，后来我们也改用了这种方式。
没有使用K折交叉验证。

**Comment by Gavin-Meskin-Chen** [comment]
DVS的数据量普遍比较少，是否需要使用一些数据增强的方式来扩充数据(之前看过一些传统双流网络做传统视频动作检测的文章用过一些数据增强)？

DVS数据常见的两种处理思路：(一)帧复原再传入模型；(二)直接利用事件流信息进行编码，然后传入模型；在这种数据量相对小的情况下，SNN网络能达到一个相对较好的效果，过拟合现象相对较少，是否与其自身特殊的离散结构有关系？刚刚接触这个领域，不太了解。

**Comment by fangwei123456** [comment]
> DVS的数据量普遍比较少，是否需要使用一些数据增强的方式来扩充数据

实际上原始数据集巨大，脉冲数量可以多达百万。数据增强一般是为了减少过拟合。

> 直接利用事件流信息进行编码，然后传入模型

直接输入脉冲的SNN文章，发一下链接看看

**Comment by Gavin-Meskin-Chen** [comment]
基于事件的目标定位与识别模型研究(唐瑭)，DOI：10.27342/d.cnki.gscdu.2021.000379

- “本文的研究方向为事件流数据的目标识别问题，比起帧重构，更科学的解决方案是构造可以应用于事件流数据的视觉处理方法。研究思路一种是基于传统的视觉处理方法启发，将其改造为适用于事件流数据的变体，另一种是创建新的，适合事件流数据处理的新方案。“

- “提出了一种尺度融合的多脉冲事件流目标特征提取方法,并使用群体编码的tempotron分类算法,构造了事件驱动的脉冲神经网络目标识别模型。“

不太清楚是不是我所理解的那样。

**Comment by fangwei123456** [comment]
看不出来这个文章的输入究竟是什么形式的

**Comment by Gavin-Meskin-Chen** [comment]
那就目前该领域比较常见的输入形式都是什么类型的呀？都是将事件数据重构成传统的帧数据吗？个人感觉在重构的时候，会减少事件形式数据的一些特有的优势吧？

**Comment by fangwei123456** [comment]
> 都是将事件数据重构成传统的帧数据吗？

是的。

> 个人感觉在重构的时候，会减少事件形式数据的一些特有的优势吧？

是的，重构的帧没有原始脉冲那么稀疏。

**Comment by Gavin-Meskin-Chen** [comment]
还有一个问题：好多脉冲编码方法是不是还都停留在理论研究上面，有没有相关文章具体在做DVS数据使用下面这些编码策略的呀？

1. 基于时间的编码：首脉冲时间编码、延迟相位编码等...
2. 基于频率的编码：频率编码、泊松编码等...

在SNN网络各种各样的编码方式中，感觉用得最多的就是泊松了，但是好像前提也是使用了帧重构的方案吧。

**Comment by fangwei123456** [comment]
多数编码方式都是对单个输入编码，因此很难用到DVS数据

**Comment by Gavin-Meskin-Chen** [comment]
十分感谢
