### ISSUE TITLE
关于SpikeLinear

### ISSUE THREAD

**Issue by 1y9y9l4** [fangwei123456/spikingjelly#226]
您好，我注意到0.0.0.0.12版本从layer中移除了SpikeLinear，能否咨询一下是什么原因呢

**Comment by fangwei123456** [comment]
没有去除，只是挪到了一个独立的py文件

https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/clock_driven/spike_op.py

原因参见 https://github.com/fangwei123456/spikingjelly/issues/217

**Comment by 1y9y9l4** [comment]
明白了，感谢
