### ISSUE TITLE
关于SNN网络中对神经元的训练？

### ISSUE THREAD

**Issue by KoiLiu** [fangwei123456/spikingjelly#233]
您好，请问在对SNN网络直接训练的过程中（例如教程中：使用卷积SNN识别Fashion-MNIST），除了对编码层参数的训练、调整，对于神经元参数的训练，我并不是十分理解，是否仅针对神经元的时间常数进行训练，还是对于阈值电压等参数也会进行训练、调整？谢谢。

**Comment by fangwei123456** [comment]
> 是否仅针对神经元的时间常数进行训练，还是对于阈值电压等参数也会进行训练、调整

这些参数一般是float类型，不会被训练。只有 `nn.Parameter` 类型才会被训练。

**Comment by Yanqi-Chen** [comment]
神经元的超参数，在一般的用法里均不会进行训练。

**Comment by KoiLiu** [comment]
很感谢你们的回复！谢谢！
