### ISSUE TITLE
lif_fc_mnist.py 编译错误

### ISSUE THREAD

**Issue by ketechn** [fangwei123456/spikingjelly#249]
您好：
       我将代码下载到本机后，使用pycharm + anaconda进行编译
       运行lif_fc_mnist.py出现下面的错误
C:\Program Files (x86)\Anaconda3\python.exe" C:/SNN/spikingjelly/spikingjelly/activation_based/examples/lif_fc_mnist.py -tau 2.0 -T 100 -device cpu -b 64 -epochs 100 -data-dir .\dataset\MNIST -amp -opt adam -lr 1e-3 -j 8
Traceback (most recent call last):
  File "C:/SNN/spikingjelly/spikingjelly/activation_based/examples/lif_fc_mnist.py", line 16, in <module>
    from spikingjelly.activation_based import neuron, encoding, functional, surrogate, layer
  File "C:\SNN\spikingjelly\spikingjelly\activation_based\neuron.py", line 5, in <module>
    from . import surrogate, base, lava_exchange
  File "C:\SNN\spikingjelly\spikingjelly\activation_based\surrogate.py", line 1763, in <module>
    def log_tailed_relu_backward(grad_output: torch.Tensor, x: torch.Tensor, alpha: float):
  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\torch\jit\__init__.py", line 1290, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::index_put_(Tensor(a!) self, Tensor?[] indices, Tensor values, bool accumulate=False) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'values' but instead found type 'float'.
  
  aten::index_put_(Tensor(a!) self, Tensor[] indices, Tensor values, bool accumulate=False) -> (Tensor(a!)):
  Expected a value of type 'List[Tensor]' for argument 'indices' but instead found type 'List[Optional[Tensor]]'.

The original call is:
  File "C:\SNN\spikingjelly\spikingjelly\activation_based\surrogate.py", line 1768
    grad_x = torch.ones_like(grad_output)
    grad_x[mask_gt1] = 1. / x[mask_gt1]
    grad_x[mask_le0] = alpha
    ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return grad_output * grad_x, None


Process finished with exit code 1

请问该如何解决？谢谢
使用python 3.7.4 torch版本1.5.1+cpu

**Comment by fangwei123456** [comment]
cpu运行是不能开启 `-amp`的。我在本机上试了一下，可以运行：

```
(sj-dev) wfang@mlg-ThinkStation-P920:~/spikingjelly_dev$ python ./spikingjelly/activation_based/examples/lif_fc_mnist.py -tau 2.0 -T 100 -device cpu -b 64 -epochs 100 -data-dir /datasets/MNIST -opt adam -lr 1e-3 -j 8
Namespace(T=100, device='cpu', b=64, epochs=100, j=8, data_dir='/datasets/MNIST', out_dir='./logs', resume=None, amp=False, opt='adam', momentum=0.9, lr=0.001, tau=2.0)
SNN(
  (layer): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1, step_mode=s)
    (1): Linear(in_features=784, out_features=10, bias=False)
    (2): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=False, step_mode=s, backend=torch, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
  )
)
Mkdir ./logs/T100_b64_adam_lr0.001.
```
