### ISSUE TITLE
stateful变量的判定问题

### ISSUE THREAD

**Issue by Yanqi-Chen** [fangwei123456/spikingjelly#25]
采用是否有reset属性来判别该层是否有状态并不合理
https://github.com/fangwei123456/spikingjelly/blob/c135ac80c0ec1e3f9474143e5d7c3d0719cd3f63/spikingjelly/clock_driven/functional.py#L32-L36
如果内部变量在网络运行过程中不变，只是在开始或结束时reset，那么运行过程中不存在数据依赖，仍然可以并行。

**Comment by fangwei123456** [comment]
准备给存在前序依赖的模块加一个属性，markov_property
