### ISSUE TITLE
关于LSTM中的c_t计算过程的疑问

### ISSUE THREAD

**Issue by SizhaoXu** [fangwei123456/spikingjelly#252]
在《Long Short-Term Memory Spiking Networks and Their Applications》中提到 t 时刻的 c_t 的计算可能产生 0, 1, 2三种值，而文中采取的做法是将 1, 2 都转变为 1 (为了符合脉冲的形式)，但是在惊蛰 rnn.py 的 SpikingLSTMCell 类中，并未对这一问题(可能出现 2 )进行处理。这样的话，是否与约定的脉冲网络的定义有所冲突呢？

最后，依旧感谢惊蛰团队提供这一便捷的SNN框架，期待后续STDP相关模块的引进~

**Comment by fangwei123456** [comment]
应该是当是没有注意原文的这句话，现在加上去了
