### ISSUE TITLE
Fashion MNIST NameError

### ISSUE THREAD

**Issue by Nesara13** [fangwei123456/spikingjelly#254]
I was working through this tutorial training SpikingJelly on the Fashion MNIST dataset:
[https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/conv_fashion_mnist.html#
](URL)

But when I try to run the train/test data loading code, it gives me this error:
```
NameError                                 Traceback (most recent call last)
Untitled-1.ipynb Cell 9 in <cell line: 3>()
      train_set = torchvision.datasets.FashionMNIST(
----> root=args.data_dir,
      train=True,
      transform=torchvision.transforms.ToTensor(),
      download=True)

NameError: name 'args' is not defined
```

Please let me know how I should fix this.
Thank you so much.

**Comment by fangwei123456** [comment]
Hi, the codes in this tutorial are **not complete**. To train the network, you can run the commands:

`python -m spikingjelly.activation_based.examples.conv_fashion_mnist -T 4 -device cuda:0 -b 128 -epochs 64 -data-dir /datasets/FashionMNIST/ -amp -cupy -opt sgd -lr 0.1 -j 8`

Codes are saved in
 
spikingjelly.activation_based.examples.conv_fashion_mnist

https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/examples/conv_fashion_mnist.py
