### ISSUE TITLE
datasets NCaltech101 bugs

### ISSUE THREAD

**Issue by QianpengLi577** [fangwei123456/spikingjelly#255]
After downloading data from the URL, the following bug is issued

```
NotImplementedError: This dataset can not be downloaded by SpikingJelly, please download [ReadMe(Caltech101)-SINAPSE-G.txt] from [https://www.garrickorchard.com/datasets/n-caltech101] manually and put files at ./ncaltech101/download.
```

However, the source data only has the following files, without `ReadMe(Caltech101)-SINAPSE-G.txt`

```
Caltech101_annotations.zip
Caltech101.zip  
MatlabFunctions  
ReadMe(Caltech101).txt
```

**Comment by fangwei123456** [comment]
You can find `ReadMe(Caltech101)-SINAPSE-G.txt` in the onedrive from https://www.garrickorchard.com/datasets/n-caltech101 .

**Comment by fangwei123456** [comment]
![image](https://user-images.githubusercontent.com/38352109/185908982-2be48605-8358-49a2-9313-e0e146862b97.png)
