### ISSUE TITLE
Query regarding calculation of energy metrics of SNN

### ISSUE THREAD

**Issue by sauravtii** [fangwei123456/spikingjelly#258]
Hello!
Is there a way to get the performance metrics like energy consumption, latency, etc of an SNN after simulating it ?

**Comment by fangwei123456** [comment]
You need to get SOP of each `spiking neurons layer->conv/fc`, which is `FLOP * fring rate * T`. 
To get flop, you can search `pytorch flop` in github and get some python packages.
To get firing rate, you can use the monitor: https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/monitor.html

**Comment by sauravtii** [comment]
Okay, by doing this I will be getting all the metrics for CPU or GPU, right ?
Or spikingjelly uses any other hardware for simulation under the hood ?

**Comment by fangwei123456** [comment]
> by doing this I will be getting all the metrics for CPU or GPU, right ?

Yes, it can be done in both CPU and GPU.

**Comment by sauravtii** [comment]
Okay, thank you!
Can you please help me with https://github.com/fangwei123456/spikingjelly/issues/259 ?

**Comment by fangwei123456** [comment]
I do not know much details about ANN2SNN in spikingjelly. [DingJianhao](https://github.com/DingJianhao) will help to solve that issue.
