### ISSUE TITLE
迭代NMIST数据集train_data_loader时出现错误

### ISSUE THREAD

**Issue by moxueyingyan** [fangwei123456/spikingjelly#260]
TypeError: Caught TypeError in DataLoader worker process 0.
TypeError: can't convert np.ndarray of type numpy.uint32. 
可能是label的数据类型出现问题？请问在哪里修改？

**Comment by fangwei123456** [comment]
提供最小的能够复现错误的代码

**Comment by moxueyingyan** [comment]
我在复现[Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron]工程里train文件时，迭代NMNIST时发生错误，源代码我没有动，如下：
    for epoch in range(net.epoch, max_epoch):

        start_time = time.time()

        log_data_list.append([])
        print(
            f'log_dir={log_dir}, max_test_accuracy={net.max_test_accuracy}, train_times={net.train_times}, epoch={epoch}')
        print(args)
        print(argv)

        net.train()

        for img, label in train_data_loader:
            img = img.to(device)
            label = label.to(device)
            optimizer.zero_grad()
            out_spikes_counter = net(img)
            out_spikes_counter_frequency = out_spikes_counter / net.T
在 for img, label in train_data_loader:这一行出现错误：
/home/wxy/anaconda3/envs/spikingjelly/bin/python3.8 /home/wxy/spikingjelly720-master/spikingjelly/activation_based/examples/train.py
Namespace(T=20, T_max=64, alpha_learnable=True, batch_size=16, channels=128, dataset_name='NMNIST', detach_reset=True, device='cuda:1', init_b=1.0, init_c=10.0, init_tau=2.0, learning_rate=0.001, log_dir_prefix='/home/wxy/plif_test/logsd', max_epoch=1024, normalization=None, number_layer=2, split_by='number', use_max_pool=True, use_plif=True)
/home/wxy/plif_test/logsd/NMNIST_use_plif_True_use_max_pool_True_T_20_c_128_n_2_split_by_number_normalization_None_detach_reset_True /home/wxy/plif_test/logsd/pt_NMNIST_use_plif_True_use_max_pool_True_T_20_c_128_n_2_split_by_number_normalization_None_detach_reset_True
NMNISTNet(
  (boost): AvgPool1d(kernel_size=(10,), stride=(10,), padding=(0,))
  (conv): Sequential(
    (0): Conv2d(2, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): PLIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=s, backend=torch, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): PLIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=s, backend=torch, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Dropout(p=0.5)
    (2): Linear(in_features=8192, out_features=2048, bias=False)
    (3): PLIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=s, backend=torch, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (4): Dropout(p=0.5)
    (5): Linear(in_features=2048, out_features=100, bias=False)
    (6): PLIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=s, backend=torch, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
  )
)
log_dir=/home/wxy/plif_test/logsd/NMNIST_use_plif_True_use_max_pool_True_T_20_c_128_n_2_split_by_number_normalization_None_detach_reset_True, max_test_accuracy=0, train_times=0, epoch=0
Namespace(T=20, T_max=64, alpha_learnable=True, batch_size=16, channels=128, dataset_name='NMNIST', detach_reset=True, device='cuda:1', init_b=1.0, init_c=10.0, init_tau=2.0, learning_rate=0.001, log_dir_prefix='/home/wxy/plif_test/logsd', max_epoch=1024, normalization=None, number_layer=2, split_by='number', use_max_pool=True, use_plif=True)
/home/wxy/spikingjelly720-master/spikingjelly/activation_based/examples/train.py
Traceback (most recent call last):
  File "/home/wxy/spikingjelly720-master/spikingjelly/activation_based/examples/train.py", line 783, in <module>
    for img, label in train_data_loader:
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/wxy/anaconda3/envs/spikingjelly/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 64, in <listcomp>
    return default_collate([torch.as_tensor(b) for b in batch])
TypeError: can't convert np.ndarray of type numpy.uint32. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.


Process finished with exit code 1

**Comment by fangwei123456** [comment]
如果是用原始代码，则应该安装其对应的老版本框架，不能和新版混用。

**Comment by fangwei123456** [comment]
如果用新版框架，可以参考新版框架的教程，里面有DVS数据集加载的教程。新版框架中也有网络的定义：

https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/model/parametric_lif_net.py

**Comment by moxueyingyan** [comment]
多谢指导，已修改好，非常感谢！
