### ISSUE TITLE
Same net and same input data, but different output

### ISSUE THREAD

**Issue by slucas03** [fangwei123456/spikingjelly#267]
Hi! I've trained a Spiking Neural Network (SNN) using SpikingJelly and I've saved it at the end of training phase, in order to use it during  test phase. In the test I want to check that the results are the same if I introduce the same input data to the net, thus in the script I use the net 3 times with the same input. Besides, I use the sentence `net.eval()` so the net's parameters shouldn't change during the performance.

Surprisingly, the outputs of the networks that I achieve are different in each attempt and I don't know why. I've already checked that the input data is the same in each attempt and that the parameters of the network don't change, so I've no idea what might be happening. They aren't big changes, but there is a little difference and I understand that if I use the same net and the same input data, the results should be the same.

I hope someone can help me. Thanks in advance.

**Comment by fangwei123456** [comment]
I guess that you forget to call ``functional.reset_net(net)`` after one forward?

**Comment by slucas03** [comment]
Oh my god!! Yes, it's that. I thought that sentence is only for training, my fault. Thank very much!!
