### ISSUE TITLE
Can ANN2SNN converted model deal with neuromorphic data?

### ISSUE THREAD

**Issue by GorkaAbad** [fangwei123456/spikingjelly#269]
Hi,
I was wondering if an ANN model, e.g., ResNet18, can be used with neuromorphic datasets, e.g., DVS Gesture, after conversion with ANN2SNN.

I tried this and I got this error:
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [128, 16, 2, 128, 128]

I assume that the model expects "regular" data instead of neuromorphic one. Can this be solved? or ANN2SNN is not supposed to deal with this.

Best,
Gorka

**Comment by fangwei123456** [comment]
Hi, the ANN (or SNN converted from it) expects input with shape `[N, *]`, while the data from neuromorphic datasets have shape `[N, T, *]` or `[T, N, *]`. Refer to https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/neuromorphic_datasets.html for more details.

To send data with shape `[T, N, *]` to your ANN/SNN, you should send `x[t]` at time-step `t`, which has shape `[N, *]`.

**Comment by GorkaAbad** [comment]
Hi, thanks for the fast reply.
So the data provided to the ANN will be treated as a regular image, right? We are just decomposing it in frames.

**Comment by fangwei123456** [comment]
> So the data provided to the ANN will be treated as a regular image, right?

Yes.

**Comment by GorkaAbad** [comment]
Thanks a lot!
