### ISSUE TITLE
Which neuromorphic hardware does spikingjelly simulate ?

### ISSUE THREAD

**Issue by sauravtii** [fangwei123456/spikingjelly#273]
Hi,

I have been recently using spikingjelly a lot as it's a great framework! But I am still not sure on which neuromorphic hardware does it simulate ?
For example,
I am running this [code](https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/ann2snn/examples/resnet18_cifar10.py) and [this](https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/ann2snn/examples/cnn_mnist.py), but not sure on which neuromorphic hardware the SNN models are getting simulated (for ex. Loihi, SpiNNaker, BrainScaleS, etc)

**Comment by fangwei123456** [comment]
Hi, by default modules in SpikingJelly are simulated in CPU or GPU.

Loihi will be supported in SpikingJelly. The tutorial will come soon.

Here are some primary codes:
https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/lava_exchange.py

**Comment by sauravtii** [comment]
Okay, is there a functionality to simulate the SNN on SpiNNaker and BrainScaleS also, or will it be available in future ?

**Comment by sauravtii** [comment]
Okay, thank you
