### ISSUE TITLE
从github上下载源码并安装成功，仍显示No matching distribution found for spikingjelly.clock_driven

### ISSUE THREAD

**Issue by chococheri** [fangwei123456/spikingjelly#277]
ubuntu机器上使用git clone下载受限，于是从github上下载源码以后执行了cd spikingjelly python setup.py install，显示以下打印信息
Using /home/qtt/anaconda3/envs/NASNet/lib/python3.9/site-packages 
Finished processing dependencies for spikingjelly==0.0.0.0.13
但是在执行from spikingjelly.clock_driven.functional import reset_net时，出现以下信息，请问是什么问题呢？
ERROR: Could not find a version that satisfies the requirement spikingjelly.clock_driven (from versions: none)
ERROR: No matching distribution found for spikingjelly.clock_driven

**Comment by fangwei123456** [comment]
`clock_driven`是<=12版本的，GitHub目前的源代码是13版本。装12版本可以从pip安装

**Comment by chococheri** [comment]
> `clock_driven`是<=12版本的，GitHub目前的源代码是13版本。装12版本可以从pip安装

谢谢！修改后没问题了。
