### ISSUE TITLE
Spike waveforms don't look like what I expected

### ISSUE THREAD

**Issue by SeanNobel** [fangwei123456/spikingjelly#283]
Hi, thanks for your work on this great repository.
I'm kind of new to SNNs and have a question to ask.

When I input constant values to an LIF neuron node, why do the spikes have a symmetric shape?

<img width="400" alt="lif_default" src="https://user-images.githubusercontent.com/75618251/196401917-265aeab6-ccb8-41d9-8edd-ad05b2be5148.png">

While I expected something like this shows up:

<img width="400" alt="スクリーンショット 2022-10-18 19 17 54" src="https://user-images.githubusercontent.com/75618251/196403819-0e0d7c9c-f7a3-43f5-b91f-e915736ff97f.png">

The simple code that I ran is as below.

```
import torch
from spikingjelly.activation_based import neuron, surrogate
import matplotlib.pyplot as plt


lif_neuron = neuron.LIFNode()

input = torch.Tensor([1.0])

output = torch.stack(
    [lif_neuron(input) for _ in range(100)]
)

fig = plt.figure(tight_layout=True)
plt.plot(output)
plt.title("LIF neuron default")
fig.savefig("tmp/lif_default.png")
```

I see the same symmetric shape when I use `neurons.IzhikevichNode`.

Thanks.

**Comment by fangwei123456** [comment]
The outputs of the spiking neuron are spikes, rather than voltage.
You can use the following codes to plot vlotage:


```python
import torch
from spikingjelly.activation_based import neuron, surrogate
import matplotlib.pyplot as plt


lif_neuron = neuron.LIFNode(tau=2.)

input = torch.Tensor([1.])
v = []

for _ in range(100):
    v.append(lif_neuron.v)
    lif_neuron(input)

fig = plt.figure(tight_layout=True)
plt.plot(v)
plt.title("LIF neuron default")
plt.show()
```

![image](https://user-images.githubusercontent.com/38352109/196406922-b7244dc0-94c5-4006-b91b-794fc9804ddd.png)

**Comment by fangwei123456** [comment]
```python
import torch
from spikingjelly.activation_based import neuron, surrogate
import matplotlib.pyplot as plt


lif_neuron = neuron.IzhikevichNode()

input = torch.Tensor([0.25])
v = []

for _ in range(100):
    v.append(lif_neuron.v)
    lif_neuron(input)

fig = plt.figure(tight_layout=True)
plt.plot(v)
plt.title("IzhikevichNode neuron default")
plt.show()
```

![image](https://user-images.githubusercontent.com/38352109/196407113-a9130834-8cad-440f-9964-33653a3625ae.png)

**Comment by SeanNobel** [comment]
Ooh I see, thank you very much!
