### ISSUE TITLE
applying transform to gesture recognition dataloader

### ISSUE THREAD

**Issue by negishubham** [fangwei123456/spikingjelly#287]
Hi, 

I wanted to know how to apply resize transform to the dataloader in spikingjelly for DVS 128 gesture dataset? 

Below is the syntax that I am using to apply the transform:
dvs128_gesture.DVS128Gesture(root=dataset_dir, train=True, data_type='frame', frames_number=T, split_by='number', transform=transforms.RandomCrop(64, padding=4))

But I am getting below error: 
TypeError: img should be PIL Image. Got <class 'numpy.ndarray'>

**Comment by fangwei123456** [comment]
Hi, you can try this:

```python
import numpy as np
from torchvision import transforms
import torch
class FromNP:
    def __call__(self, x: np.ndarray):
        return torch.from_numpy(x)


tf = transforms.Compose(
    [
        FromNP(),
        transforms.RandomCrop((64, 64), padding=4),
    ]
)

x = np.random.random([2, 128, 128])
print(tf(x).shape)
```

Do not use `transforms.ToTensor()` because it will regard `[2, 128, 128]` as an image with `channel=128`.

**Comment by negishubham** [comment]
Thanks it worked!
