### ISSUE TITLE
No module named 'spikingjelly.clock_driven.ann2snn.sample_models'

### ISSUE THREAD

**Issue by lagnx** [fangwei123456/spikingjelly#305]
@DingJianhao 

**Issue type**

- [ ] Bug Report

**SpikingJelly version**

`0.0.0.0.12`

**Description**

运行 `spikingjelly.clock_driven.ann2snn.examples.cnn_mnist.py` 时，第七行 `from spikingjelly.clock_driven.ann2snn.sample_models import mnist_cnn` 会报错， ann2snn 并没有 `sample_models` 。

我查看本地文件里面也没有 `sample_models` 模块，但是在 github 上的 0.0.0.0.12 分支中，确实有这个模块，我猜测可能是 pip 安装时的问题？是我个人的问题还是普遍性的问题，这一点有待确认。

**Comment by fangwei123456** [comment]
pip安装的是最新稳定版12，而GitHub是开发版13。可以考虑从github安装源代码

```
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
python setup.py install
```

**Comment by lagnx** [comment]
我明白你的意思，我安装的是 12 稳定版，但是 github可以查看12版本的分支上确实是有前面说的 `sample_models` 的，而pip安装下来的 12 稳定版中却没有这个 `sample_models` 的，这是存在差异的。

此外这个问题我个人已经解决，我只是想反映一下这样的问题，看看能否对你们完善代码有所帮助。

**Comment by fangwei123456** [comment]
看了一下估计pypi上传打包的时候出了问题，里面确实没有
![image](https://user-images.githubusercontent.com/38352109/201071048-19908615-4329-466a-9023-a7d842392004.png)

**Comment by fangwei123456** [comment]
由于pypi不允许对已经发布的版本修改，这个问题只能留到14版本修复了。
感谢你的debug！
