### ISSUE TITLE
module 'spikingjelly.clock_driven.functional' has no attribute 'set_monitor'

### ISSUE THREAD

**Issue by lagnx** [fangwei123456/spikingjelly#308]
**Issue type**

- [ ] Bug Report

**SpikingJelly version**

`0.0.0.0.12`

**Description**

在12版本的 `spikingjelly.clock_driven.examples.Spiking_DQN_state.py` 中第 222 行使用了 `functional.set_monitor` ，但是在 `spikingjelly.clock_driven.functional` 中没有该函数的实现

**Comment by lucifer2859** [comment]
> @lucifer2859 在最新的master版本中也有这个问题。 `functional.set_monitor(policy_net, True)`是用来做什么的？

在0.0.0.0.4中有实现： “将policy_net中的所有含有监视器的模块，监视器状态设置为True”，并在0.0.0.0.6之后移除；

**Comment by lucifer2859** [comment]
> @lucifer2859 在最新的master版本中也有这个问题。 `functional.set_monitor(policy_net, True)`是用来做什么的？

用在249行：IF_spikes = np.asarray(policy_net.fc[1].monitor['s'])

**Comment by lagnx** [comment]
ok，这个问题我暂时搁置，因为暂时没有急切地需求。
其他人如果有问题可以尝试上述诉说的新版监视器替换。

**Comment by fangwei123456** [comment]
@lucifer2859 有时间还是得修复一下这个bug

**Comment by lucifer2859** [comment]
> ok，这个问题我暂时搁置，因为暂时没有急切地需求。 其他人如果有问题可以尝试上述诉说的新版监视器替换。

问题已在0.0.0.0.12版本中解决，请查看最新的Spiking_DQN_state.py

**Comment by lucifer2859** [comment]
> @lucifer2859 有时间还是得修复一下这个bug

0.0.0.0.12中的bug已解决，后续会在最新版本对此问题进行解决

**Comment by lucifer2859** [comment]
最新版本已解决

**Comment by fangwei123456** [comment]
> > @lucifer2859 有时间还是得修复一下这个bug
> 
> 0.0.0.0.12中的bug已解决，后续会在最新版本对此问题进行解决

已经pypi发布的版本是不能做更改的了。我把那个修复覆盖一下
