### ISSUE TITLE
Deconvolutional (Spiking) layers

### ISSUE THREAD

**Issue by GorkaAbad** [fangwei123456/spikingjelly#309]
Hi,
I want to create a (Spiking) autoencoder. However, I checked, and there are no Deconvolutional layers in ```spikingjelly/activation_based/layer.py```. 
Can we create an autoencoder with LIF neurons from scratch? Is it preferred to use ANN2SNN? I assume the last won't work because it requires spiking deconv layers.

Do you have any suggestions?
Thanks in advance
Gorka

**Comment by fangwei123456** [comment]
Hi,I wll add the deconv layers.

> Is it preferred to use ANN2SNN? 

I think you can use it as long as your ANN use ReLU activation.

**Comment by fangwei123456** [comment]
We have added `ConvTranspose` layers:

https://github.com/fangwei123456/spikingjelly/blob/df2127b94e09890df850996e990cee5ff782f522/spikingjelly/activation_based/layer.py#L276

**Comment by GorkaAbad** [comment]
Thanks for the fast reply.
I tried it and works perfectly. 

Thanks again
