### ISSUE TITLE
关于平均脉冲发放率的统计

### ISSUE THREAD

**Issue by chenjiefighting** [fangwei123456/spikingjelly#319]
你好，根据以前的讨论得到公式avg_firing_rate = spikes/(neuron*T)，我看了代码部分，变成了avg_firing_rate = spikes/(neuron*T*batchsize)，我想问一下，平均脉冲发放率是针对单个样本进行统计，所以除以batchsize，是这样的吗？谢谢

**Comment by fangwei123456** [comment]
脉冲的shape是 `[T, N, *]`，直接求平均得到的是所有神经元的平均发放率，不除以T得到的是空间发放率，不除以N得到的是每个样本的所有神经元的平均发放率。要用哪个发放率，就用相应的方式计算。

**Comment by chenjiefighting** [comment]
好的，非常感谢
