### ISSUE TITLE
Questions about STDPLearner

### ISSUE THREAD

**Issue by youyou782** [fangwei123456/spikingjelly#326]
Hi, thanks for the library.

I'm wondering whether the STDPLearner can be applied to a Conv1d. I didn't see a stdp_single_step function for Conv1d in learning.py. I guess it can only be applied to linear layer and Conv2d layer now.

On top of that, I notice the change of stdp_trace.py on Nov.19

change:
def f_weight(x):
        return torch.clamp(x, -1, 1.)
to:
def f_pre(x, w_min, alpha=0.):
        return (x - w_min) ** alpha
def f_post(x, w_max, alpha=0.):
        return (w_max - x) ** alpha

What's this for?

**Comment by fangwei123456** [comment]
I think STDP for conv1d can be easily modified from conv2d.

> What's this for?
@lucifer2859

**Comment by fangwei123456** [comment]
Hi, I just add stdp1d. Here is an example:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import SGD, Adam
from spikingjelly.activation_based import learning, layer, neuron, functional

T = 8
N = 2
C = 3
L = 32
lr = 0.1
tau_pre = 2.
tau_post = 100.
step_mode = 'm'

def f_weight(x):
    return torch.clamp(x, -1., 1.)


net = nn.Sequential(
    layer.Conv1d(3, 16, kernel_size=3, stride=1, padding=1, bias=False),
    neuron.IFNode(),
    layer.MaxPool1d(2, 2),
    layer.Conv1d(16, 16, kernel_size=3, stride=1, padding=1, bias=False),
    neuron.IFNode(),
    layer.MaxPool1d(2, 2),
    layer.Flatten(),
    layer.Linear(16 * 8, 64, bias=False),
    neuron.IFNode(),
    layer.Linear(64, 10, bias=False),
    neuron.IFNode(),
)

functional.set_step_mode(net, step_mode)

instances_stdp = (layer.Conv2d, layer.Conv1d)

stdp_learners = []

for i in range(net.__len__()):
    if isinstance(net[i], instances_stdp):
        stdp_learners.append(
            learning.STDPLearner(step_mode=step_mode, synapse=net[i], sn=net[i+1], tau_pre=tau_pre, tau_post=tau_post,
                                f_pre=f_weight, f_post=f_weight)
        )


params_stdp = []
for m in net.modules():
    if isinstance(m, instances_stdp):
        for p in m.parameters():
            params_stdp.append(p)

params_stdp_set = set(params_stdp)
params_gradient_descent = []
for p in net.parameters():
    if p not in params_stdp_set:
        params_gradient_descent.append(p)

optimizer_gd = Adam(params_gradient_descent, lr=lr)
optimizer_stdp = SGD(params_stdp, lr=lr, momentum=0.)



x_seq = (torch.rand([T, N, C, L]) > 0.5).float()
target = torch.randint(low=0, high=10, size=[N])

optimizer_gd.zero_grad()
optimizer_stdp.zero_grad()

y = net(x_seq).mean(0)
loss = F.cross_entropy(y, target)
loss.backward()



optimizer_stdp.zero_grad()

for i in range(stdp_learners.__len__()):
    stdp_learners[i].step(on_grad=True)

optimizer_gd.step()
optimizer_stdp.step()
```

**Comment by fangwei123456** [comment]
@lucifer2859 
Hi, I just remove `w_max` and `w_min` in weight functions becuse the tutorials have not been updated. When we run codes in the tutorial, we will get an error about missing `w_max` and `w_min` in `__init__`.

I think we can wrap args inside the weight functions to avoid api/tutorial change. Here is an example:

```python
import torch
from typing import Callable

def gen_f(f: Callable, *args, **kwargs):
    def wrapped_f(weight: torch.Tensor):
        return f(weight, *args, **kwargs)

    return wrapped_f


f_clamp = gen_f(torch.clamp, -0.1, 0.1)

x = torch.rand([8]) - 0.5

print(x)
print(f_clamp(x))
```

The outputs are:
```
tensor([ 0.4800, -0.0776,  0.4091,  0.0440,  0.0065,  0.1121, -0.2439,  0.4566])
tensor([ 0.1000, -0.0776,  0.1000,  0.0440,  0.0065,  0.1000, -0.1000,  0.1000])
```

**Comment by lucifer2859** [comment]
You can refer to Section 2.2 of this paper（Spike-timing dependent synaptic plasticity: a phenomenological framework). The purpose of this change is to obtain a realistic description of synaptic plasticity we have to make sure that the synaptic efficacy
stays within certain bounds.

**Comment by lucifer2859** [comment]
> @lucifer2859 Hi, I just remove `w_max` and `w_min` in weight functions becuse the tutorials have not been updated. When we run codes in the tutorial, we will get an error about missing `w_max` and `w_min` in `__init__`.
> 
> I think we can wrap args inside the weight functions to avoid api/tutorial change. Here is an example:
> 
> ```python
> import torch
> from typing import Callable
> 
> def gen_f(f: Callable, *args, **kwargs):
>     def wrapped_f(weight: torch.Tensor):
>         return f(weight, *args, **kwargs)
> 
>     return wrapped_f
> 
> 
> f_clamp = gen_f(torch.clamp, -0.1, 0.1)
> 
> x = torch.rand([8]) - 0.5
> 
> print(x)
> print(f_clamp(x))
> ```
> 
> The outputs are:
> 
> ```
> tensor([ 0.4800, -0.0776,  0.4091,  0.0440,  0.0065,  0.1121, -0.2439,  0.4566])
> tensor([ 0.1000, -0.0776,  0.1000,  0.0440,  0.0065,  0.1000, -0.1000,  0.1000])
> ```

ok

**Comment by youyou782** [comment]
Thanks so much for both of your help. I will try this later.
So, the `w_max` and `w_min` will be added back after the tutotial has been upadate?

**Comment by fangwei123456** [comment]
> So, the w_max and w_min will be added back after the tutotial has been upadate?

No, we suggest that you can wrap `w_max` and `w_min` inside the weight function. Refer to this:

https://github.com/fangwei123456/spikingjelly/issues/326#issuecomment-1359316416
