### ISSUE TITLE
import lyngor和import lynpy时没找到相关文件，可以提供吗？

### ISSUE THREAD

**Issue by moxueyingyan** [fangwei123456/spikingjelly#332]
我在尝试“在灵汐芯片上推理”，

在spikingjelly/activation_based/examples/lynxi_fmnist_inference.py文件中引用lynxi_exchange.compile_lynxi_model属性时，发生错误：
AttributeError: module 'spikingjelly.activation_based.lynxi_exchange' has no attribute 'compile_lynxi_model'

在lynxi_exchange.py文件中import lyngor和import lynpy时提示错误，能否提供这两个文件？非常感谢作者的贡献！

**Comment by fangwei123456** [comment]
这个是商业闭源的库，需要联系灵汐公司，我们不能提供

**Comment by moxueyingyan** [comment]
好的，感谢您的快速回复！

**Comment by moxueyingyan** [comment]
还想问一下，灵汐KA200芯片支持这个样例的推理么？

**Comment by fangwei123456** [comment]
支持，这个例子里面用的就是KA200

**Comment by moxueyingyan** [comment]
哦，HP300搭载的3颗KA200芯片，那一颗KA200够用吗？

**Comment by fangwei123456** [comment]
fmnist那个网络规模很小，一个KA200足够了

**Comment by moxueyingyan** [comment]
好的好的，非常感谢！
