### ISSUE TITLE
你好，我想使用MultiDimensionalAttention，但是报错'MultiDimensionalAttention' object is not callable，请求指点

### ISSUE THREAD

**Issue by hongliang520** [fangwei123456/spikingjelly#363]
您好，我有一些问题请教您，请您有时间的时候回答一下，谢谢
我想使用layer.MultiDimensionalAttention这个模块，代码如下
       from spikingjelly.activation_based import layer
       ······
       self.Mul =  layer.MultiDimensionalAttention(2,64,1,1,3)
       ······
       h1 = self.Mul(h1)#h1的Size[2, 4, 64, 224, 224]

报错：'MultiDimensionalAttention' object is not callable
麻烦您指导我解决这个问题，谢谢

**Comment by fangwei123456** [comment]
这是个bug，已经修复了。从GitHub重新安装SJ框架试一下

**Comment by fangwei123456** [comment]
这是一个比较严重的bug，加到bug列表了：
https://github.com/fangwei123456/spikingjelly/blob/master/bugs.md

**Comment by hongliang520** [comment]
> 这是个bug，已经修复了。从GitHub重新安装SJ框架试一下

谢谢，已经解决问题了，非常感谢您的解答
