### ISSUE TITLE
咨询作者

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#37]
您好，我是一名学生，感觉您这个SNN的包真的是太棒了，有许多问题想跟您咨询（可以有偿），您能给我说一下您的联系方式吗？
我的邮箱是729684332@qq.com
十分期待您的来信。

**Comment by fangwei123456** [comment]
遇到使用中的问题，可以先看教程和文档，仍然有疑问再提issue即可

**Comment by huatianxue1994** [comment]
谢谢您！我正在仔细研究文档和代码



---原始邮件---
发件人: "fangwei123456"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 晚上10:25
收件人: "fangwei123456/spikingjelly"<spikingjelly@noreply.github.com&gt;;
抄送: "huatianxue1994"<729684332@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [fangwei123456/spikingjelly] 咨询作者 (#37)




 
遇到使用中的问题，可以先看教程和文档，仍然有疑问再提issue即可
