### ISSUE TITLE
Train_SEW_Resnet_for_CIFAR10DVS 

### ISSUE THREAD

**Issue by Malek-1** [fangwei123456/spikingjelly#375]
@ fangwei123456 

**Issue type**

- [ ] Bug Report
- [ ] Feature Request
- [x] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**

When i tried to run train.py for CIFAR10DVS to train SEW resnet i got this error! please help me : 
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataset.py", line 298, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/content/Spike-Element-Wise-ResNet/cifar10dvs/train.py", line 57, in __getitem__
    sample = torch.load(file_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:130] . file in archive is not in a subdirectory: frames.npy

**Minimal code to reproduce the error/bug**
CIFAR10DVS(root='/content/',  data_type='frame', frames_number= 16, split_by='number')
train_set, test_set = split_to_train_test_set(0.9, '/content/frames_number_16_split_by_number', 10, random_split= False)

    train_data_loader = DataLoader(
        dataset=train_set,
        batch_size=args.b,
        shuffle=True,
        num_workers=args.j,
        drop_last=True)

    test_data_loader = DataLoader(
        dataset=test_set,
        batch_size=args.b,
        shuffle=False,
        num_workers=args.j,
        drop_last=False)  i have changed the split_to_train_test_set like this : 
class CustomDataset(Dataset):
    def __init__(self, dataset_path, loader):
        self.loader = loader
        self.samples = self._load_samples(dataset_path)

    def _load_samples(self, dataset_path):
        samples = []
        classes = os.listdir(dataset_path)
        classes.sort()

        for class_idx, class_name in enumerate(classes):
            class_dir = os.path.join(dataset_path, class_name)
            if not os.path.isdir(class_dir):
                continue
            file_names = os.listdir(class_dir)
            for file_name in file_names:
                if file_name.endswith('.npz'):
                    file_path = os.path.join(class_dir, file_name)
                    samples.append((file_path, class_idx))

        return samples

    def __getitem__(self, index):
        file_path, target = self.samples[index]
        sample = torch.load(file_path)
        return sample, target

    def __len__(self):
        return len(self.samples)

def split_to_train_test_set(train_ratio: float, dataset_path: str, num_classes: int, random_split: bool = False):
    '''
    :param train_ratio: split the ratio of the origin dataset as the train set
    :type train_ratio: float
    :param origin_dataset: the origin dataset
    :type origin_dataset: torch.utils.data.Dataset
    :param num_classes: total classes number, e.g., ``10`` for the MNIST dataset
    :type num_classes: int
    :param random_split: If ``False``, the front ratio of samples in each classes will
            be included in train set, while the reset will be included in test set.
            If ``True``, this function will split samples in each classes randomly. The randomness is controlled by
            ``numpy.randon.seed``
    :type random_split: int
    :return: a tuple ``(train_set, test_set)``
    :rtype: tuple
    '''
   
    origin_dataset = CustomDataset(dataset_path, loader=torch.load) 
    label_idx = []
    for _ in range(num_classes):
        label_idx.append([])

    for i, (_, label) in enumerate(origin_dataset.samples):
        #y = item[1]
        #if isinstance(y, np.ndarray) or isinstance(y, torch.Tensor):
            #y = y.item()
        if label < num_classes:
            label_idx[label].append(i)

    train_idx = []
    test_idx = []

    if random_split:
        for i in range(num_classes):
            np.random.shuffle(label_idx[i])

    for i in range(num_classes):
        pos = math.ceil(len(label_idx[i]) * train_ratio)
        train_idx.extend(label_idx[i][0: pos])
        test_idx.extend(label_idx[i][pos:])

    return torch.utils.data.Subset(origin_dataset, train_idx), torch.utils.data.Subset(origin_dataset, test_idx) 
i added a custom_dataset class, can you help me to fix this issue please! Thanks.

```python
import spikingjelly
# ...
```

**Comment by fangwei123456** [comment]
Solved?

**Comment by Malek-1** [comment]
Yes thank you!

________________________________
De : fangwei123456 ***@***.***>
Envoyé : mercredi 10 mai 2023 02:33
À : fangwei123456/spikingjelly ***@***.***>
Cc : Malek ABBES ***@***.***>; State change ***@***.***>
Objet : Re: [fangwei123456/spikingjelly] Train_SEW_Resnet_for_CIFAR10DVS (Issue #375)


Solved?

**Comment by fangwei123456** [comment]
You can try this:

https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/datasets/__init__.py#L137

**Comment by Malek-1** [comment]
[heart]         Malek ABBES reacted to your message:
________________________________

**Comment by Malek-1** [comment]
Hi,

I tried to adapt spikingjelly.datasets.n_mnist  for ncars dataset but i got this error ;


The directory [/content/frames_number_16_split_by_number] already exists.


---------------------------------------------------------------------------


FileNotFoundError                         Traceback (most recent call last)


<ipython-input-39-b87d0038608a><https://localhost:8080/#> in <cell line: 1>()
----> 1 dataset = NCARS(root='/content/', train = True, data_type='frame', frames_number=16, split_by='number')



________________________________
4 frames
________________________________

/usr/local/lib/python3.10/dist-packages/torchvision/datasets/folder.py<https://localhost:8080/#> in make_dataset(directory, class_to_idx, extensions, is_valid_file)
    100         if extensions is not None:
    101             msg += f"Supported extensions are: {extensions if isinstance(extensions, str) else ', '.join(extensions)}"
--> 102         raise FileNotFoundError(msg)
    103
    104     return instances



FileNotFoundError: Found no valid file for the classes background, cars. Supported extensions are: .npz


i change the version of spikingjelly to 0.0.0.0.12 but the error not solved can you help me to fix it please!


________________________________
De : fangwei123456 ***@***.***>
Envoyé : mercredi 10 mai 2023 11:57
À : fangwei123456/spikingjelly ***@***.***>
Cc : Malek ABBES ***@***.***>; State change ***@***.***>
Objet : Re: [fangwei123456/spikingjelly] Train_SEW_Resnet_for_CIFAR10DVS (Issue #375)


You can try this:

https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/datasets/__init__.py#L137

**Comment by fangwei123456** [comment]
`The directory [/content/frames_number_16_split_by_number] already exists.` You can try to delete all dirs except the `download` dir. Then the codes will regenerate events and frames.

By the way, to add a new dataset, please read all codes in 

https://github.com/fangwei123456/spikingjelly/blob/bdc8cc9dd137d98fc210c2be5efade008f0dfd87/spikingjelly/datasets/__init__.py#L571

to learn its workflow and complete all `abstractmethod`.

**Comment by Malek-1** [comment]
Hi,

I have a question how can i generate frames.npy and include it to my ncars dataset because when i integrate the events to frames
and i load the dataset using torch.load i got this error :
RuntimeError: [enforce fail at inline_container.cc:130] . file in archive is not in a subdirectory: frames.npy.

Thank you for your help!

________________________________
De : fangwei123456 ***@***.***>
Envoyé : jeudi 11 mai 2023 10:55
À : fangwei123456/spikingjelly ***@***.***>
Cc : Malek ABBES ***@***.***>; State change ***@***.***>
Objet : Re: [fangwei123456/spikingjelly] Train_SEW_Resnet_for_CIFAR10DVS (Issue #375)


The directory [/content/frames_number_16_split_by_number] already exists. You can try to delete all dirs except the download dir. Then the codes will regenerate events and frames.

By the way, to add a new dataset, please read all codes in

https://github.com/fangwei123456/spikingjelly/blob/bdc8cc9dd137d98fc210c2be5efade008f0dfd87/spikingjelly/datasets/__init__.py#L571

to learn its workflow and complete all abstractmethod.

**Comment by fangwei123456** [comment]
`npy` files are created from events by spikingjelly. For example:

https://github.com/fangwei123456/spikingjelly/blob/bdc8cc9dd137d98fc210c2be5efade008f0dfd87/spikingjelly/datasets/__init__.py#L808
