### ISSUE TITLE
DQN之CartPole模型缺失问题

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#38]
大佬你好，我想咨询一个问题。
我在运行Spiking_DQN_state.py程序时，会报错，显示“不存在policy_net_256_max.pt”。
这个policy_net_256_max.pt的模型要怎么得到呢？或者说，需要自己训练一个？

**Comment by fangwei123456** [comment]
play函数是画图的。请先运行train函数

**Comment by fangwei123456** [comment]
train函数运行过程中会保存模型，得到模型后就可以用play函数画出游戏过程中的界面

**Comment by huatianxue1994** [comment]
十分感谢！不过我在文档中没有发现train.py这个文件。
在dqn_cart_pole.py中有一个定义的train函数，请问是这个吗？

**Comment by fangwei123456** [comment]
是的，可以参考此教程：[强化学习DQN](https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/6_dqn_cart_pole.html)
我们的绝大多数样例都是教程的一部分

**Comment by huatianxue1994** [comment]
太感谢了！这个教程我也在拜读。

**Comment by huatianxue1994** [comment]
已经成功运行了，谢谢您！
