### ISSUE TITLE
monitor占显存严重

### ISSUE THREAD

**Issue by Midun-xkAn** [fangwei123456/spikingjelly#385]
![image](https://github.com/fangwei123456/spikingjelly/assets/77448394/afe1ce5b-5800-402f-906b-5fc8bc1396fb)

如图所示，每个epoch都会存储2个LIF神经元尺寸为[5000,50,20]的脉冲发放，而且在cuda上。这会显著占用显存，限制网络规模和batch规模。即便放在cpu也是很大一块空间。有没有更好的数据存储（压缩）方式，可以占用更小的内存？

**Comment by fangwei123456** [comment]
如果是纯01的tensor，可以从float32压缩成bool，每个bool保存8个spike。存储可以降低为原来的1/32。
你需要对比一下使用和不使用监视器时显存的差异，如果差异不大，用这个方式也不会有太多改善

https://github.com/fangwei123456/spikingjelly/blob/21ce1bca68a2010df5ae602f5435e31a2dbda9d4/spikingjelly/activation_based/tensor_cache.py#L91

https://github.com/fangwei123456/spikingjelly/blob/21ce1bca68a2010df5ae602f5435e31a2dbda9d4/spikingjelly/activation_based/tensor_cache.py#L130

https://github.com/fangwei123456/spikingjelly/blob/21ce1bca68a2010df5ae602f5435e31a2dbda9d4/spikingjelly/activation_based/tensor_cache.py#L168

**Comment by Midun-xkAn** [comment]
我对比了使用监视器和不使用的情况，显存相差很大（数个G），我确定监视器记录每代的脉冲发放情况占据了大量存储。

我将bool_spike_to_float(x)作为参数function_on_output传给monitor.OutputMonitor，这么做会导致报错（好像跟cupy有关）。
`spike_seq_monitor = monitor.OutputMonitor(net, neuron.LIFNode, function_on_output=lambda x: float_spike_to_bool(x))`

我使用了一个简单的办法`spike_seq_monitor = monitor.OutputMonitor(net, neuron.LIFNode, function_on_output=lambda x: x.bool())`。经过测试，可以将存储降低为原来的1/4，如下图所示。
![image](https://github.com/fangwei123456/spikingjelly/assets/77448394/29e21c48-59be-44da-9e60-4a353fdfe631)

False和True分别表示0和1，我不理解每个bool保存8个spike是怎么做到的，那样存储可以降低为原来的1/32。

**Comment by fangwei123456** [comment]
这个是因为实际上bool类似仍然是int8

**Comment by fangwei123456** [comment]
2楼的那个bool是把8个spike存入一个int8，所以实现了1/32

**Comment by Midun-xkAn** [comment]
以后再找吧，先做要紧的任务

**Comment by fangwei123456** [comment]
> 我正在找办法把8个spike存入一个int8

参考2楼代码里面cupy版本的实现

**Comment by fangwei123456** [comment]
明天我把监视器里面加一下这个功能

**Comment by Midun-xkAn** [comment]
我真是太爱您了^_^

**Comment by fangwei123456** [comment]
现在加了个压缩的函数和教程
https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based/monitor.html#id5

**Comment by Midun-xkAn** [comment]
我今天也检测了一下，功能很好，再次感谢！！！
