### ISSUE TITLE
关于测试集精度的问题

### ISSUE THREAD

**Issue by li17855320680** [fangwei123456/spikingjelly#387]
作者你好，我使用了Spikingjelly Version : 0.0.0.0.14，直接将spikingjelly-master/spikingjelly/activation_based/model下的train_classify.py文件中的数据集加载框架本身就写好的cifar-10数据集，并且将spiking_resnet文件中的num_classes改成了10，最后运行train_imagenet_example.py文件，运行出来的测试集精度test_acc1都只有十几，这是什么问题，希望作者能够帮忙解答？万分感谢！

**Comment by fangwei123456** [comment]
网络结构不好、超参数不好等都是有可能的，需要慢慢调试

**Comment by li17855320680** [comment]
训练集train_acc1可以达到70多，测试集test_acc1只有10多，这不是过拟合嘛？但cifar-10数据集也不大呀。请问原框架中的train_classify.py和train_imagenet_example.py是不是最好还是训练imagenet数据集会好点？

**Comment by fangwei123456** [comment]
测试集10是瞎猜，不是过拟合了，这种情况大概率代码写错了

**Comment by li17855320680** [comment]
好的，谢谢，那我框架源码不动，还是去训练imagenet数据集，应该不会存在这样的情况吧？

**Comment by fangwei123456** [comment]
建议你先把bug找出来，不然这个bug会影响你后续在其他数据集的训练

**Comment by li17855320680** [comment]
好的好的，万分感谢
