### ISSUE TITLE
DVS CIFA准确率问题

### ISSUE THREAD

**Issue by Taotaonoangry** [fangwei123456/spikingjelly#390]
请问为什么模型在之前的DVS数据集中表现正常，NMNIST99%，DVSGESTURE 94%，但在DVS CIFA中准确率莫名的高，训练集71%时，测试集准确率就已经达到了83%，而且别的DVS在使用spikingjelly进行微分时会创建train和test这两个文件夹，但是DVS CIFA中似乎并没有这两个文件夹，并且from spikingjelly.datasets.cifar10_dvs import CIFAR10DVS中CIFAR10DVS好像也没有train这个关键字参数。
分类方法是参考https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based/neuromorphic_datasets.html
将DVS128Gesture改为了CIFAR10DVS

**Comment by Taotaonoangry** [comment]
非常感谢，划分完数据集后表现正常了

**Comment by li17855320680** [comment]
> 非常感谢，划分完数据集后表现正常了

您好，这个CIFAR10DVS是怎么划分的能分享下吗，我这边划的依然有问题，谢谢了

**Comment by fangwei123456** [comment]
> > 非常感谢，划分完数据集后表现正常了
> 
> 您好，这个CIFAR10DVS是怎么划分的能分享下吗，我这边划的依然有问题，谢谢了

可以参考一下这个代码：

https://github.com/fangwei123456/Spike-Element-Wise-ResNet/blob/cfc547c5e8196b1a16ebc596509b4dffea7c306f/cifar10dvs/train.py#L133
