### ISSUE TITLE
关于脉冲网络的训练

### ISSUE THREAD

**Issue by densechen** [fangwei123456/spikingjelly#40]
你好，感谢你们开源的工作！
在你们的文档中提到了一个脉冲神经网络的训练示例，是基于泊松编码，在MNIST数据集上的分类问题。
该网络模拟了100个时间不长，在显卡上耗时72分钟完成了训练。
关于这个，有一些问题我想请教一下：
1. 模拟100个时间步长有必要吗？在我的实验中，发现，其实模拟1个时间步长，和100个时间步长带来的效果其实是差不多的。所以，我这里挺疑惑的：在直接训练的方法中，增加脉冲步长，究竟是从哪一方面提升了网络的效果呢？因为我们知道基于转换的模型中，增加脉冲步长是为了更好的统计出脉冲发放的个数，从而计算出更准确的频率。但是在直接训练的问题中，好像并没有一个很合理的解释。
2. 另外，我们知道，增加了时间步长的同时，在计算梯度的时候，也成T倍的累计了梯度，因此，如果真的增加时间步长可能使得网络收敛更快，那是不是单纯由于这个T倍的梯度累计导致的呢？也就是说，步长为1的网络，是否经过T倍的训练量以后，其实性能会差不多呢？
3. 脉冲网络之所以看起来效果不错会不会很大原因是因为MNIST数据集本身就仅仅只包含0/1？

**Comment by fangwei123456** [comment]
个人看法:
1.MNIST的样例中，使用的是泊松编码器。由于图像像素值的范围是0-255，所以至少要仿真255步才能生成255个不同频率的输入脉冲序列。[编码器教程](https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/2_encoding.html)中有一副图片展示了泊松编码器输出的累计脉冲，非常直观：
![image](https://user-images.githubusercontent.com/38352109/103510616-8bac7080-4ea0-11eb-9dd5-d4450c90453c.png)
理论上仿真时间太短的话，很多取值相近的像素会无法区分。实际上对于MNIST这样的简单数据集，T可以取很小，因为即便输入图片被二值化也很容易辨认。之后的[FashionMNIST识别教程](https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/4_conv_fashion_mnist.html)中，直接将图片输入且取了很小的T=8。实际上即便T=1也能有80以上的正确率。
2.增加时间步长可以增加SNN的表达能力。T=1的网络表达能力会明显弱于T=2的网络，类似于半精度的ANN拟合能力要低于全精度网络。
3.MNIST确实比较简单，但直接训练的SNN的拟合能力很强。例如最新的[Going Deeper With Directly-Trained Larger Spiking Neural Networks](https://arxiv.org/abs/2011.05280)，直接训练的SNN在ImageNet上也能达到接近ANN的性能了。

**Comment by densechen** [comment]
感谢您的及时回复！
关于3，SNN肯定是可以训练的起来的。因为相比于二值网络，SNN对数据的处理显然是要宽松许多的。既然二值网络可以达到，那SNN肯定也是没有问题的。
而且SNN网络和量化网络的研究内容，如果抛开时间维度的信息的话，重合度非常的高。
所以一直很疑惑，这里的步长信息，究竟是起到的什么样的决定性作用呢？
因为没有任何步长信息的量化网络，也可以取得很好的结果🤔🤔🤔
另外，关于仿真步长的话，在基于模型转换的方法里面，我们都很明确的知道，只有足够长的仿真步长，才能够更好的表示频率的信息。但是在直接训练的模型里面，仿真步长的作用难到依然是起到一个无偏估计的作用吗？🤔🤔🤔🤔

**Comment by fangwei123456** [comment]
不知，这个问题还没有人专门研究过。数学上倒是有一定意义，更大的T相当于更小的dt，差分方程对微分方程的逼近误差会更小。但并非模型越“仿真”性能就越好

**Comment by densechen** [comment]
十分感谢！
