### ISSUE TITLE
请问“Incorporating Learnable Membrane Time Constant to Enhance Learning of Spiking Neural Networks”的程序

### ISSUE THREAD

**Issue by manwu1994** [fangwei123456/spikingjelly#41]
您好，拜读了关于您的文章“Incorporating Learnable Membrane Time Constant to Enhance Learning of
Spiking Neural Networks”，对动态的Membrane Time Constant参数这个比较有兴趣，请问在spikingjelly中有涉及吗？谢谢！

**Comment by fangwei123456** [comment]
LIF神经元的tau即为Membrane Time Constant。这篇文章的源码在reseatch gate上有，之后会用框架中的CUDA神经元重新实现一次

**Comment by fangwei123456** [comment]
加入相关代码后，我会通知你

**Comment by fangwei123456** [comment]
#42
