### ISSUE TITLE
使用visualizing.plot_one_neuron_v_s绘图时，电压未达到阈值就释放脉冲

### ISSUE THREAD

**Issue by Taotaonoangry** [fangwei123456/spikingjelly#415]
`if_layer = neuron.IFNode()

if_layer.reset()
x = torch.as_tensor([0.05])
T = 150
s_list = []
v_list = []
for t in range(T):
    s_list.append(if_layer(x))
    v_list.append(if_layer.v)

dpi = 300
figsize = (12, 8)
visualizing.plot_one_neuron_v_s(torch.cat(v_list).numpy(), torch.cat(s_list).numpy(), v_threshold=if_layer.v_threshold,
                                v_reset=if_layer.v_reset,
                                figsize=figsize, dpi=dpi)
plt.show()
`

![image](https://github.com/fangwei123456/spikingjelly/assets/126577004/96237141-a372-4d6c-9119-32d961ff607a)

结果显示电压未达到阈值就释放脉冲，请问这是为什么

**Comment by fangwei123456** [comment]
`v_list.append(if_layer.v)` 是放电后的电压，也就是`v[t]`，而你还需要记录`h[t]`才能显示出充电后、放电前的过阈值的电压
在教程中，把x设置的很小，T设置很大，使得看起来是一样的

下图是一个记录所有H和放电后的V的示例（LIF神经元）

![image](https://github.com/fangwei123456/spikingjelly/assets/38352109/661db580-2c8c-46a1-a402-ffa30ac9e9ad)

**Comment by Taotaonoangry** [comment]
@fangwei123456  感谢您的及时回复！
