### ISSUE TITLE
TEBN

### ISSUE THREAD

**Issue by yyq19990828** [fangwei123456/spikingjelly#418]
**Issue type**

- [ ] Bug Report
- [x] Feature Request
- [ ] Help wanted
- [ ] Other

**SpikingJelly version**

`开发版`

**Description**
请问TEBN可以集成入框架吗

**Comment by fangwei123456** [comment]
这个很容易实现，就加进去了

**Comment by yyq19990828** [comment]
这是来自QQ邮箱的自动回复邮件。已经成功收到你的邮件
