### ISSUE TITLE
请教GPU方面的问题

### ISSUE THREAD

**Issue by Met4physics** [fangwei123456/spikingjelly#422]
**Issue type**

- [ ] Bug Report
- [ ] Feature Request
- [x] Help wanted
- [ ] Other

**SpikingJelly version**

`latest`

**Description**
请问你们显存占用也是非常多吗，我实现了一个unet，T=4时占9g，T=8直接把3090撑爆了
...

**Comment by fangwei123456** [comment]
BPTT的显存占用和T几乎是正比的，所以占显存大很正常

**Comment by Met4physics** [comment]
好的感谢
