### ISSUE TITLE
The link for downloading the Nav gesture dataset is down

### ISSUE THREAD

**Issue by GorkaAbad** [fangwei123456/spikingjelly#423]
**Issue type**

- [x] Bug Report
- [ ] Feature Request
- [ ] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**

The link for downloading the Nav gesture dataset is down or has been moved to somewhere else. I cannot find where.
Link: https://www.neuromorphic-vision.com/public/downloads/navgesture/navgesture-walk.zip

**Minimal code to reproduce the error/bug**
```bash
wget https://www.neuromorphic-vision.com/public/downloads/navgesture/navgesture-walk.zip
```
The downloaded file is not the dataset but some html code.

**Comment by fangwei123456** [comment]
https://www.frontiersin.org/articles/10.3389/fnins.2020.00275/full#h5

![image](https://github.com/fangwei123456/spikingjelly/assets/38352109/f13cd13d-1356-4354-bd01-faa0902ba118)


It seems that they do not renew the domain.

**Comment by fangwei123456** [comment]
I have set this dataset as not downloadable.

**Comment by GorkaAbad** [comment]
Great thanks!
