### ISSUE TITLE
请教关于ann2snn

### ISSUE THREAD

**Issue by Met4physics** [fangwei123456/spikingjelly#424]
**Issue type**

- [ ] Bug Report
- [ ] Feature Request
- [x] Help wanted
- [ ] Other

**SpikingJelly version**

`latest`

**Description**

请问ann2snn中的Converter，为什么需要传入一个dataloader；还有转换后的snn是单步模式吗？

**Comment by fangwei123456** [comment]
我猜测是因为有一些ann2snn中的norm权重的操作需要过一遍数据集，例如为了约束relu的输出到[0, 1]以内，需要先过一遍数据集记录下relu的最大值，然后对权重进行缩放
转换后的snn应该是单步模式的

**Comment by Met4physics** [comment]
> 我猜测是因为有一些ann2snn中的norm权重的操作需要过一遍数据集，例如为了约束relu的输出到[0, 1]以内，需要先过一遍数据集记录下relu的最大值，然后对权重进行缩放 转换后的snn应该是单步模式的

非常感谢
