### ISSUE TITLE
关于脉冲编码器的问题：

### ISSUE THREAD

**Issue by kugatsu-sudo** [fangwei123456/spikingjelly#43]
在使用卷积SNN识别Fashion-Mnist一例中，使用教程中说到了这样一句话：“实际上我们完全可以直接将 图片送入SNN，在这种情况下，SNN中的首层脉冲神经元层及其之前的层，可以看作是一个参数可学习的自编码器。例如我们刚才定义的卷积层中的这些层”，请问这句话该如何理解？卷积层是怎么把像素值编码为脉冲序列的？这种方法引用自那篇文献？以及采用这种方式进行编码是否需要对输入归一化？非常期待你的回答，万分感谢！

**Comment by fangwei123456** [comment]
{卷积层-脉冲神经元}这样的一个整体，可以当作是可学习的脉冲编码器，因为它的输出是脉冲，权重被直接训练。输入是否归一化应该影响不大，因为权重是可训练的。
许多文章都已经这样用了，例如：

Direct Training for Spiking Neural Networks: Faster, Larger, Better

DIET-SNN: Direct Input Encoding With Leakage and Threshold Optimization in Deep Spiking Neural Networks

但尚未见到有那篇文章声称自己是首个“提出”此方法的

**Comment by kugatsu-sudo** [comment]
好的，谢谢你的回答，我去看一下相关文献

**Comment by fangwei123456** [comment]
#64

**Comment by fangwei123456** [comment]
可以参考 https://github.com/fangwei123456/spikingjelly/issues/64 ，更详细的讨论
