### ISSUE TITLE
ERROR: abc_map is error, error num is -2

### ISSUE THREAD

**Issue by ZengCZXY** [fangwei123456/spikingjelly#430]
你好，我在运行“在灵汐芯片上推理”的样例代码时会提示 abc_map is error, error num is -2，但后续没有继续运行到INFO: build abc map failed, try to build by auto mode，请问一下是什么原因呢？

**Comment by ZengCZXY** [comment]
> 教程中的代码输出也有这个错误，但不影像后面的运行：
> 
> ```
> builder.py[line:252]-ERROR: abc_map is error, error num is -2
> ```
> 
> 这个错误具体是什么，估计得问灵汐科技的工程师

感谢您的回复，我报错之后程序代码就停止了，并没有后续执行，这种情况会和版本有关系吗

**Comment by fangwei123456** [comment]
这个不了解，因为这些错误来源于lynxi的闭源库

**Comment by ZengCZXY** [comment]
> 这个不了解，因为这些错误来源于lynxi的闭源库

好的 谢谢您

**Comment by xander-2077** [comment]
您好，我复现您的代码时也遇到了相同的问题：
```
ValueError: abc_map is error, error num is -2
```
想请教一下您使用的python/pytorch/lyngor版本具体是什么

**Comment by ZengCZXY** [comment]
您好，之前这个问题一直没有解决，目前我们已经换成其他卡了，很抱歉不能帮你解决该问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fangwei123456/spikingjelly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月12日(星期五) 晚上6:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fangwei123456/spikingjelly] ERROR: abc_map is error, error num is -2 (Issue #430)





 
您好，我复现您的代码时也遇到了相同的问题：
 ValueError: abc_map is error, error num is -2  
想请教一下您使用的python/pytorch/lyngor版本具体是什么

**Comment by justlego** [comment]
这个问题应该是芯片不兼容原代码输出维度导致的，可以去看看patch目录下关于对源代码的改动补丁
