### ISSUE TITLE
使用卷积SNN识别Fashion-MNIST

### ISSUE THREAD

**Issue by kugatsu-sudo** [fangwei123456/spikingjelly#44]
请问“时间驱动：使用卷积SNN识别Fashion-MNIST”这一例子的代码是参考的哪一篇文献啊？代码的有些地方我还不是很理解，感觉更像是ANN而不像是SNN？对于直接使用第一个卷积层作为脉冲编码器，我也不是很理解？麻烦了。

**Comment by fangwei123456** [comment]
代码没有参考任何文献，随手写的，常用的卷积+全连接结构。
“SNN”并没有一个明确的定义，一般来说神经元用脉冲神经元的网络都能算SNN。

**Comment by kugatsu-sudo** [comment]
好的，谢谢回答，麻烦了

**Comment by fangwei123456** [comment]
顺便一提，在"Incorporating Learnable Membrane Time Constant to Enhance Learning of Spiking Neural Networks"这篇文章中，识别MNIST、Fashion-MNIST和N-MNIST的网络，用的是和这个教程非常类似的结构，除了全连接层用的是2层而不是三层
