### ISSUE TITLE
ModuleNotFoundError:No module named '_C_neuron' 

### ISSUE THREAD

**Issue by huzhoudaxia** [fangwei123456/spikingjelly#46]
when I do "from spikingjelly.clock_driven.monitor import Monitor",
meet the trouble "No module named '_C_neuron' ".

**Comment by Yanqi-Chen** [comment]
I guess you install SpikingJelly using pip? If so, you can install it from source again.
```
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
python setup.py install
```
Since the pypi's version has no compiled CUDA extensions like '_C_neuron'.

**Comment by huzhoudaxia** [comment]
You said right and thanks.

**Comment by mountains-high** [comment]
Hi there, I'm continuing the https://github.com/fangwei123456/Spike-Element-Wise-ResNet/issues/1

I'm sorry for re-opening this issue. I installed the Anaconda and created a new environment. This time there weren't any setup errors. 
```
1.  (sew) assel@assel-System-Product-Name:~/Desktop/SEW_2$ git clone https://github.com/fangwei123456/spikingjelly.git
Cloning into 'spikingjelly'...
remote: Enumerating objects: 9828, done.
remote: Counting objects: 100% (1093/1093), done.
remote: Compressing objects: 100% (411/411), done.
remote: Total 9828 (delta 891), reused 787 (delta 680), pack-reused 8735
Receiving objects: 100% (9828/9828), 35.44 MiB | 8.39 MiB/s, done.
Resolving deltas: 100% (6406/6406), done.
```
```
2.   (sew) assel@assel-System-Product-Name:~/Desktop/SEW_2$ cd spikingjelly/
3.   (sew) assel@assel-System-Product-Name:~/Desktop/SEW_2/spikingjelly$ git reset --hard 2958519df84ad77c316c6e6fbfac96fb2e5f59a3
```
HEAD is now at 2958519 add pub list
```
4.   (sew) assel@assel-System-Product-Name:~/Desktop/SEW_2/spikingjelly$ python setup.py install


CUDA_HOME is None. Install Without CUDA Extension
running install
running bdist_egg
running egg_info
creating spikingjelly.egg-info
writing spikingjelly.egg-info/PKG-INFO
writing dependency_links to spikingjelly.egg-info/dependency_links.txt
......

.....
Using /home/assel/anaconda3/envs/sew/lib/python3.9/site-packages/typing_extensions-4.1.1-py3.9.egg
Searching for six==1.16.0
Best match: six 1.16.0
Processing six-1.16.0-py3.9.egg
six 1.16.0 is already the active version in easy-install.pth

Using /home/assel/anaconda3/envs/sew/lib/python3.9/site-packages/six-1.16.0-py3.9.egg
Finished processing dependencies for spikingjelly==0.0.0.0.4
```
This time I was able to run setup.py without any errors. However, it still occurs:

```
(sew) assel@assel-System-Product-Name:~/Desktop/SEW_2/spikingjelly$ python3 test.py 
Traceback (most recent call last):
  File "/home/assel/Desktop/SEW_2/spikingjelly/test.py", line 40, in <module>
    import sew_resnet, spiking_resnet
  File "/home/assel/Desktop/SEW_2/spikingjelly/sew_resnet.py", line 4, in <module>
    from spikingjelly.cext import neuron as cext_neuron
  File "/home/assel/Desktop/SEW_2/spikingjelly/spikingjelly/cext/neuron.py", line 5, in <module>
    import _C_neuron
ModuleNotFoundError: No module named '_C_neuron'
```
I think this version is spikingjelly==0.0.0.0.4. Could you help please to solve this issue? Thank you!

P.S: My goal was to use pre-trained Imagenet weights which were saved via state_dict. That's the reason why I need to have model architecture.

**Comment by fangwei123456** [comment]
@mountains-high 
I find that you install without CUDA: `CUDA_HOME is None. Install Without CUDA Extension`. 
'_C_neuron' is a CUDA module.

If you do not have CUDA, you can try to use this code https://github.com/fangwei123456/Spike-Element-Wise-ResNet/tree/new_sj and replace the 'cupy' backend to the 'torch' backend:

https://github.com/fangwei123456/Spike-Element-Wise-ResNet/blob/74b48797bf6fc8e6bb71a867bce13385f280eba5/imagenet/sew_resnet.py#L9

**Comment by fangwei123456** [comment]
Another choice is using to this python neuron 
```
from spikingjelly.clock_driven import neuron, layer, surrogate

layer.MultiStepContainer(neuron.IFNode(detach_reset=True, surrogate_function=surrogate.ATan()))
```
to replace `cext_neuron.MultiStepIFNode`. The neuron has no parameter, and I think it will not influence the loading of weights.

**Comment by mountains-high** [comment]
Dr. Fang Wei, 
Thank you very much for all your help and support. 

1. The 1st option (changed 'cupy' into 'torch', but I have CUDA) didn't work. Because that gave 
```
  File "/home/assel/Desktop/SEW_2/spiking_resnet.py", line 13, in create_msif
    return neuron.MultiStepIFNode(detach_reset=True, surrogate_function=surrogate.ATan(), backend='torch')
AttributeError: module 'spikingjelly.clock_driven.neuron' has no attribute 'MultiStepIFNode'
```

2. The 2nd option: I changed all "cext_neuron" into "layer" neurons. 
``` 
net = spiking_resnet.spiking_resnet34()
net.load_state_dict(torch.load("spiking_resnet_34_checkpoint_319.pth")['model'])
```
Output: 
```
loading Net
Traceback (most recent call last):
  File "/home/assel/Desktop/SEW_2/spikingjelly/test.py", line 326, in <module>
    net_teacher.load_state_dict(torch.load("spiking_resnet_34_checkpoint_319.pth")['model'])
  File "/home/assel/anaconda3/envs/sew/lib/python3.9/site-packages/torch-1.10.2-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SpikingResNet:
	Missing key(s) in state_dict: "sn1.module.surrogate_function.alpha", "layer1.0.sn1.module.surrogate_function.alpha", "layer1.0.sn2.module.surrogate_function.alpha", "layer1.1.sn1.module.surrogate_function.alpha", "layer1.1.sn2.module.surrogate_function.alpha", "layer1.2.sn1.module.surrogate_function.alpha", "layer1.2.sn2.module.surrogate_function.alpha", "layer2.0.sn1.module.surrogate_function.alpha", "layer2.0.sn2.module.surrogate_function.alpha", "layer2.1.sn1.module.surrogate_function.alpha", "layer2.1.sn2.module.surrogate_function.alpha", "layer2.2.sn1.module.surrogate_function.alpha", "layer2.2.sn2.module.surrogate_function.alpha", "layer2.3.sn1.module.surrogate_function.alpha", "layer2.3.sn2.module.surrogate_function.alpha", "layer3.0.sn1.module.surrogate_function.alpha", "layer3.0.sn2.module.surrogate_function.alpha", "layer3.1.sn1.module.surrogate_function.alpha", "layer3.1.sn2.module.surrogate_function.alpha", "layer3.2.sn1.module.surrogate_function.alpha", "layer3.2.sn2.module.surrogate_function.alpha", "layer3.3.sn1.module.surrogate_function.alpha", "layer3.3.sn2.module.surrogate_function.alpha", "layer3.4.sn1.module.surrogate_function.alpha", "layer3.4.sn2.module.surrogate_function.alpha", "layer3.5.sn1.module.surrogate_function.alpha", "layer3.5.sn2.module.surrogate_function.alpha", "layer4.0.sn1.module.surrogate_function.alpha", "layer4.0.sn2.module.surrogate_function.alpha", "layer4.1.sn1.module.surrogate_function.alpha", "layer4.1.sn2.module.surrogate_function.alpha", "layer4.2.sn1.module.surrogate_function.alpha", "layer4.2.sn2.module.surrogate_function.alpha". 
```

I think I cannot use these weights.
Thank you again for your help. 

Have a nice day!

**Comment by fangwei123456** [comment]
`RuntimeError: Error(s) in loading state_dict for SpikingResNet:
	Missing key(s) in state_dict: "sn1.module.surrogate_function.alpha"`

It is wired because the surrogate function should not have the learnable parameter:
```
import torch
from spikingjelly.clock_driven import neuron, layer, surrogate

net = layer.MultiStepContainer(neuron.IFNode(detach_reset=True, surrogate_function=surrogate.ATan()))
print(net.state_dict())
```

```
OrderedDict()
```

**Comment by mountains-high** [comment]
In my case when I run above code:
```
OrderedDict([('module.surrogate_function.alpha', tensor(2.))])
```

**Comment by fangwei123456** [comment]
OK, you can try to change

https://github.com/fangwei123456/spikingjelly/blob/2958519df84ad77c316c6e6fbfac96fb2e5f59a3/spikingjelly/clock_driven/surrogate.py#L79

to

`self.alpha=alpha`.

**Comment by mountains-high** [comment]
Thank you very much! Finally, it works :) 
Thank you for your time, Dr. Wei

**Comment by LvQiangWen** [comment]
Sorry to open this issue again, I am trying to use "Spike-Element-Wise-ResNet" project.
When I install spikingjelly from source, I meet the question like this:
The first three steps are good.
![微信图片_20240408085812](https://github.com/fangwei123456/spikingjelly/assets/66072711/3b01aef2-82d0-43a0-92ba-27516e967036)
BUT, when I using "python setup.py install", it turns out this error. I have searched from the internet, but still not solved.
![a43bb47ad681f74e5b1342eac85d537](https://github.com/fangwei123456/spikingjelly/assets/66072711/d1a48b12-9452-4e04-8fa9-f6dc7d3e3de9)

**Comment by RakshithaKalkura** [comment]
> Sorry to open this issue again, I am trying to use "Spike-Element-Wise-ResNet" project. When I install spikingjelly from source, I meet the question like this: The first three steps are good. ![微信图片_20240408085812](https://github.com/fangwei123456/spikingjelly/assets/66072711/3b01aef2-82d0-43a0-92ba-27516e967036) BUT, when I using "python setup.py install", it turns out this error. I have searched from the internet, but still not solved. ![a43bb47ad681f74e5b1342eac85d537](https://github.com/fangwei123456/spikingjelly/assets/66072711/d1a48b12-9452-4e04-8fa9-f6dc7d3e3de9)

I am facing the same issue too. The build fails. Although all the prequisite libraries are installed, I am getting build error.
