### ISSUE TITLE
关于SNN的搭建以及在灵汐芯片上进行推理的细节疑问

### ISSUE THREAD

**Issue by LIFE-SI** [fangwei123456/spikingjelly#463]
对于SNN的搭建以及在灵汐芯片上进行推理，在细节上有几个疑问：
- 灵汐芯片或者说神经形态芯片 是否支持ANN和SNN混合模式？对于所有的诸如卷积、池化等操作后是否必须连接脉冲神经元？芯片能否将经过卷积计算的结果直接输出，还是说必须再经过神经元，芯片只能输出二值？
- 灵汐芯片能否结合传统芯片，将一些ANN中的操作在传统芯片进行，当遇到SNN的操作，像脉冲激活等，转到神经形态芯片上进行？

**Comment by fangwei123456** [comment]
灵汐芯片上没有太多限制，上述操作基本都满足。loihi/lava上限制很多

> 灵汐芯片能否结合传统芯片，将一些ANN中的操作在传统芯片进行，当遇到SNN的操作，像脉冲激活等，转到神经形态芯片上进行？

对于它后台如何计算的细节我不了解
