### ISSUE TITLE
Adding DVS-Lip to pypi version

### ISSUE THREAD

**Issue by tahafkh** [fangwei123456/spikingjelly#471]
Hi,
Is it possible for you to add DVS-Lip dataset to the latest version in pypi? I know it's available in the developer's version, but I can't use that version.

Thank you

**Comment by fangwei123456** [comment]
Hi, can you install from github by pypi? For example, you can use `pip install -qU git+https://github.com/fangwei123456/spikingjelly`.

**Comment by tahafkh** [comment]
Thanks, it worked perfectly!
