### ISSUE TITLE
No module named '_C_neuron'

### ISSUE THREAD

**Issue by jcmharry** [fangwei123456/spikingjelly#48]
您好，在运行example里conv_fashion_mnist_cuda_lbl.py时会出现No module named '_C_neuron'，请问怎么解决？谢谢。

**Comment by fangwei123456** [comment]
参考
https://github.com/fangwei123456/spikingjelly/issues/47
https://github.com/fangwei123456/spikingjelly/issues/46

**Comment by jcmharry** [comment]
问题解决，感谢！
