### ISSUE TITLE
灵汐芯片推理环境要求

### ISSUE THREAD

**Issue by xander-2077** [fangwei123456/spikingjelly#489]
请问作者在运行lynxi_fmnist_inference.py时使用的lynDriver, lynSDK, lyngor版本，以及python, pytorch, torchvision版本是什么呢？能否提供一个pip导出的requirements文件？
Thanks!

**Comment by fangwei123456** [comment]
python, pytorch, torchvision没有特殊要求，但前者已经不可查了。这边的灵汐服务器已经不在了

**Comment by xander-2077** [comment]
好的，感谢您的快速回复！
