### ISSUE TITLE
关于surrogate模块中的参数param spiking问题

### ISSUE THREAD

**Issue by wangqh1996** [fangwei123456/spikingjelly#49]
您好，非常感谢你们的开源工作！我想咨询一下``surrogate``模块中的参数``param spiking``的问题，文档中说的是``param spiking``: 是否输出脉冲，默认为 ``True``，在前向传播时使用 ``heaviside`` 而在反向传播使用替代梯度。若为 ``False``则不使用替代梯度，前向传播时，使用反向传播时的梯度替代函数对应的原函数；是否可以理解为如果``spiking``为``False``，则前向传播是基于替代梯度函数的原函数而不是阶跃函数，这样LIF神经元就类似于特殊的ANN神经元，替代梯度类似传统的激活函数？关于``spiking``参数的设置的用途是否可以先选择``spiking=False``训练几轮模型，然后``spiking``设置为``true``,在基于预训练模型继续训练。另外我在源代码中暂时只看到``PiecewiseLeakyReLU``类有关于``spiking``参数的实现，其他替代梯度函数的写法类似吗？期待您的解答。

**Comment by fangwei123456** [comment]
> 是否可以理解为如果spiking为False，则前向传播是基于替代梯度函数的原函数而不是阶跃函数，这样LIF神经元就类似于特殊的ANN神经元，替代梯度类似传统的激活函数？

是的，如果设置成`False`，则直接用替代函数作为原函数，输出是浮点值而非0/1。但如果是在eval模式下，无论`spiking`是否为`True`，都会使用阶跃函数。

> 关于spiking参数的设置的用途是否可以先选择spiking=False训练几轮模型，然后spiking设置为true,在基于预训练模型继续训练。

可以这样。

设置`spiking`这样一个参数是因为有些文章在训练时使用替代函数，推理时使用阶跃函数，并且发现效果也不错。

**Comment by wangqh1996** [comment]
> > 是否可以理解为如果spiking为False，则前向传播是基于替代梯度函数的原函数而不是阶跃函数，这样LIF神经元就类似于特殊的ANN神经元，替代梯度类似传统的激活函数？
> 
> 是的，如果设置成`False`，则直接用替代函数作为原函数，输出是浮点值而非0/1。但如果是在eval模式下，无论`spiking`是否为`True`，都会使用阶跃函数。
> 
> > 关于spiking参数的设置的用途是否可以先选择spiking=False训练几轮模型，然后spiking设置为true,在基于预训练模型继续训练。
> 
> 可以这样。
> 
> 设置`spiking`这样一个参数是因为有些文章在训练时使用替代函数，推理时使用阶跃函数，并且发现效果也不错。

好的明白了，非常感谢您的及时回复！

**Comment by fangwei123456** [comment]
由于[PiecewiseLeakyReLU](https://github.com/fangwei123456/spikingjelly/blob/7fb48912e2f0c7a2da3233b3902a1e9fd4f8edf4/spikingjelly/clock_driven/surrogate.py#L888)含有2个决定曲线形状的参数，因此是单独实现的。

其他的替代函数只有1个参数，所以通过继承[SurrogateFunctionBase](https://github.com/fangwei123456/spikingjelly/blob/7fb48912e2f0c7a2da3233b3902a1e9fd4f8edf4/spikingjelly/clock_driven/surrogate.py#L75)实现，参考其[forward](https://github.com/fangwei123456/spikingjelly/blob/7fb48912e2f0c7a2da3233b3902a1e9fd4f8edf4/spikingjelly/clock_driven/surrogate.py#L95)函数：


```
def forward(self, x: torch.Tensor):
        if self.training:
            if self.spiking:
                return self.spiking_function(x, self.alpha)
            else:
                return self.primitive_function(x, self.alpha)
        else:
            # 无论是否为spiking模式，只要是测试（推理）阶段，都直接使用阶跃函数
            return heaviside(x)
```

**Comment by wangqh1996** [comment]
> 由于[PiecewiseLeakyReLU](https://github.com/fangwei123456/spikingjelly/blob/7fb48912e2f0c7a2da3233b3902a1e9fd4f8edf4/spikingjelly/clock_driven/surrogate.py#L888)含有2个决定曲线形状的参数，因此是单独实现的。
> 
> 其他的替代函数只有1个参数，所以通过继承[SurrogateFunctionBase](https://github.com/fangwei123456/spikingjelly/blob/7fb48912e2f0c7a2da3233b3902a1e9fd4f8edf4/spikingjelly/clock_driven/surrogate.py#L75)实现，参考其[forward](https://github.com/fangwei123456/spikingjelly/blob/7fb48912e2f0c7a2da3233b3902a1e9fd4f8edf4/spikingjelly/clock_driven/surrogate.py#L95)函数：
> 
> ```
> def forward(self, x: torch.Tensor):
>         if self.training:
>             if self.spiking:
>                 return self.spiking_function(x, self.alpha)
>             else:
>                 return self.primitive_function(x, self.alpha)
>         else:
>             # 无论是否为spiking模式，只要是测试（推理）阶段，都直接使用阶跃函数
>             return heaviside(x)
> ```

好的，非常感谢，我尝试一下。
