### ISSUE TITLE
关于cuda增强的神经元在3090显卡中的使用问题

### ISSUE THREAD

**Issue by wangqh1996** [fangwei123456/spikingjelly#50]
您好，我在``2080Ti``显卡，``cuda10.1``环境下成功使用了cuda增强的神经元进行加速，但是当我使用相同的安装方法在``3090``显卡，``cuda11``环境中尝试进一步加速时，虽然可以成功安装，而且在不使用``cuda``增强的神经元情况下也可以成功运行，但是当使用cuda加速神经元是，导入模块时显示  ``import _C_neuron`` 时出错，``ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory``。不知目前是对cuda版本有一定要求吗，感谢您的帮助，非常感谢！

**Comment by fangwei123456** [comment]
框架本身应该是同时兼容cuda10和11的，可以尝试一下在3090显卡的机器上删除原来的spikingjelly并重新安装。

> 导入模块时显示 import _C_neuron 时出错，ImportError: libcudart.so.10.1

看起来这个_C_neuron像是在CUDA10.1环境下编译出来的

**Comment by wangqh1996** [comment]
感谢解答，确实是因为之前没有卸载干净，不过重新安装时遇到了新的问题，``nvcc fatal   : Unsupported gpu architecture 'compute_86'``, 因为目前cuda11.0版本不支持30系列的算力，等pytorch官方更新支持11.0以上版本在做尝试。
