### ISSUE TITLE
[Request] SuperSpike surrogate function

### ISSUE THREAD

**Issue by JackCaster** [fangwei123456/spikingjelly#504]
**Issue type**

- [ ] Bug Report
- [x] Feature Request
- [ ] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**
I was wondering if you are thinking of implementing the [SuperSpike](https://arxiv.org/abs/1705.11146v2) surrogate function. It is the default one in [Norse](https://norse.github.io/norse/index.html) and the implementation is [here](https://norse.github.io/norse/_modules/norse/torch/functional/superspike.html#super_fn)

**Comment by fangwei123456** [comment]
Hi, I just added this function (but not CUDA version). You can use it as:
```
import torch
from spikingjelly.activation_based import surrogate

x = torch.randn([8], requires_grad=True)
x[0].data.zero_()
sg = surrogate.SuperSpike()

print(x)
y = sg(x)
print(y)
y.sum().backward()
print(x.grad)
```
