### ISSUE TITLE
Question about DSQN

### ISSUE THREAD

**Issue by QianpengLi577** [fangwei123456/spikingjelly#509]
**For faster response**

| Reinforcement Learning           |  @lucifer2859   |

**Issue type**

- [ ] Bug Report
- [ ] Feature Request
- [x] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**

Actually this is not a problem with spikingjelly. I would like to know the specific version number of ptan in the **DSQN** tutorial. I am using ptan==0.4, but the following error occurs.

```bash
File "train.py", line 141, in <module>
    tgt_net = ptan.agent.TargetNet(net, net_)
TypeError: __init__() takes 2 positional arguments but 3 were given

File "utils/atari_wrappers.py", line 32, in reset
    obs, _, done, _ = self.env.step(self.noop_action)
ValueError: too many values to unpack (expected 4)
```

**Comment by lucifer2859** [comment]
Thanks for the feedback, the modified PTAN package is provided in the new version of the code
