### ISSUE TITLE
请问如何将spikingjelly.datasets.n_mnist.NMNIST转换成train_loader/test_loader

### ISSUE THREAD

**Issue by manwu1994** [fangwei123456/spikingjelly#52]
您好，如题目所描述，我尝试利用spikingjelly识别动态数据集，我看docs中没有给出example，所以想请教一下！
非常感谢！

**Comment by fangwei123456** [comment]
可以试一下下面这份代码：
```
from spikingjelly.datasets.n_mnist import NMNIST
train_data_loader = torch.utils.data.DataLoader(
        dataset=NMNIST(dataset_dir, train=True, use_frame=True, frames_num=T, split_by='number',
                       normalization=None),
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        drop_last=True,
        pin_memory=True)
test_data_loader = torch.utils.data.DataLoader(
        dataset=NMNIST(dataset_dir, train=False, use_frame=True, frames_num=T, split_by='number',
                       normalization=None),
        batch_size=batch_size * 4,
        shuffle=False,
        num_workers=4,
        drop_last=False,
        pin_memory=True)
```

**Comment by fangwei123456** [comment]
如果使用原始AER格式的数据，无法用DataLoader包装，因为原始数据提供的是字典格式，不能被打包成批量的tensor。

**Comment by fangwei123456** [comment]
可以参考下面的一篇文章的源代码，包含识别NMNIST、DVS Gesture、CIFAR10-DVS的代码：
https://www.researchgate.net/publication/346410859_Source_CodesIncorporating_Learnable_Membrane_Time_Constant_to_Enhance_Learning_of_Spiking_Neural_Networks

**Comment by manwu1994** [comment]
感谢您的回复，N-MNIST原始的文件提供的是.bin格式，请问是需要转换成.pt格式吗？再次表达感谢之情！！

**Comment by fangwei123456** [comment]
不需要手动转换。框架代码可以直接读取这些bin文件，并转换成字典形式的npy；如果使用帧数据，还会转换成帧数据的npy。

**Comment by manwu1994** [comment]
感谢回复！我在多次尝试之后还是没法转换......我下载的是N_MNIST的源bin文件.....不需要将源文件进行处理吗？之前尝试dvs_cifar时候，利用给的.mat转成了npy....NMNIST一直没有成功，麻烦了，谢谢！！

**Comment by fangwei123456** [comment]
不需要将原文件进行处理，框架内的代码可以直接读取原文件。原文件下载后会得到Train.zip和Test.zip。这2个文件所在的路径设置为dataset_dir，运行代码可以自动解压、转换成npy。
目录结构如下：
```
`-- NMNIST
    |-- Test.zip
    |-- Train.zip
```

转换完成后得到如下所示的目录结构：
```
`-- NMNIST
    |-- Test.zip
    |-- Train.zip
    |-- events
    `-- frames_num_10_split_by_number_normalization_None
```

**Comment by manwu1994** [comment]
非常感谢您的回复！我实现了~再次表达我的感激之情！！

**Comment by fangwei123456** [comment]
我们最近新增了一个关于数据集的教程，可以参考：
https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/13_neuromorphic_datasets.html

**Comment by manwu1994** [comment]
谢谢！我这几天在跑spikingjelly时候出现
```
from torchaudio.datasets.utils import (
ImportError: cannot import name 'walk_files'
```
然后torchaudio来回折腾也没法解决，请问您有遇到类似的问题吗？谢谢！

**Comment by fangwei123456** [comment]
这是由于 \spikingjelly\datasets\speechcommands.py中有如下代码：
```
from torchaudio.datasets.utils import (
    download_url,
    extract_archive,
    walk_files
)
```

而 ``walk_files``函数已经被torchaudio移除了：
https://github.com/pytorch/audio/issues/1109

在我们修复之前，你可以先从下载SpikingJelly的源代码，注释掉下面这一行：

https://github.com/fangwei123456/spikingjelly/blob/495fa7b41c69d6429e2716a6ec07c64af9c5a4b2/spikingjelly/datasets/__init__.py#L14

然后再从源代码安装。

@Yanqi-Chen 麻烦之后对这个问题修复一下

**Comment by manwu1994** [comment]
好的，非常感谢！！
