### ISSUE TITLE
running build_ext error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by LvQiangWen** [fangwei123456/spikingjelly#520]
I am trying to reproduce "Spike-Element-Wise-ResNet" project.
At the beginning, I am using SpikingJelly installed from pip, version 0.0.0.0.14. Error like this:
>ImportError: cannot import name 'neuron' from 'spikingjelly.cext' (D:\Programming\Anaconda\envs\stable38\lib\site-packages\spikingjelly\cext\__init__.py)

After searching the internet, I tried to install from source and question like this:
![320328191-3b01aef2-82d0-43a0-92ba-27516e967036](https://github.com/fangwei123456/spikingjelly/assets/66072711/0a0f07bf-8d3e-4c6b-98dd-76d87a22d649)
![320328760-d1a48b12-9452-4e04-8fa9-f6dc7d3e3de9](https://github.com/fangwei123456/spikingjelly/assets/66072711/e593f16c-5f4d-453e-a412-aa7e0413d459)

I have checked my cuda and msvc, it should be able to work.
Thanks.

**Comment by LvQiangWen** [comment]
![111](https://github.com/fangwei123456/spikingjelly/assets/66072711/e0902c64-24e6-4029-bbf3-d48a72d8c533)

直接安装最新版也是一样的错误，emmm还有其他解决办法吗
在pip安装的话：ModuleNotFoundError: No module named 'spikingjelly.cext.neuron'

**Comment by fangwei123456** [comment]
像是老版本没有卸载干净，因为cext这个包很早就被去掉了
多执行几次pip uninstall spikingjelly试试

**Comment by LvQiangWen** [comment]
![屏幕截图 2024-04-20 121623](https://github.com/fangwei123456/spikingjelly/assets/66072711/40e48b58-afc0-492c-98d0-10f63d3660cf)
可以了，感谢
