### ISSUE TITLE
请问如果本身使用时序数据，假设数据维度为（B,C,T），还需要额外模拟一个时间T吗，然后在T循环吗？可否出一个时序数据的教程？非常感谢您的回复

### ISSUE THREAD

**Issue by thebug-dev** [fangwei123456/spikingjelly#525]
# **Read before creating a new issue**

- Users who want to use SpikingJelly should first be familiar with the usage of PyTorch. 
- If you do not know much about PyTorch, we recommend that the user can learn the [basic tutorials of PyTorch](https://pytorch.org/tutorials/).
- Do not ask for help with the basic conception of PyTorch/Machine Learning but not related to SpikingJelly. For these questions, please refer to Google or [PyTorch Forums](https://discuss.pytorch.org/).

**For faster response**

You can @ the corresponding developers for your issue. Here is the division:

| Features                         | Developers                                                   |
| -------------------------------- | ------------------------------------------------------------ |
| Neurons and Surrogate Functions  | [fangwei123456](https://github.com/fangwei123456)<br />[Yanqi-Chen](https://github.com/Yanqi-Chen) |
| CUDA Acceleration                | [fangwei123456](https://github.com/fangwei123456)<br />[Yanqi-Chen](https://github.com/Yanqi-Chen) |
| Reinforcement Learning           | [lucifer2859](https://github.com/lucifer2859)                |
| ANN to SNN Conversion            | [DingJianhao](https://github.com/DingJianhao)<br />[Lyu6PosHao](https://github.com/Lyu6PosHao) |
| Biological Learning (e.g., STDP) | [AllenYolk](https://github.com/AllenYolk)                    |
| Others                           | [Grasshlw](https://github.com/Grasshlw)<br />[lucifer2859](https://github.com/lucifer2859)<br />[AllenYolk](https://github.com/AllenYolk)<br />[Lyu6PosHao](https://github.com/Lyu6PosHao)<br />[DingJianhao](https://github.com/DingJianhao)<br />[Yanqi-Chen](https://github.com/Yanqi-Chen)<br />[fangwei123456](https://github.com/fangwei123456) |

We are glad to add new developers who are volunteering to help solve issues to the above table.

**Issue type**

- [ ] Bug Report
- [ ] Feature Request
- [ ] Help wanted
- [x] Other

**SpikingJelly version**

`0.0.0.0.2`

**Description**

...

**Minimal code to reproduce the error/bug**

```python
import spikingjelly
# ...
```

**Comment by thebug-dev** [comment]
按照您mnist的教程：
                for t in range(args.T):
                    encoded_img = encoder(img)  # 对输入图片进行编码
                    out_fr += net(encoded_img)  # 计算网络输出的累加值
                out_fr = out_fr / args.T  # 计算平均输出
如果数据集为（B,C,T）是否应该先更换维度为（T,B,C），再循环T，最后对T维度做平均？

**Comment by thebug-dev** [comment]
您好，经过仔细阅读您sj论文，问题已解决，感谢！

**Comment by fangwei123456** [comment]
这个里面应该有一些相关的内容

https://spikingjelly.readthedocs.io/zh-cn/latest/activation_based/basic_concept.html

T放在最后一维会导致计算效率大幅度下降，在SJ框架里面是放到第0维的

**Comment by fangwei123456** [comment]
https://github.com/fangwei123456/spikingjelly/issues/528#issuecomment-2081435585
