### ISSUE TITLE
前馈ANN转化为SNN

### ISSUE THREAD

**Issue by ppx-hub** [fangwei123456/spikingjelly#54]
您好，在前馈ANN转换SNN的章节中，我运行代码出现两个问题：
1. ann2snn.examples.if_cnn_mnist.py，在examples目录下并没有这个文件
2. 加载默认的转换配置并保存用到了utils模块，在文中提到的ann2snn.utils实现了Config类，但我在ann2snn.examples.utils下并没有找到Config的实现
期待您的回复

**Comment by fangwei123456** [comment]
这一部分的代码是@DingJianhao 完成的，他稍后会回复

**Comment by DingJianhao** [comment]
@ppx-hub 很抱歉 您看到的部分是老文档，我正在搞新的文档。加之今年可能会增加新的内容，还会有更大变动，如有文档更新不及时，敬请谅解

**Comment by DingJianhao** [comment]
> 您好，在前馈ANN转换SNN的章节中，我运行代码出现两个问题：
> 
> 1. ann2snn.examples.if_cnn_mnist.py，在examples目录下并没有这个文件
> 2. 加载默认的转换配置并保存用到了utils模块，在文中提到的ann2snn.utils实现了Config类，但我在ann2snn.examples.utils下并没有找到Config的实现
>    期待您的回复

中文文档已更新
