### ISSUE TITLE
Error in documentation in neuronal_reset ( english version)

### ISSUE THREAD

**Issue by Thvnvtos** [fangwei123456/spikingjelly#57]
Hello, in https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven_en/0_neuron.html
![issue](https://user-images.githubusercontent.com/23236210/112011086-33dce780-8b28-11eb-9ca3-e4c853150899.png)

The line should be : self.v = self.v - spike * self.v_threshold

**Comment by tmasquelier** [comment]
Hi Ilyass! I guess neuronal_reset() is only called when spike=1, so it wouldn't make any difference, would it?

**Comment by fangwei123456** [comment]
Thanks! It is an error.

> Hi Ilyass! I guess neuronal_reset() is only called when spike=1, so it wouldn't make any difference, would it?

Thanks for Tim's reply!
This function will always be called after ``neuronal_fire`` and this function does an element-wise operation. When ``v_reset is None``, the neuron will use soft reset, and ``v = v - v_threshold`` after firing a spike.
