### ISSUE TITLE
惊蛰框架为什么在训练过程中会产生报错，是否可以提供调试的解决思路？

### ISSUE THREAD

**Issue by zhangxiaodi** [fangwei123456/spikingjelly#577]
<img width="828" alt="image" src="https://github.com/user-attachments/assets/92f994d5-5330-4c68-8f49-a8edcd3ce94e">

**Comment by zhangxiaodi** [comment]
具体说明：
我的是pytorch 2.4.0 
显卡 4090
问题是，在前面几个epoch都可以正常跑完，但是跑到十几个epoch的时候出现了这种问题。是否有调试和分析问题的思路呢？

**Comment by Ym-Shan** [comment]
最好提供下你的代码，是在某个epoch更改了输入的tensor尺寸吗？
