### ISSUE TITLE
引入惊蛰框架后会导致自己的logging模块失效

### ISSUE THREAD

**Issue by AmazingDD** [fangwei123456/spikingjelly#578]
如题，

**Comment by fangwei123456** [comment]
SJ框架中有些代码可能会设置了logging的等级，覆盖掉你的默认设置，比如：
https://github.com/fangwei123456/spikingjelly/blob/31a867346477695a467faab16b1c2153dd9c18e5/spikingjelly/activation_based/auto_cuda/base.py#L78


建议在import相关模块后，在你自己的代码前重新设置logging等级

**Comment by AmazingDD** [comment]
原来如此 感谢
