### ISSUE TITLE
SNN参数量和运算代价计算

### ISSUE THREAD

**Issue by 1439278026** [fangwei123456/spikingjelly#579]
请教一下SNN的参数量如何计算，包括FLOPs（MAC乘法，AC加法），Params。

**Comment by Met4physics** [comment]
SNN的参数量就是conv层这些的参数量，你可以直接用pytorch summary获取，SNN中不使用浮点数乘法，一般用SOP衡量计算量

**Comment by zhangxiaodi** [comment]
> SNN的参数量就是conv层这些的参数量，你可以直接用pytorch summary获取，SNN中不使用浮点数乘法，一般用SOP衡量计算量

我想咨询一下如何计算SNN网络功耗呢？我在淘宝上基本上看不到有neuromorphic开发板的购买链接。

**Comment by Met4physics** [comment]
> > SNN的参数量就是conv层这些的参数量，你可以直接用pytorch summary获取，SNN中不使用浮点数乘法，一般用SOP衡量计算量
> 
> 我想咨询一下如何计算SNN网络功耗呢？我在淘宝上基本上看不到有neuromorphic开发板的购买链接。

可以参考这篇文章Diet-snn: Direct input encoding with leakage and threshold optimization in deep spiking neural networks，另外一般不会上板子做实验

**Comment by zhangxiaodi** [comment]
他不上板子做实验 这个文章的功耗估计可靠吗？

**Comment by Met4physics** [comment]
> 他不上板子做实验 这个文章的功耗估计可靠吗？

没有办法，板子很难弄到

**Comment by zhangxiaodi** [comment]
对了，有没有SNN模型估算功耗的代码吗

**Comment by Bullboyking** [comment]
> > 他不上板子做实验 这个文章的功耗估计可靠吗？
> 
> 没有办法，板子很难弄到

这个算法有在speck开发板上部署吗？我看到有在nature communication发表文章（姚满）
