### ISSUE TITLE
Deprecated usage of `np.int` in the codebase

### ISSUE THREAD

**Issue by Doudou-Wu** [fangwei123456/spikingjelly#583]
**Issue type**

- [x] Bug Report
- [ ] Feature Request
- [ ] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**

Hi, I noticed that the codebase is still using np.int, which has been deprecated in NumPy 1.20 and later versions. This leads to compatibility issues and deprecation warnings in the newer versions of NumPy.

**Minimal code to reproduce the error/bug**

1. Install NumPy 1.20+ in a Python environment.
2. Run any script that triggers the usage of np.int from the SpikingJelly codebase.
3. Observe the Deprecation AttributeError.

**Affected Code**
Please search and replace occurrences of np.int across the codebase. Specifically, I found the usage in the following files:
"spikingjelly/activation_based/auto_cuda/base.py" in line 249:
`elif value.dtype == np.int:`
to
`elif value.dtype == int:  `

**Comment by CheKaiWei** [comment]
This bug is fixed by the new commit:
https://github.com/fangwei123456/spikingjelly/commit/5e95cddc25962e5119682711defec3f020910bba
