### ISSUE TITLE
有没有办法估算脉冲平均发放频率呢？

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#59]
您好。由于这个SNN是基于GPU和pytorch的，所以无法体现出来SNN的低功耗特性。有相关研究表示，神经态芯片主要的功耗在于脉冲发放，只要知道了脉冲发放频率和对应的突触数量，就能大概估算出来相应的功率。
那有没有办法估算脉冲平均发放频率的方法呢？比如说在使用卷积SNN来运算的时候。
恳请大佬指点一二。

**Comment by Yanqi-Chen** [comment]
感谢您的建议！
框架的Monitor部分提供了计算网络平均发放率的监测方式，可以参考相应的[教程](https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven/12_monitor.html)。而类似的能耗估算需要相关芯片的具体数据，如IBM TrueNorth、Intel Loihi、Spinnaker等都有不同的能耗特性，这在部分文献中也有提到。

**Comment by huatianxue1994** [comment]
谢谢！

**Comment by huatianxue1994** [comment]
您好！我升级到了最新的版本spikingjelly==0.0.0.4，尝试使用教程中的monitor，但是在导入包的时候出现错误。
报错为No module named '_C_neuron'。没有这个_C_neuron的包，我查看本机python下“\Lib\site-packages\spikingjelly\cext”文件夹下只有四个.py文件，没有_C_neuron,也没有文件夹

**Comment by Yanqi-Chen** [comment]
可参考 #46

**Comment by huatianxue1994** [comment]
谢谢！

**Comment by huatianxue1994** [comment]
谢谢！由于某些原因，我未能成功下载最新版的master压缩包。我本地电脑有去年12月份的master压缩包，我在spiking-master下执行命令“python setup.py install”，显示成功安装“spikingjelly==0.0.0.2”。但是运行程序时，依然存在“No module named '_C_neuron'”的错误。查看本地电脑\Lib\site-packages\下，也没有spikingjelly的文件夹。这是怎么回事呢？恳请指点一下，万分感谢！

**Comment by huatianxue1994** [comment]
目前已经成功下载最近版本的master压缩包，在相应目录下打算运行“python setup.py install”， Microsoft Visual C++ 14.0当时还未安装完成，安装完成后再试试

**Comment by fangwei123456** [comment]
c_neuron是个共性的问题，稍后我们会更新相关代码和readme，届时会在此issue通知你。

**Comment by huatianxue1994** [comment]
谢谢！刚刚安装完成VS14.0，但是依然会报错，无法成功使用python setup.py install完成源代码的安装。万分期待后续的解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
c_neuron是个共性的问题，稍后我们会更新相关代码和readme，届时会在此issue通知你。

**Comment by Yanqi-Chen** [comment]
可以试一下刚更新的代码，另外有GPU和CUDA的机器安装会容易一些

**Comment by huatianxue1994** [comment]
好的谢谢！我的机器上安装了GPU和cuda。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午11:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
可以试一下刚更新的代码，另外有GPU和CUDA的机器安装会容易一些

**Comment by huatianxue1994** [comment]
另外，由于某种原因，我这里无法使用git clone https://github.com/fangwei123456/spikingjelly.git这种方式安装。
我是将那个master包下载下来了，然后在命令行里运行的python setup.py install，应该效果是一样的吧？

**Comment by Yanqi-Chen** [comment]
对，应该是一样的

**Comment by huatianxue1994** [comment]
谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
对，应该是一样的

**Comment by fangwei123456** [comment]
更新了readme。在没有CUDA的机器上安装，是不会编译CUDA扩展的。

**Comment by fangwei123456** [comment]
安装报错，具体报错信息是什么？

**Comment by huatianxue1994** [comment]
刚刚出门了😂一会儿回实验室看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
安装报错，具体报错信息是什么？

**Comment by huatianxue1994** [comment]
产生的报错较多，不太清楚其含义，截取一部分刚刚报错的消息

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
安装报错，具体报错信息是什么？

**Comment by huatianxue1994** [comment]
![微信图片_20210330122407](https://user-images.githubusercontent.com/56421468/112933745-065cf300-9153-11eb-8870-f927835a26ab.png)

**Comment by huatianxue1994** [comment]
![image](https://user-images.githubusercontent.com/56421468/112933831-268cb200-9153-11eb-89eb-e9fc22ae72c2.png)
第一张图是报错的开始，第二张图是报错的结束

**Comment by huatianxue1994** [comment]
![image](https://user-images.githubusercontent.com/56421468/112934315-16290700-9154-11eb-9af5-6661f609a89c.png)
这个是报错的开始，
![image](https://user-images.githubusercontent.com/56421468/112934348-2a6d0400-9154-11eb-92ea-d411fd0fd000.png)
这个是报错的末尾

**Comment by huatianxue1994** [comment]
![image](https://user-images.githubusercontent.com/56421468/112934424-525c6780-9154-11eb-94aa-c370e06bbb13.png)
这是我目前torch的版本

**Comment by fangwei123456** [comment]
看一下环境变量的path中是否有类似的路径：
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64
这个是cl.exe所在的目录

**Comment by huatianxue1994** [comment]
好的，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午12:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
看一下环境变量的path中是否有类似的路径：
 C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64
 这个是cl.exe所在的目录

**Comment by huatianxue1994** [comment]
![image](https://user-images.githubusercontent.com/56421468/112935621-b1bb7700-9156-11eb-83ff-9b3d465a646f.png)
我的机器中有多个cl.exe文件，不太清楚放哪个进去可以。但都在bin文件夹下，所以我直接将bin文件夹放到环境变量中去。

![image](https://user-images.githubusercontent.com/56421468/112936688-db759d80-9158-11eb-895e-62fa98ec8b2d.png)
这个是目前的报错情况，看来是要安装GCC。不过我目前的机器是Windows，是不是要解决这个问题还比较困难？

**Comment by fangwei123456** [comment]
应该不需要GCC。建议试一下先用conda装一个pytorch的虚拟环境，然后在虚拟环境中尝试。conda中的pytorch比pip的好一些。windows下是可以编译CUDA扩展的，而且不需要GCC，我这样做是成功的。
如果你不需要CUDA扩展，可以直接用这个setup.py：
https://github.com/fangwei123456/spikingjelly/blob/c61ee0611899c32d59f32b15a9ea07a1516d9fa0/setup.py

**Comment by huatianxue1994** [comment]
好的 谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
应该不需要GCC。建议试一下先用conda装一个pytorch的虚拟环境，然后在虚拟环境中尝试。conda中的pytorch比pip的好一些。windows下是可以编译CUDA扩展的，而且不需要GCC，我这样做是成功的。
 如果你不需要CUDA扩展，可以直接用这个setup.py：
 https://github.com/fangwei123456/spikingjelly/blob/c61ee0611899c32d59f32b15a9ea07a1516d9fa0/setup.py

**Comment by fangwei123456** [comment]
conda环境下安装仍然失败的话，麻烦在此issue中回复一下报错的信息。

**Comment by huatianxue1994** [comment]
好的好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 中午1:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
conda环境下安装仍然失败的话，麻烦在此issue中回复一下报错的信息。

**Comment by huatianxue1994** [comment]
由于实验室网速慢+重新配置环境耗时较长（对我而言。。。）我使用本台机器中的虚拟机（环境为：Ubuntu+anaconda3+python3.8+pytorch1.7.1+cpu）可以正常使用“python setup.py install”
![image](https://user-images.githubusercontent.com/56421468/112943901-ae2eec80-9164-11eb-8790-03dddcb9b36c.png)

**Comment by fangwei123456** [comment]
linux配环境确实比windows方便多了。windows下conda环境下安装的结果如何？

**Comment by huatianxue1994** [comment]
不怕大佬笑话，我当时Windows下装conda+pytorch+cuda+cudnn费了九牛二虎之力也没整明白，后来卸载了conda又花了很久安装仅仅安装python3.6.6+pytorch-gpu+cuda+cudnn。没敢把目前的环境给卸载，怕装不回去

**Comment by fangwei123456** [comment]
windows下装cuda和cudnn确实麻烦，那就先这样用吧

**Comment by huatianxue1994** [comment]
谢谢！
关于脉冲平均发放率的问题，为什么第2层就不行呢？明明第1层和第3层的平均发放率都是有的呀？
![image](https://user-images.githubusercontent.com/56421468/112948347-8e9ac280-916a-11eb-8787-98861104bf5b.png)

**Comment by Yanqi-Chen** [comment]
第二层是FC，不是神经元，发放率只对神经元层才有定义

**Comment by huatianxue1994** [comment]
啊！谢谢大佬指点！

**Comment by huatianxue1994** [comment]
你好！对于教程中的网络结构，脉冲平均发放数量是不是（784+100+10）*0.2655=237.357？
那么平均每秒大概发放多少次呢？就是最一开始的问题，如果这个模拟环境是真实硬件的话，每秒大概多少次脉冲该如何计算呢？

**Comment by Yanqi-Chen** [comment]
计算的是总能耗而非功率，因此一般只考虑发放的脉冲总数，发放间隔并不十分重要。可以参考[DIET-SNN](https://arxiv.org/abs/2008.03658)的计算方式。

**Comment by huatianxue1994** [comment]
谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




 
计算的是总能耗而非功率，因此一般只考虑发放的脉冲总数，发放间隔并不十分重要。可以参考DIET-SNN的计算方式。

**Comment by huatianxue1994** [comment]
![image](https://user-images.githubusercontent.com/56421468/113075616-dcadd580-91ff-11eb-95bf-21139019e3d4.png)
你好，我想请教一下，当网络结构是这种的时候，module_name是什么呢？我尝试了1,2,3,4和static_conv、conv，好像都不太好使。
![image](https://user-images.githubusercontent.com/56421468/113075782-38785e80-9200-11eb-974b-6fe7fce36e5a.png)

**Comment by Yanqi-Chen** [comment]
> ![image](https://user-images.githubusercontent.com/56421468/113075616-dcadd580-91ff-11eb-95bf-21139019e3d4.png)
> 你好，我想请教一下，当网络结构是这种的时候，module_name是什么呢？我尝试了1,2,3,4和static_conv、conv，好像都不太好使。
> ![image](https://user-images.githubusercontent.com/56421468/113075782-38785e80-9200-11eb-974b-6fe7fce36e5a.png)

关于模块命名，如文档所说请参见PyTorch的[命名方式](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=named_module#torch.nn.Module.named_modules)。

**Comment by huatianxue1994** [comment]
谢谢！恍然大悟！前者是Avg Spike Times这个说法更准确哈。那也就是说，实际上，spikingjelly中乘以一个步长T,就是DIET-SNN中的“平均发放次数”了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 上午9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)





  
你好！DIET-SNN文章中的spikerate和教程中的平均发放率是同一回事嘛？我发现无论我怎么调整神经元的参数，步长的大小，都无法使平均发放率超过1，最多稳定在0.5左右（无论是IF还是LIF神经元）。而DIET-SNN文章表示它在VGG的类似结构中，发放率稳定在1.6，也就是整个训练过程中每个神经元平均发放1.6次。 所以，DIET-SNN文章中的spikerate和spikingjelly中的平均发放率不是同一回事吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月30日(星期二) 下午4:58 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59) 计算的是总能耗而非功率，因此一般只考虑发放的脉冲总数，发放间隔并不十分重要。可以参考DIET-SNN的计算方式。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
现行文章中关于平均发放率实际上有两种不同的计算方式
 #Spike / #Neuron
 #Spike / (#Neuron * T)
 SpikingJelly使用的是后者，因为前者更适合被称为Avg Spike Times

**Comment by huatianxue1994** [comment]
谢谢！承蒙指导，十分感激！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 上午9:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)





  

 你好，我想请教一下，当网络结构是这种的时候，module_name是什么呢？我尝试了1,2,3,4和static_conv、conv，好像都不太好使。
 
  
关于模块命名，如文档所说请参见PyTorch的命名方式。

**Comment by huatianxue1994** [comment]
现行文章中关于平均发放率实际上有两种不同的计算方式
#Spike / #Neuron
#Spike / (#Neuron * T)
SpikingJelly使用的是后者，因为前者更适合被称为Avg Spike Times。
关于这一段表述，其中的“T”是指训练过程中全部的推理时间，还是仅仅是训练步长呢（如下图中的T=8）？
![image](https://user-images.githubusercontent.com/56421468/115200290-9ffe3b80-a126-11eb-95aa-614273b3d089.png)

**Comment by Yanqi-Chen** [comment]
> 关于这一段表述，其中的“T”是指训练过程中全部的推理时间，还是仅仅是训练步长呢（如下图中的T=8）？

全部的推理时间指的是？对于单个神经元而言，T指的就是仿真步长。

**Comment by huatianxue1994** [comment]
谢谢！多有叨扰，承蒙指导，多谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月19日(周一) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 有没有办法估算脉冲平均发放频率呢？ (#59)




  
关于这一段表述，其中的“T”是指训练过程中全部的推理时间，还是仅仅是训练步长呢（如下图中的T=8）？
  
全部的推理时间指的是？对于单个神经元而言，T指的就是仿真步长。
