### ISSUE TITLE
Numpy error in cupy execution

### ISSUE THREAD

**Issue by Pooookeman** [fangwei123456/spikingjelly#595]
**Issue type**

- [x] Bug Report
- [ ] Feature Request
- [ ] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**
Numpy error in cupy execution

**Minimal code to reproduce the error/bug**

***Bug description***
Exception has occurred: AttributeError
module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  File "network.py", line 23, in forward
    x = self.network(x)
  File "network.py", line 31, in <module>
    out = model(input)
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
***Minimum code implementation***

```python
import torch
import torch.nn as nn
from spikingjelly.activation_based import layer, neuron, surrogate

class SMLP_eg(nn.Module):
    def __init__(self, input_dim, hidden_dim, out_dim):
        super().__init__()
        self.network = nn.Sequential(
        layer.Linear(input_dim, hidden_dim, bias=False),
        neuron.LIFNode(tau=2., surrogate_function=surrogate.ATan(),step_mode='m', backend='cupy'),
        layer.Linear(hidden_dim, hidden_dim, bias=False),
        neuron.LIFNode(tau=2., surrogate_function=surrogate.ATan(),step_mode='m', backend='cupy'),
        layer.Linear(hidden_dim, out_dim, bias=False),
        )

    def forward(self,x):
        x = self.network(x)
        return x

# Model test
if __name__ == '__main__':
    input = torch.rand(98, 32, 40).cuda() # 4-second visual frames
    model = SMLP_eg(40, 64, 35).cuda()
    print("Model para number = %.2f"%(sum(param.numel() for param in model.parameters()) / 1e6))
    out = model(input)
    print(out.shape)

```

**Comment by fangwei123456** [comment]
Hi, this problem did not occur in my version (the latest github version):

```
C:\Users\fw\anaconda3\envs\pytorch2\python.exe C:\Users\fw\Desktop\代码\spikingjelly\test.py 
Model para number = 0.01
torch.Size([98, 32, 35])
```

You can try to install from github and check again.

**Comment by fangwei123456** [comment]
I fixed this bug before:

https://github.com/fangwei123456/spikingjelly/commit/5e95cddc25962e5119682711defec3f020910bba
