### ISSUE TITLE
LIF神经元的参数\tau的单位是秒还是毫秒呢？

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#60]
![image](https://user-images.githubusercontent.com/56421468/113084052-dcb5d180-920f-11eb-83e3-1eb8de85bf79.png)

请教一个问题。LIF神经元中，膜时间常数\tau的默认值比如说100，那物理意义上是指100s还是指100ms呢？我看很多文章中LIF的膜时间常数都是以毫秒为单位的，在spikingjelly中的LIF是不是也是这样呢？

**Comment by fangwei123456** [comment]
100个仿真步长的意思，没有实际的物理意义。很多以往的工作把仿真步长设置成1ms，这种情况下相当于是100ms

**Comment by huatianxue1994** [comment]
谢谢！
