### ISSUE TITLE
梯度替代和反向传播算法是同一回事嘛？

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#61]
请教大佬一个原理问题，没想明白。
spikingjelly教程里面说到，反向传播的时候，使用梯度替代函数sigmoid函数来替代脉冲的梯度。同时，我在很多文献中看到“spike-based BP”的方式.例如[https://arxiv.org/pdf/1903.06379v1.pdf](url)这篇文章中的误差反向传播算法。
![image](https://user-images.githubusercontent.com/56421468/113110324-865d8880-9239-11eb-850d-fbced8296ee2.png)
这中误差反向传播方式和spikingjelly中的一样吗？期待您的答疑解惑

**Comment by fangwei123456** [comment]
不一样，这篇文章用的是特殊的方法。这篇文章被复现了：
https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/clock_driven/examples/cifar10_r11_enabling_spikebased_backpropagation.py

**Comment by huatianxue1994** [comment]
谢谢！多谢指导！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fangwei123456/spikingjelly] 梯度替代和反向传播算法是同一回事嘛？ (#61)





 
历史上以及最近都有大量使用BP训练SNN的算法，这些并不都是替代梯度方法，如SpikeProp。建议先好好阅读相关综述如这个，issue最好主要是讨论框架具体的问题。
