### ISSUE TITLE
使用卷积SNN识别Fashion-MNIST

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#64]
你好，我想请问一下，在卷积SNN中，图像输入转化为脉冲输入，是使用的什么编码方式呢？是使用首脉冲触发的时间编码吗？
在教程中没有看到详细的说明，请指点一二。

**Comment by huatianxue1994** [comment]
我看教程中写的是“将图像直接送入SNN”中，是不是一个像素点对应一个脉冲发放时间呢？像素点亮度决定脉冲发放的时刻？

**Comment by fangwei123456** [comment]
与https://github.com/fangwei123456/spikingjelly/issues/43类似
我的观点是，直接输入图像，经过卷积层，再到脉冲神经元，实际上构成了一种可学习的周期性的延迟编码器。
如果设置卷积层的通道数为1，卷积核大小1，权重也是1，偏置为0，那{卷积-IF神经元}这个整体就构成了一个最简单的延迟编码器，输入像素值为p时，每ceil(v_threshold/p)个时间步释放一次脉冲。p越大，释放脉冲越早。

这个教程里面的代码，卷积层通道为128，卷积核大小3*3，权重是可学习的，因此是一个非常复杂的可学习的周期性的延迟编码器。

**Comment by huatianxue1994** [comment]
非常感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上8:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fangwei123456/spikingjelly] 使用卷积SNN识别Fashion-MNIST (#64)





 
与https://github.com/fangwei123456/spikingjelly/issues/43类似
 我的观点是，直接输入图像，经过卷积层，再到脉冲神经元，实际上构成了一种可学习的周期性的延迟编码器。
 如果设置卷积层的通道数为1，卷积核大小1，权重也是1，偏置为0，那{卷积-IF神经元}这个整体就构成了一个最简单的延迟编码器，输入像素值为p时，每ceil(v_threshold/p)个时间步释放一次脉冲。p越大，释放脉冲越早。
 
这个教程里面的代码，卷积层通道为128，卷积核大小3*3，权重是可学习的，因此是一个非常复杂的可学习的周期性的延迟编码器。

**Comment by huatianxue1994** [comment]
你好。刚刚浏览了相关的文献，那是不是这样的意思呢：输入图像是28*28的灰度图像，经过卷积出来的是128*28*28一个张量，然后这个张量中的每一个值都遵循“每ceil(v_threshold/p)个时间步释放一次脉冲”的规则，这样形成了128*28*28个脉冲。也就是说{卷积层-编码神经元}相当于一个整体。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上8:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fangwei123456/spikingjelly] 使用卷积SNN识别Fashion-MNIST (#64)





 
与https://github.com/fangwei123456/spikingjelly/issues/43类似
 我的观点是，直接输入图像，经过卷积层，再到脉冲神经元，实际上构成了一种可学习的周期性的延迟编码器。
 如果设置卷积层的通道数为1，卷积核大小1，权重也是1，偏置为0，那{卷积-IF神经元}这个整体就构成了一个最简单的延迟编码器，输入像素值为p时，每ceil(v_threshold/p)个时间步释放一次脉冲。p越大，释放脉冲越早。
 
这个教程里面的代码，卷积层通道为128，卷积核大小3*3，权重是可学习的，因此是一个非常复杂的可学习的周期性的延迟编码器。

**Comment by fangwei123456** [comment]
> 然后这个张量中的每一个值都遵循“每ceil(v_threshold/p)个时间步释放一次脉冲”的规则
只有卷积核大小为1且权重为1，才满足这个计算公式。实际的公式应该是ceil(v_threshold/sigma(w_i * p_i))个时间步释放一次脉冲。sigma(w_i * p_i)表示卷积核的卷积过程。

> 也就是说{卷积层-编码神经元}相当于一个整体。
是的。输入图像，输出脉冲的都可以叫编码器，这个整体满足这样的条件。

**Comment by huatianxue1994** [comment]
谢谢！如醍醐灌顶！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月7日(周三) 晚上11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fangwei123456/spikingjelly] 使用卷积SNN识别Fashion-MNIST (#64)




  
然后这个张量中的每一个值都遵循“每ceil(v_threshold/p)个时间步释放一次脉冲”的规则
  
只有卷积核大小为1且权重为1，才满足这个计算公式。实际的公式应该是ceil(v_threshold/sigma(w_i * p_i))个时间步释放一次脉冲。sigma(w_i * p_i)表示卷积核的卷积过程。
  
也就是说{卷积层-编码神经元}相当于一个整体。
  
是的。输入图像，输出脉冲的都可以叫编码器，这个整体满足这样的条件。
