### ISSUE TITLE
关于编码器泊松编码的实现

### ISSUE THREAD

**Issue by cymbidium-lan** [fangwei123456/spikingjelly#68]
初学请教，请问out_spike = torch.rand_like(x).le(x) 中 torch.rand_like(x) 不是生成的是均与分布的张量吗

**Comment by Yanqi-Chen** [comment]
脉冲以输入x为概率发放，因此在T个时间步内发放脉冲次数N服从二项分布B(N,x)，当T充分大时，平均发放率逼近泊松分布。

**Comment by cymbidium-lan** [comment]
多谢解答，我还是有点疑惑，不是二项分布的概率小且次数多才能泊松近似吗，其中的概率不是个定值吗

**Comment by Yanqi-Chen** [comment]
> 不是二项分布的概率小且次数多才能泊松近似吗

是的，所以是渐进意义上的近似，比如x~O(1/n)的情形在n趋向无穷时是很容易证明近似的。而并非对于每个x属于[0,1]都成立。

> 其中的概率不是个定值吗

是的，对于静态图像，输入是固定的像素值，因此的确是定值。

**Comment by cymbidium-lan** [comment]
> 是的，对于静态图像，输入是固定的像素值，因此的确是定值。
多谢解答，  我的理解是二项分布中多次实验的概率一致且为定值，我们这里不是用了均匀分布的一系列随机数表征概率，将X与随机概率比较，大于此概率则发放脉冲，这些概率可以不同吗？

**Comment by Yanqi-Chen** [comment]
这里的均匀分布是用来伯努利采样的，因为二项分布实际上是多个i.i.d.伯努利分布的求和。
比如我想得到一个以p概率取0的伯努利分布，方法是在[0,1]区间随机采样，然后采样值大于p则取1，否则取0。这里的代码就是单次采样的代码。

**Comment by cymbidium-lan** [comment]
再次感谢，意思是二项分布可以理解为，多个不同伯努利实验的叠加，只要他们彼此独立即可，再由于这个实验次数较多，进而近似泊松分布，是这样吗

**Comment by Yanqi-Chen** [comment]
完全正确

**Comment by cymbidium-lan** [comment]
非常感谢大佬耐心讲解！！！！！
