### ISSUE TITLE
About DVS-Gesture dataset

### ISSUE THREAD

**Issue by lslynf** [fangwei123456/spikingjelly#71]
The input of the dataset is (128*128), how to change the input size to (32 * 32)? Thanks  a lot!

**Comment by fangwei123456** [comment]
```
from spikingjelly.datasets import dvs128_gesture
import torch.nn.functional as F
import torch
train_set = dvs128_gesture.DVS128Gesture('D:/datasets/DVS128Gesture', train=True, data_type='frame', frames_number=16, split_by='number')
x, y = train_set[0]
print(x.shape)

x = torch.from_numpy(x).float()

print(F.interpolate(x, size=(32, 32)).shape)


```

**Comment by asselkembay** [comment]
> ```
> from spikingjelly.datasets import dvs128_gesture
> import torch.nn.functional as F
> import torch
> train_set = dvs128_gesture.DVS128Gesture('D:/datasets/DVS128Gesture', train=True, data_type='frame', frames_number=16, split_by='number')
> x, y = train_set[0]
> print(x.shape)
> 
> x = torch.from_numpy(x).float()
> 
> print(F.interpolate(x, size=(32, 32)).shape)
> ```

Good day, I used(run) the above code lines, but I am getting this error:
```/home/assel/.local/lib/python3.6/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
Traceback (most recent call last):
  File "set.py", line 4, in <module>
    train_set = dvs128_gesture.DVS128Gesture('.', train=True, data_type='frame', frames_number=16, split_by='number')
TypeError: __init__() got an unexpected keyword argument 'data_type' 
```

 Could you help me to solve this problem, please? Thank you

**Comment by fangwei123456** [comment]
Do you use an old version (e.g., from pypi)? Some API have been changed after 0.0.0.4. You can try to install from the source codes in GitHub.
