### ISSUE TITLE
Line80 和 Line 84 重复检查了，可以删掉一行

### ISSUE THREAD

**Issue by wangxiao5791509** [fangwei123456/spikingjelly#72]
https://github.com/fangwei123456/spikingjelly/blob/35ef912d29f62f6a1b376b398b7a02b5d221579d/spikingjelly/clock_driven/ann2snn/__init__.py#L80

错了，是 Line 83 ...

**Comment by fangwei123456** [comment]
@DingJianhao 不知是重复还是需要检查2次？
```
onnx.checker.check_model(onnx_model)
if layer_reduc:
    onnx_model = onnx_kernel.layer_reduction(onnx_model)
onnx.checker.check_model(onnx_model)
```

**Comment by DingJianhao** [comment]
当时写的时候 就是希望再检查一次 XD
