### ISSUE TITLE
关于conv_fashion_mnist.py里面的过程

### ISSUE THREAD

**Issue by ZulunZhu** [fangwei123456/spikingjelly#78]
您好，看了这个部分的代码，发现数据的预处理中，没有编码部分，所以整个过程中信号都是实值，这样是否还算SNN呢？

**Comment by fangwei123456** [comment]
参见这两个issues

https://github.com/fangwei123456/spikingjelly/issues/43
https://github.com/fangwei123456/spikingjelly/issues/44

**Comment by ZulunZhu** [comment]
看了这两个的讨论，意思就是输入图像+卷积+LIF，这个整体看作可学习的编码器是吗？ 那这样说来，对于多层的网络来说，编码器的界定也是可变的，比如可以把‘**输入图像+卷积+LIF’**看作编码器，也可以把**‘输入图像+卷积+LIF+卷积+LIF’**看作编码器？万分感谢您的回答！

**Comment by fangwei123456** [comment]
都可以，把所有卷积部分看作编码器也行，后面的全连接层部分看作是分类器。

**Comment by fangwei123456** [comment]
如果给编码器下个定义，把数据转换成脉冲序列的都可以算脉冲编码器，那只要输入是原始数据，输出是脉冲的就都能算编码器了。
