### ISSUE TITLE
能否对 cext 模块中 CUDA 加速的神经元的使用示例做更详细的解释？

### ISSUE THREAD

**Issue by AptX395** [fangwei123456/spikingjelly#80]
首先非常感谢你们的工作！

目前 SpikingJelly 的文档中给出的 CUDA 加速的神经元的用法示例比较简短，我看了之后仍然有许多疑惑，例如 `cext.neuron.LIFNode` 和 `cext.neuron.MultiStepLIFNode` 的区别是什么、在使用 CUDA 加速的神经元搭建网络时 `layer.SeqToANNContainer()` 的作用是什么、训练网络时如何分别进行 forward 和 backward 、如何设置仿真步长、网络的输入为图像时是否必须将图像编码等等。

可以烦请你们对这些疑问进行一下解答吗？十分感谢！

**Comment by fangwei123456** [comment]
建议阅读一下红框内的教程：
![image](https://user-images.githubusercontent.com/38352109/121884924-19d92c80-cd46-11eb-8c76-aa3d088564d4.png)

**Comment by fangwei123456** [comment]
阅读完这些教程后如果有疑问，重新开启此issue即可
