### ISSUE TITLE
关于ANN2SNN，if_resnet18_cifar10.py运行报错的问题

### ISSUE THREAD

**Issue by huatianxue1994** [fangwei123456/spikingjelly#86]
我在运行此程序的时候，碰到了如下错误：
`AttributeError: module 'spikingjelly.clock_driven.neuron' has no attribute 'NSIFNode'`

当前使用的是0.0.0.6版本，这个错误要如何处理呢？
看起来像是neuron模块中没有NSIFNode函数。我本地电脑上有之前0.0.0.4的版本，查看0.0.0.4版本的neuron.py中也没有NSIFNode函数。

**Comment by huatianxue1994** [comment]
@DingJianhao 讲，NSIFNode这个函数已经去掉了，用处不大

**Comment by fangwei123456** [comment]
嗯，我查了一下现在应该只有这个地方用到了：

https://github.com/fangwei123456/spikingjelly/blob/542a06430992780c4a18d6c998e5a10445e968d2/spikingjelly/clock_driven/ann2snn/__init__.py#L121

用try语句框住了，在没有这个模块的情况下应该也不会报错
