### ISSUE TITLE
Tempotron中的一个疑问

### ISSUE THREAD

**Issue by Francis-Zhuang** [fangwei123456/spikingjelly#88]
Tempotron类中，是不是缺了个括号？
原文：self.v0 = self.v_threshold / math.exp(-t_max / tau) - math.exp(-t_max / tau_s)
我认为的：self.v0 = self.v_threshold / (math.exp(-t_max / tau) - math.exp(-t_max / tau_s))
还请指教

**Comment by fangwei123456** [comment]
谢了，应该是错了，明天修复一下。因为相应的教程也得修复一下
