### ISSUE TITLE
The operation problem about example : MINST classification

### ISSUE THREAD

**Issue by Winston-X** [fangwei123456/spikingjelly#89]
When I tried to run the MINST classification example, "AttributeError" happened.

AttributeError: module 'spikingjelly.clock_driven.functional' has no attribute 'set_monitor'

AttributeError: 'LIFNode' object has no attribute 'monitor'

I don't know if it is the problem of the downloaded installation package or the problem of the function file itself. Or others?

**Comment by Winston-X** [comment]
好像只是添加注释而已。那等之后你们修改后再跑一下这个例程。

**Comment by fangwei123456** [comment]
因为monitor只用来画教程里面的图，并不影响训练，所以先直接注释了

**Comment by Yanqi-Chen** [comment]
> 好像只是添加注释而已。那等之后你们修改后再跑一下这个例程。

可以重新试一下这个教程， 代码现在用argparse定义参数而不是在运行时输入了

**Comment by fangwei123456** [comment]
@Winston-X 应该没问题了，如果还有bug，请重新打开这个issue
