### ISSUE TITLE
关于ANN转换SNN

### ISSUE THREAD

**Issue by Francis-Zhuang** [fangwei123456/spikingjelly#92]
有一个关于证明的问题，为什么第一个隐层的恒定输入为z=Vth*a呢，直接就和Relu的激活值建立了联系，是人为规定的吗？感谢！

**Comment by fangwei123456** [comment]
https://www.frontiersin.org/articles/10.3389/fnins.2017.00682/full

原文的公式2，括号里面的部分相当于a吧

**Comment by Francis-Zhuang** [comment]
多谢！我再理解一下
