### ISSUE TITLE
加载数据集的时候出现Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#94]
![%XTHR_B~J}DZ37151JO}`_8](https://user-images.githubusercontent.com/33653847/127950227-a9191a65-12aa-4e38-9547-6ef3dabe3cff.png)

使用的是这里的源码，训练NMNIST的时候出现问题
https://github.com/fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron

**Comment by fangwei123456** [comment]
报错的是哪个文件的哪一行代码？

**Comment by BugCodeHub** [comment]
![image](https://user-images.githubusercontent.com/33653847/127951346-49cf93d3-ec79-4504-8b98-35c5dafa2e13.png)

应该数据加载的时候出错，这边有修改了一些之前的代码，把models里面surrogate.ATan()中的alpha_learnale去掉了

**Comment by fangwei123456** [comment]
我在读取帧数文件的函数里面增加了选项：https://github.com/fangwei123456/spikingjelly/commit/4002b35c55fa75775197262fcb02305c388f9e07

更新一下框架的代码试试。或者是你直接在自己的代码中做同样的修改。

**Comment by BugCodeHub** [comment]
不好意思，我的框架代码是最新的，有看到datasets中__init__.py有范围这个，那我可以直接调用该函数吗？（新手有点迷糊）
或者是我直接写个一样的函数，通过用NMNIST函数处理完的数据再用自己写的load_npz_frames(file_name: str)可以实现转换吗

**Comment by fangwei123456** [comment]
已经是最新的按理说不会报错了。试一下git pull更新后重新安装框架再运行看是否报错。
“通过用NMNIST函数处理完的数据再用自己写的load_npz_frames(file_name: str)可以实现转换吗”这个不行，因为还没有运行到这里就报错了

**Comment by BugCodeHub** [comment]
请问下在使用NMNIST加载数据的时候是不是就会直接调用load_npz_frames(file_name: str)？我试了下更新完还是有问题

**Comment by fangwei123456** [comment]
是的，NMNIST加载积分后的数据，会自动调用load_npz_frames。你放一下完整的报错代码和错误信息吧，别用截图

**Comment by BugCodeHub** [comment]
models.py的代码
`import torch
import torch.nn as nn
import torch.nn.functional as F
from spikingjelly.clock_driven import layer, surrogate
from spikingjelly.clock_driven.neuron import LIFNode
from torchvision import transforms
import math


def create_conv_sequential(in_channels, out_channels, number_layer, init_tau, use_max_pool, detach_reset):
    # 首层是in_channels-out_channels
    # 剩余number_layer - 1层都是out_channels-out_channels
    conv = [
        nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=3, padding=1, bias=False),
        nn.BatchNorm2d(out_channels),
        LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
        nn.MaxPool2d(2, 2) if use_max_pool else nn.AvgPool2d(2, 2)
    ]

    for i in range(number_layer - 1):
        conv.extend([
            nn.Conv2d(in_channels=out_channels, out_channels=out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
            nn.MaxPool2d(2, 2) if use_max_pool else nn.AvgPool2d(2, 2)
        ])
    return nn.Sequential(*conv)


def create_2fc(channels, h, w, dpp, class_num, init_tau, detach_reset):
    return nn.Sequential(
        nn.Flatten(),
        layer.Dropout(dpp),
        nn.Linear(channels * h * w, channels * h * w // 4, bias=False),
        LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
        layer.Dropout(dpp),
        nn.Linear(channels * h * w // 4, class_num * 10, bias=False),
        LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
    )

class NeuromorphicNet(nn.Module):
    def __init__(self, T, init_tau, use_plif, use_max_pool, detach_reset):
        super().__init__()
        self.T = T
        self.init_tau = init_tau
        # self.use_plif = use_plif
        self.use_max_pool = use_max_pool
        # self.alpha_learnable = alpha_learnable
        self.detach_reset = detach_reset

        self.train_times = 0
        self.max_test_accuracy = 0
        self.epoch = 0
        self.conv = None
        self.fc = None
        self.boost = nn.AvgPool1d(10, 10)

    def forward(self, x):
        x = x.permute(1, 0, 2, 3, 4)  # [T, N, 2, *, *]  T时间戳, N batch_size 2正负极性, x,y就是x的像素大小
        out_spikes_counter = self.boost(self.fc(self.conv(x[0])).unsqueeze(1)).squeeze(1)
        for t in range(1, x.shape[0]):
            out_spikes_counter += self.boost(self.fc(self.conv(x[t])).unsqueeze(1)).squeeze(1)
        return out_spikes_counter

class NMNISTNet(NeuromorphicNet):
    def __init__(self, T, init_tau, use_plif, use_max_pool, detach_reset, channels, number_layer):
        super().__init__(T=T, init_tau=init_tau, use_plif=use_plif, use_max_pool=use_max_pool, detach_reset=detach_reset)
        w = 34
        h = 34  # 原始数据集尺寸
        self.conv = create_conv_sequential(2, channels, number_layer=number_layer, init_tau=init_tau, use_max_pool=use_max_pool, detach_reset=detach_reset)
        self.fc = create_2fc(channels=channels, w=w >> number_layer, h=h >>number_layer, dpp=0.5, class_num=10, init_tau=init_tau, detach_reset=detach_reset)

`

train.py
`import torch
import torch.nn as nn
import torch.nn.functional as F
from spikingjelly.clock_driven import functional
import torchvision
from torch.utils.tensorboard import SummaryWriter
import numpy as np
import readline
import os
import argparse
import time
import sys

sys.path.append('./')
from spikingjelly.datasets.n_mnist import NMNIST

torch.backends.cudnn.benchmark = True
_seed_ = 2020
torch.manual_seed(_seed_)  # use torch.manual_seed() to seed the RNG for all devices (both CPU and CUDA)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(_seed_)
import models

'''
静态数据集
/userhome/anaconda3/envs/pytorch-env/bin/python /userhome/plif_test/train.py -init_tau 2.0 -use_plif -use_max_pool -device cuda:0 -dataset_name CIFAR10 -log_dir_prefix ./logsd -T 8 -max_epoch 1024 -detach_reset

/userhome/anaconda3/envs/pytorch-env/bin/python /userhome/plif_test/train.py -init_tau 2.0 -use_plif -use_max_pool -device cuda:0 -dataset_name CIFAR10DVS -log_dir_prefix /userhome/plif_test/logsd -T 20 -max_epoch 512 -detach_reset -channels 128 -number_layer 4 -split_by number -normalization None
train.py -init_tau 2.0 -use_plif -use_max_pool -device cuda:0 -dataset_name CIFAR10DVS -log_dir_prefix /cir                                                                      -T 20 -max_epoch 512 -detach_reset -channels 128 -number_layer 4 -split_by number -normalization None

'''

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    # init_tau, batch_size, learning_rate, T_max, log_dir, use_plif
    parser.add_argument('-init_tau', type=float)
    parser.add_argument('-batch_size', type=int, default=16)
    parser.add_argument('-learning_rate', type=float, default=1e-3)
    parser.add_argument('-T_max', type=int, default=64)
    # parser.add_argument('-use_plif', action='store_true', default=False)
    parser.add_argument('-alpha_learnable', action='store_true', default=False)
    parser.add_argument('-use_max_pool', action='store_true', default=False)
    parser.add_argument('-device', type=str)
    parser.add_argument('-dataset_name', type=str, default='NMNIST')
    parser.add_argument('-log_dir_prefix', type=str)
    parser.add_argument('-T', type=int)
    parser.add_argument('-channels', type=int)
    parser.add_argument('-number_layer', type=int)
    parser.add_argument('-split_by', type=str)
    parser.add_argument('-normalization', type=str)
    parser.add_argument('-max_epoch', type=int)
    parser.add_argument('-detach_reset', action='store_true', default=False)

    args = parser.parse_args()
    argv = ' '.join(sys.argv)

    print(args)
    init_tau = 2.0
    use_frame = True
    batch_size = args.batch_size
    learning_rate = args.learning_rate
    T_max = args.T_max
    # use_plif = args.use_plif
    alpha_learnable = args.alpha_learnable
    use_max_pool = args.use_max_pool
    device = 'cuda'
    dataset_name = args.dataset_name
    dataset_dir = '/code/train_model/nmnist_model/datasets/' + 'N-MNIST'
    # dataset_dir = '/raid/fangw01/cifar10'
    log_dir_prefix = 'code/train_model/nmnist_model/logs'
    T = 10
    max_epoch = 100
    detach_reset = args.detach_reset

    number_layer = 2
    channels = 128
    split_by = 'number'
    normalization = args.normalization
    if normalization == 'None':
        normalization = None

    class_num = 10  # 绝大多数数据集为10，如果不一样，在新建dataloader的时候再修改

    train_data_loader = torch.utils.data.DataLoader(
        dataset=NMNIST(dataset_dir, train=True, data_type='frame', frames_number=20, split_by='number'),
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        drop_last=True,
        pin_memory=True,
    )
    test_data_loader = torch.utils.data.DataLoader(
        dataset=NMNIST(dataset_dir, train=False, data_type='frame', frames_number=20, split_by='number'),
        batch_size=batch_size * 4,
        shuffle=False,
        num_workers=4,
        drop_last=False,
        pin_memory=True,

    )

    net = models.NMNISTNet(T=T, init_tau=init_tau, use_max_pool=use_max_pool,
                           detach_reset=detach_reset, channels=channels,
                           number_layer=number_layer).to(device)

    print(net)
    # 使用Adam优化器
    optimizer = torch.optim.Adam(net.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=T_max)

    for net.epoch in range(net.epoch, max_epoch):

        net.train()
        for img, label in train_data_loader:
            img = img.to(device)
            label = label.to(device)
            optimizer.zero_grad()
        # img = img.type(torch.cuda.FloatTensor)
            out_spikes_counter = net(img)
            out_spikes_counter_frequency = out_spikes_counter / net.T
            loss = F.mse_loss(out_spikes_counter_frequency, F.one_hot(label, class_num).float())
            loss.backward()
            optimizer.step()
            functional.reset_net(net)
            writer.add_scalar('train_correct_rate', correct_rate, train_times)
            if train_times % 100 == 0:
                print(device, dataset_dir, batch_size, learning_rate, T, train_epoch, log_dir, max_test_acccuracy)
            print(sys.argv, 'train_times', train_times, 'train_correct_rate', correct_rate)
            train_times += 1
        scheduler.step()

        net.eval()
        with torch.no_grad():
            test_sum = 0
            correct_sum = 0
            for img, label in test_data_loader:
                img = img.to(device)
                label = label.to(device)
                out_spikes_counter = net(img)
                correct_sum += (out_spikes_counter.argmax(dim=1) == label).float().sum().item()
                test_sum += label.numel()
                functional.reset_net(net)
            test_accuracy = correct_sum / test_sum
            print('test_accuracy', test_accuracy)

            if net.max_test_accuracy <= test_accuracy:
                print('save model with test_accuracy = ', test_accuracy)
                net.max_test_accuracy = test_accuracy
                torch.save({
                    'net': net,
                    'optimizer': optimizer.state_dict(),
                    'scheduler': scheduler.state_dict(),
                    'log_data_list': log_data_list
                }, check_point_max_path)

            # 保存最新模型
            torch.save({
                'net': net,
                'optimizer': optimizer.state_dict(),
                'scheduler': scheduler.state_dict(),
                'log_data_list': log_data_list
            }, check_point_path)
        writer.close()
`

**Comment by BugCodeHub** [comment]
训练的代码
`import torch
import torch.nn as nn
import torch.nn.functional as F
from spikingjelly.clock_driven import functional
import torchvision
from torch.utils.tensorboard import SummaryWriter
import numpy as np
import readline
import os
import argparse
import time
import sys

sys.path.append('./')
from spikingjelly.datasets.n_mnist import NMNIST

torch.backends.cudnn.benchmark = True
_seed_ = 2020
torch.manual_seed(_seed_)  # use torch.manual_seed() to seed the RNG for all devices (both CPU and CUDA)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(_seed_)
import models

'''
静态数据集
/userhome/anaconda3/envs/pytorch-env/bin/python /userhome/plif_test/train.py -init_tau 2.0 -use_plif -use_max_pool -device cuda:0 -dataset_name CIFAR10 -log_dir_prefix ./logsd -T 8 -max_epoch 1024 -detach_reset

/userhome/anaconda3/envs/pytorch-env/bin/python /userhome/plif_test/train.py -init_tau 2.0 -use_plif -use_max_pool -device cuda:0 -dataset_name CIFAR10DVS -log_dir_prefix /userhome/plif_test/logsd -T 20 -max_epoch 512 -detach_reset -channels 128 -number_layer 4 -split_by number -normalization None
train.py -init_tau 2.0 -use_plif -use_max_pool -device cuda:0 -dataset_name CIFAR10DVS -log_dir_prefix /cir                                                                      -T 20 -max_epoch 512 -detach_reset -channels 128 -number_layer 4 -split_by number -normalization None

'''

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    # init_tau, batch_size, learning_rate, T_max, log_dir, use_plif
    parser.add_argument('-init_tau', type=float)
    parser.add_argument('-batch_size', type=int, default=16)
    parser.add_argument('-learning_rate', type=float, default=1e-3)
    parser.add_argument('-T_max', type=int, default=64)
    # parser.add_argument('-use_plif', action='store_true', default=False)
    parser.add_argument('-alpha_learnable', action='store_true', default=False)
    parser.add_argument('-use_max_pool', action='store_true', default=False)
    parser.add_argument('-device', type=str)
    parser.add_argument('-dataset_name', type=str, default='NMNIST')
    parser.add_argument('-log_dir_prefix', type=str)
    parser.add_argument('-T', type=int)
    parser.add_argument('-channels', type=int)
    parser.add_argument('-number_layer', type=int)
    parser.add_argument('-split_by', type=str)
    parser.add_argument('-normalization', type=str)
    parser.add_argument('-max_epoch', type=int)
    parser.add_argument('-detach_reset', action='store_true', default=False)

    args = parser.parse_args()
    argv = ' '.join(sys.argv)

    print(args)
    init_tau = 2.0
    use_frame = True
    batch_size = args.batch_size
    learning_rate = args.learning_rate
    T_max = args.T_max
    # use_plif = args.use_plif
    alpha_learnable = args.alpha_learnable
    use_max_pool = args.use_max_pool
    device = 'cuda'
    dataset_name = args.dataset_name
    dataset_dir = '/code/train_model/nmnist_model/datasets/' + 'N-MNIST'
    # dataset_dir = '/raid/fangw01/cifar10'
    log_dir_prefix = 'code/train_model/nmnist_model/logs'
    T = 10
    max_epoch = 100
    detach_reset = args.detach_reset

    number_layer = 2
    channels = 128
    split_by = 'number'
    normalization = args.normalization
    if normalization == 'None':
        normalization = None

    class_num = 10  # 绝大多数数据集为10，如果不一样，在新建dataloader的时候再修改

    train_data_loader = torch.utils.data.DataLoader(
        dataset=NMNIST(dataset_dir, train=True, data_type='frame', frames_number=20, split_by='number'),
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        drop_last=True,
        pin_memory=True,
    )
    test_data_loader = torch.utils.data.DataLoader(
        dataset=NMNIST(dataset_dir, train=False, data_type='frame', frames_number=20, split_by='number'),
        batch_size=batch_size * 4,
        shuffle=False,
        num_workers=4,
        drop_last=False,
        pin_memory=True,

    )

    net = models.NMNISTNet(T=T, init_tau=init_tau, use_max_pool=use_max_pool,
                           detach_reset=detach_reset, channels=channels,
                           number_layer=number_layer).to(device)

    print(net)
    # 使用Adam优化器
    optimizer = torch.optim.Adam(net.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=T_max)

    for net.epoch in range(net.epoch, max_epoch):

        net.train()
        for img, label in train_data_loader:
            img = img.to(device)
            label = label.to(device)
            optimizer.zero_grad()
        # img = img.type(torch.cuda.FloatTensor)
            out_spikes_counter = net(img)
            out_spikes_counter_frequency = out_spikes_counter / net.T
            loss = F.mse_loss(out_spikes_counter_frequency, F.one_hot(label, class_num).float())
            loss.backward()
            optimizer.step()
            functional.reset_net(net)
            writer.add_scalar('train_correct_rate', correct_rate, train_times)
            if train_times % 100 == 0:
                print(device, dataset_dir, batch_size, learning_rate, T, train_epoch, log_dir, max_test_acccuracy)
            print(sys.argv, 'train_times', train_times, 'train_correct_rate', correct_rate)
            train_times += 1
        scheduler.step()

        net.eval()
        with torch.no_grad():
            test_sum = 0
            correct_sum = 0
            for img, label in test_data_loader:
                img = img.to(device)
                label = label.to(device)
                out_spikes_counter = net(img)
                correct_sum += (out_spikes_counter.argmax(dim=1) == label).float().sum().item()
                test_sum += label.numel()
                functional.reset_net(net)
            test_accuracy = correct_sum / test_sum
            print('test_accuracy', test_accuracy)

            if net.max_test_accuracy <= test_accuracy:
                print('save model with test_accuracy = ', test_accuracy)
                net.max_test_accuracy = test_accuracy
                torch.save({
                    'net': net,
                    'optimizer': optimizer.state_dict(),
                    'scheduler': scheduler.state_dict(),
                    'log_data_list': log_data_list
                }, check_point_max_path)

            # 保存最新模型
            torch.save({
                'net': net,
                'optimizer': optimizer.state_dict(),
                'scheduler': scheduler.state_dict(),
                'log_data_list': log_data_list
            }, check_point_path)
        writer.close()
`

**Comment by BugCodeHub** [comment]
models.py 模块的代码
`import torch
import torch.nn as nn
import torch.nn.functional as F
from spikingjelly.clock_driven import layer, surrogate
from spikingjelly.clock_driven.neuron import LIFNode
from torchvision import transforms
import math


def create_conv_sequential(in_channels, out_channels, number_layer, init_tau, use_max_pool, detach_reset):
    # 首层是in_channels-out_channels
    # 剩余number_layer - 1层都是out_channels-out_channels
    conv = [
        nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=3, padding=1, bias=False),
        nn.BatchNorm2d(out_channels),
        LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
        nn.MaxPool2d(2, 2) if use_max_pool else nn.AvgPool2d(2, 2)
    ]

    for i in range(number_layer - 1):
        conv.extend([
            nn.Conv2d(in_channels=out_channels, out_channels=out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
            nn.MaxPool2d(2, 2) if use_max_pool else nn.AvgPool2d(2, 2)
        ])
    return nn.Sequential(*conv)


def create_2fc(channels, h, w, dpp, class_num, init_tau, detach_reset):
    return nn.Sequential(
        nn.Flatten(),
        layer.Dropout(dpp),
        nn.Linear(channels * h * w, channels * h * w // 4, bias=False),
        LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
        layer.Dropout(dpp),
        nn.Linear(channels * h * w // 4, class_num * 10, bias=False),
        LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(), detach_reset=detach_reset),
    )

class NeuromorphicNet(nn.Module):
    def __init__(self, T, init_tau, use_plif, use_max_pool, detach_reset):
        super().__init__()
        self.T = T
        self.init_tau = init_tau
        # self.use_plif = use_plif
        self.use_max_pool = use_max_pool
        # self.alpha_learnable = alpha_learnable
        self.detach_reset = detach_reset

        self.train_times = 0
        self.max_test_accuracy = 0
        self.epoch = 0
        self.conv = None
        self.fc = None
        self.boost = nn.AvgPool1d(10, 10)

    def forward(self, x):
        x = x.permute(1, 0, 2, 3, 4)  # [T, N, 2, *, *]  T时间戳, N batch_size 2正负极性, x,y就是x的像素大小
        out_spikes_counter = self.boost(self.fc(self.conv(x[0])).unsqueeze(1)).squeeze(1)
        for t in range(1, x.shape[0]):
            out_spikes_counter += self.boost(self.fc(self.conv(x[t])).unsqueeze(1)).squeeze(1)
        return out_spikes_counter

class NMNISTNet(NeuromorphicNet):
    def __init__(self, T, init_tau, use_plif, use_max_pool, detach_reset, channels, number_layer):
        super().__init__(T=T, init_tau=init_tau, use_plif=use_plif, use_max_pool=use_max_pool, detach_reset=detach_reset)
        w = 34
        h = 34  # 原始数据集尺寸
        self.conv = create_conv_sequential(2, channels, number_layer=number_layer, init_tau=init_tau, use_max_pool=use_max_pool, detach_reset=detach_reset)
        self.fc = create_2fc(channels=channels, w=w >> number_layer, h=h >>number_layer, dpp=0.5, class_num=10, init_tau=init_tau, detach_reset=detach_reset)

`

**Comment by BugCodeHub** [comment]
line 115, in <module>
    for img, label in train_data_loader:
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 137, in __getitem__
    sample = self.loader(path)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/spikingjelly/datasets/__init__.py", line 161, in load_npz_frames
    return np.load(file_name)['frames']
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 444, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by fangwei123456** [comment]
```
File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/spikingjelly/datasets/init.py", line 161, in load_npz_frames
return np.load(file_name)['frames']
```
从这个报错信息看，你还没有更新框架的代码？上次更新后，这里已经是

https://github.com/fangwei123456/spikingjelly/blob/199b3ad1e6537508207b5c5b4f364775a2ac8a62/spikingjelly/datasets/__init__.py#L161

**Comment by BugCodeHub** [comment]
好的，明天我试试看，感谢您的帮助！

**Comment by BugCodeHub** [comment]
我试了卸载更新，安装了0.0.0.6版本。还是会报上述的错误，有点奇怪了

**Comment by fangwei123456** [comment]
仍然是提示“File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/spikingjelly/datasets/init.py", line 161, in load_npz_frames
return np.load(file_name)['frames']”吗，更新后这里的代码按理说要变的

**Comment by BugCodeHub** [comment]
![F4}7 ZNAT%0$TA~L0R}PP](https://user-images.githubusercontent.com/33653847/128108214-ace29b28-4143-43dc-abf5-1885485549b9.png)

**Comment by BugCodeHub** [comment]
对的，就有点奇怪了。 上述代码应该没有问题吧

**Comment by fangwei123456** [comment]
切换到master版本。00006是已经发布的稳定版本，所以代码没法更新。主页的readme：
![image](https://user-images.githubusercontent.com/38352109/128108338-1f471722-3acf-4155-9cf3-78a9a91a0b97.png)

**Comment by BugCodeHub** [comment]
那个问题解决了，但是还是有点问题
/home/a401/.conda/envs/pytorch36/bin/python "/home/a401/SNN Attack/SNN-Attack-master/code/train_model/train.py"
Namespace(T=None, T_max=64, alpha_learnable=False, batch_size=16, channels=None, dataset_name='NMNIST', detach_reset=False, device=None, init_tau=None, learning_rate=0.001, log_dir_prefix=None, max_epoch=None, normalization=None, 
Traceback (most recent call last):
  File "/home/a401/train.py", line 115, in <module>
    for img, label in train_data_loader:
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 137, in __getitem__
    sample = self.loader(path)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/spikingjelly-0.0.0.0.7-py3.6.egg/spikingjelly/datasets/__init__.py", line 161, in load_npz_frames
    return np.load(file_name, allow_pickle=True)['frames']
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/home/a401/nmnist_model/datasets/N-MNIST/frames_number_20_split_by_number/train/6/00911.npz' as a pickle


Process finished with exit code 1

**Comment by fangwei123456** [comment]
/home/a401/nmnist_model/datasets/N-MNIST 这个文件夹里面的目录结构是？

**Comment by BugCodeHub** [comment]
没有理解您的意思。这里面就是处理完后的数据文件夹

**Comment by fangwei123456** [comment]
我的意思是这个文件夹里面有哪些目录，通过这个判断是老代码还是新代码进行的数据预处理

**Comment by BugCodeHub** [comment]
![~FZBI7Q_5QQVM@G{3_9FHOE](https://user-images.githubusercontent.com/33653847/128111796-1bd812cc-1bf3-4808-9362-5d37a010826c.png)

**Comment by fangwei123456** [comment]
我在我的电脑上试了一下可以正常运行：
```
from spikingjelly.datasets import n_mnist

dts = n_mnist.NMNIST(root='D:/datasets/NMNIST', train=True, data_type='frame', frames_number=20, split_by='number')
print(dts[0])
```
我上传一个npz文件（需要先解压），你用下面这个函数看能否在自己电脑上读取这个npz文件：
```
def load_npz_frames(file_name: str) -> np.ndarray:
    '''
    :param file_name: path of the npz file that saves the frames
    :type file_name: str
    :return: frames
    :rtype: np.ndarray
    '''
    return np.load(file_name, allow_pickle=True)['frames']
```

[00002.zip](https://github.com/fangwei123456/spikingjelly/files/6928165/00002.zip)

**Comment by BugCodeHub** [comment]
`import spikingjelly.datasets as dd
zss=dd.load_npz_frames('/home/a401/data/00002.npz')
print(zss)
`
![image](https://user-images.githubusercontent.com/33653847/128114524-81c67300-0535-4348-9a85-cb57c833e1cd.png)

**Comment by BugCodeHub** [comment]
这个是我有写错了吗。。。

**Comment by fangwei123456** [comment]
zip解压了吗

**Comment by BugCodeHub** [comment]
解压了

**Comment by fangwei123456** [comment]
打印一下直接用np.load(file_name, allow_pickle=True)输出的结果

**Comment by BugCodeHub** [comment]
![image](https://user-images.githubusercontent.com/33653847/128115252-045417c9-43f3-4523-8c76-44874fb11eee.png)

**Comment by fangwei123456** [comment]
顺便打印一下np.load(file_name, allow_pickle=True).files，看一下保存的keys是什么

**Comment by BugCodeHub** [comment]
![image](https://user-images.githubusercontent.com/33653847/128115360-2ff4fc10-9cef-46c6-b4e4-f7d60fbaca06.png)

**Comment by fangwei123456** [comment]
[00002.zip](https://github.com/fangwei123456/spikingjelly/files/6928296/00002.zip)
是我发错文件了，试一下下面这个zip解压后的npz，直接用“import spikingjelly.datasets as dd zss=dd.load_npz_frames('/home/a401/data/00002.npz') print(zss)”这段代码读取看是否报错。

**Comment by BugCodeHub** [comment]
这个可以正常运行了！

**Comment by BugCodeHub** [comment]
那应该是之前的我修改的代码哪里有问题吗

**Comment by fangwei123456** [comment]
你把文件夹里面除了download以外的文件夹全部删除，然后重新运行一次代码，用新的框架代码生成一次数据集再试试。如果是老的框架预处理数据，新框架可能与之不兼容

**Comment by BugCodeHub** [comment]
目前处理数据都没什么问题了，非常感谢大佬的热心回答！

**Comment by fangwei123456** [comment]
客气了~
