### ISSUE TITLE
对于训练好的模型，如果直接利用模型加载预训练模型会报错

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#95]
我这边设置了torch.backends.cuda.deterministic = True
                      torch.backends.cuda.benchmark= True
`    net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list".     net.load_state_dict(torch.load(model_path))
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NMNISTNet:
	Missing key(s) in state_dict: "conv.0.weight", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.4.weight", "conv.5.weight", "conv.5.bias", "conv.5.running_mean", "conv.5.running_var", "conv.8.weight", "conv.9.weight", "conv.9.bias", "conv.9.running_mean", "conv.9.running_var", "conv.12.weight", "conv.13.weight", "conv.13.bias", "conv.13.running_mean", "conv.13.running_var", "fc.2.weight", "fc.5.weight". 
	Unexpected key(s) in state_dict: "net", "optimizer", "scheduler", "log_data_list". 
`

**Comment by fangwei123456** [comment]
运行的是哪个代码？

**Comment by BugCodeHub** [comment]
我从您之前的代码跑完之后，得到的模型。后面我写了一个加载预训练模型，就报这个错
`
args = parser.parse_args()
argv = ' '.join(sys.argv)

print(args)
init_tau = 2.0
use_frame = True
batch_size = args.batch_size
learning_rate = args.learning_rate
T_max = args.T_max
# use_plif = args.use_plif
alpha_learnable = args.alpha_learnable
use_max_pool = args.use_max_pool
device = 'cuda'
dataset_name = args.dataset_name
dataset_dir = '/code/train_model/nmnist_model/datasets/' + 'N-MNIST'
# dataset_dir = '/raid/fangw01/cifar10'
log_dir_prefix = 'code/train_model/nmnist_model/logs'
T = 10
max_epoch = 100
detach_reset = args.detach_reset

number_layer = 2
channels = 128
split_by = 'number'
normalization = args.normalization
if normalization == 'None':
    normalization = None

class_num = 10  # 绝大多数数据集为10，如果不一样，在新建dataloader的时候再修改

train_data_loader = torch.utils.data.DataLoader(
    dataset=NMNIST(dataset_dir, train=True, data_type='frame', frames_number=20, split_by='number'),
    batch_size=batch_size,
    shuffle=True,
    num_workers=4,
    drop_last=True,
    pin_memory=True,
)
test_data_loader = torch.utils.data.DataLoader(
    dataset=NMNIST(dataset_dir, train=False, data_type='frame', frames_number=20, split_by='number'),
    batch_size=batch_size * 4,
    shuffle=False,
    num_workers=4,
    drop_last=False,
    pin_memory=True,

)

net = models.NMNISTNet(T=T, init_tau=init_tau, use_max_pool=use_max_pool,
                       detach_reset=detach_reset, channels=channels,
                       number_layer=number_layer).to(device)

print(net)
# 使用Adam优化器
optimizer = torch.optim.Adam(net.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=T_max)

for net.epoch in range(net.epoch, max_epoch):

    net.train()
    for img, label in train_data_loader:
        img = img.to(device)
        label = label.to(device)
        optimizer.zero_grad()
    # img = img.type(torch.cuda.FloatTensor)
        out_spikes_counter = net(img)
        out_spikes_counter_frequency = out_spikes_counter / net.T
        loss = F.mse_loss(out_spikes_counter_frequency, F.one_hot(label, class_num).float())
        loss.backward()
        optimizer.step()
        functional.reset_net(net)
        writer.add_scalar('train_correct_rate', correct_rate, train_times)
        if train_times % 100 == 0:
            print(device, dataset_dir, batch_size, learning_rate, T, train_epoch, log_dir, max_test_acccuracy)
        print(sys.argv, 'train_times', train_times, 'train_correct_rate', correct_rate)
        train_times += 1
    scheduler.step()

    net.eval()
    with torch.no_grad():
        test_sum = 0
        correct_sum = 0
        for img, label in test_data_loader:
            img = img.to(device)
            label = label.to(device)
            out_spikes_counter = net(img)
            correct_sum += (out_spikes_counter.argmax(dim=1) == label).float().sum().item()
            test_sum += label.numel()
            functional.reset_net(net)
        test_accuracy = correct_sum / test_sum
        print('test_accuracy', test_accuracy)

        if net.max_test_accuracy <= test_accuracy:
            print('save model with test_accuracy = ', test_accuracy)
            net.max_test_accuracy = test_accuracy
            torch.save({
                'net': net,
                'optimizer': optimizer.state_dict(),
                'scheduler': scheduler.state_dict(),
                'log_data_list': log_data_list
            }, check_point_max_path)

        # 保存最新模型
        torch.save({
            'net': net,
            'optimizer': optimizer.state_dict(),
            'scheduler': scheduler.state_dict(),
            'log_data_list': log_data_list
        }, check_point_path)
    writer.close()

`

**Comment by fangwei123456** [comment]
https://github.com/fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron/blob/07cf6d101c3573f1bf9d900aa7511c73ad95253b/codes/train.py#L251

原始代码是直接加载网络，而不是加载state dict。

你的代码里是 net.load_state_dict(torch.load(model_path))，所以报错

**Comment by BugCodeHub** [comment]
那我用该模型去预测其它NMINST数据的时候就直接加载吗

**Comment by fangwei123456** [comment]
按原始代码的方式来就行
```
        check_point = torch.load(check_point_path, map_location=device)
        net = check_point['net']
```
如果你要改代码，需要把保存和读取的同时更改为存取state dict

**Comment by BugCodeHub** [comment]
好的，谢谢了！
