### ISSUE TITLE
关于一些编码方式的性能

### ISSUE THREAD

**Issue by ZulunZhu** [fangwei123456/spikingjelly#96]
作者您好， 我了解的目前的编码方式都是以这样的泊松编码（当然我更愿意称其为Bernoulli编码）为主流，而且效果也是这种“用多个时间步长来仿真数据”比较好。目前关于event编码还有什么解决方案吗，因为看到event编码在Mnist上面都得不到很好的效果。

**Comment by fangwei123456** [comment]
看一下第八章。目前用的最多的是泊松、直接输入，以及TTFS。
[supp.pdf](https://github.com/fangwei123456/spikingjelly/files/6935771/supp.pdf)

**Comment by ZulunZhu** [comment]
最后一种Tempotron（就是编码成脉冲发射时间的） 目前的分类效果貌似都比较差？

**Comment by fangwei123456** [comment]
TTFS编码需要对神经元做一些调整，让整个网络都使用TTFS表示信息。参考这两篇文章：

[Temporal Backpropagation for Spiking Neural Networks with One Spike per Neuron](https://www.researchgate.net/publication/339990183_Temporal_Backpropagation_for_Spiking_Neural_Networks_with_One_Spike_per_Neuron)

[Training Energy-Efficient Deep Spiking Neural Networks with Single-Spike Hybrid Input Encoding
](https://arxiv.org/abs/2107.12374)

**Comment by ZulunZhu** [comment]
谢谢提醒，同时我也找到了这篇，性能更好，会议也不错：[https://ojs.aaai.org/index.php/AAAI/article/view/17329](url)。
