### ISSUE TITLE
问题：CIFAR10-DVS利用split_to_train_test_set得到的train和test数据集该如何处理数据

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#98]
请问下，从split_to_train_test_set（）得到ndarray类型的数据，在forward函数中，由于该类型数据没有permute属性，接下的数据该如何处理？
![image](https://user-images.githubusercontent.com/33653847/128442751-038395fa-f0ff-4fcc-a4f0-eeadcb67d39f.png)

**Comment by fangwei123456** [comment]
`split_to_train_test_set`返回的数据集类型的`torch.utils.data.Dataset`。如果不通过`DataLoader`包装`torch.utils.data.Dataset`而是直接访问，需要使用`torch.from_numpy(ndarray) → Tensor`
