### ISSUE TITLE
NMNIST最后输出层的可视化各脉冲频率该如何执行呢？对于经过网络处理完的图片能否可视化它在仿真步长内的脉冲？

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#99]
我是这样写的
![image](https://user-images.githubusercontent.com/33653847/128673706-592d860d-4238-4b9e-adf7-0f86846a0314.png)

**Comment by fangwei123456** [comment]
要进行可视化的数据，提前记录下来就行了。建议学习一下pytorch的钩子，通过钩子可以获取任意一层的输出脉冲

**Comment by fangwei123456** [comment]
因为输出脉冲默认是不会保存到模块内的

**Comment by BugCodeHub** [comment]
那我就不能够直接从net中直接获取电压信息了吗，需要在每一层处理的时候就要保存脉冲信息吗

**Comment by fangwei123456** [comment]
模块`m`的电压是可以直接通过`m.v`获取的。

> 因为输出脉冲默认是不会保存到模块内的

这个说错了，新版的框架也可以获取脉冲了，`m.spike`

需要注意的一点是，v和spike都是当前时刻的，每运行一次网络，都会有新数据覆盖旧数据

**Comment by BugCodeHub** [comment]
NMNIST的net好像不能直接用net[-1]定位到最后一层，那我如果想要定位到最后一层该怎么办呢

**Comment by fangwei123456** [comment]
`net.fc[-1]`

**Comment by BugCodeHub** [comment]
我这样获取当前的v和spike不太行，这个该如何处理呢
![image](https://user-images.githubusercontent.com/33653847/128679550-0d51b427-3dbc-4713-a18e-4cb9b2aa5edc.png)
![image](https://user-images.githubusercontent.com/33653847/128679586-affce642-049b-4b34-81f3-18956f7324a4.png)

**Comment by fangwei123456** [comment]
v_t_array打印出来看看是否正常

**Comment by BugCodeHub** [comment]
由于我是测试一张图片的，v_t_array 打印输出为0.0  s_t_array 也是0.0

**Comment by BugCodeHub** [comment]
这个感觉是有问题的吧

**Comment by fangwei123456** [comment]
这是因为初始化的时候电压被设置成0.(float)，经过一次运算后才会变成tensor。

**Comment by BugCodeHub** [comment]
我好像发现问题了。。
